module.exports = [

  // ── AI / ML Vendors ───────────────────────────────────────────────────────
  {
    id: 'nvidia',
    vendor: 'NVIDIA',
    url: 'https://www.nvidia.com/en-us/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['nvidia', 'gtc', 'gpu', 'ai'],
  },
  {
    id: 'databricks',
    vendor: 'Databricks',
    url: 'https://www.databricks.com/events',
    defaultCategories: ['AI', 'Data'],
    tags: ['databricks', 'data+ai summit', 'spark'],
  },
  {
    id: 'huggingface',
    vendor: 'Hugging Face',
    url: 'https://huggingface.co/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['hugging face', 'llm', 'open source ai'],
  },
  {
    id: 'scaleai',
    vendor: 'Scale AI',
    url: 'https://scale.com/events',
    defaultCategories: ['AI'],
    tags: ['scale ai', 'data labeling'],
  },
  {
    id: 'wandb',
    vendor: 'Weights & Biases',
    url: 'https://wandb.ai/site/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['weights and biases', 'wandb', 'mlops'],
  },
  {
    id: 'cohere',
    vendor: 'Cohere',
    url: 'https://cohere.com/events',
    defaultCategories: ['AI'],
    tags: ['cohere', 'llm', 'nlp'],
  },
  {
    id: 'datarobot',
    vendor: 'DataRobot',
    url: 'https://www.datarobot.com/events/',
    defaultCategories: ['AI'],
    tags: ['datarobot', 'automl'],
  },
  {
    id: 'h2oai',
    vendor: 'H2O.ai',
    url: 'https://h2oworld.h2o.ai/',
    defaultCategories: ['AI'],
    tags: ['h2o.ai', 'automl', 'machine learning'],
  },
  {
    id: 'anyscale',
    vendor: 'Anyscale',
    url: 'https://www.anyscale.com/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['anyscale', 'ray', 'distributed ml'],
  },
  {
    id: 'tecton',
    vendor: 'Tecton',
    url: 'https://www.tecton.ai/events/',
    defaultCategories: ['AI', 'Data'],
    tags: ['tecton', 'feature store', 'mlops'],
  },
  {
    id: 'lfai',
    vendor: 'LF AI & Data Foundation',
    url: 'https://lfaidata.foundation/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['lf ai', 'linux foundation', 'open source ai'],
  },
  {
    id: 'openai-events',
    vendor: 'OpenAI',
    url: 'https://openai.com/news',
    defaultCategories: ['AI'],
    tags: ['openai', 'gpt', 'chatgpt'],
  },
  {
    id: 'lightning-ai',
    vendor: 'Lightning AI',
    url: 'https://lightning.ai/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['lightning ai', 'pytorch lightning'],
  },
  {
    id: 'seldon',
    vendor: 'Seldon',
    url: 'https://www.seldon.io/events',
    defaultCategories: ['AI'],
    tags: ['seldon', 'mlops', 'model serving'],
  },
  {
    id: 'c3ai',
    vendor: 'C3.ai',
    url: 'https://c3.ai/events/',
    defaultCategories: ['AI'],
    tags: ['c3.ai', 'enterprise ai'],
  },
  {
    id: 'sas',
    vendor: 'SAS',
    url: 'https://www.sas.com/en_us/events/sas-global-forum.html',
    defaultCategories: ['AI', 'Data'],
    tags: ['sas', 'analytics', 'data science'],
  },
  {
    id: 'alteryx',
    vendor: 'Alteryx',
    url: 'https://www.alteryx.com/events',
    defaultCategories: ['AI', 'Data'],
    tags: ['alteryx', 'analytics', 'data prep'],
  },
  {
    id: 'domino-data',
    vendor: 'Domino Data Lab',
    url: 'https://www.dominodatalab.com/resources/events',
    defaultCategories: ['AI', 'Data'],
    tags: ['domino data lab', 'data science platform'],
  },

  // ── AI Research Conferences ────────────────────────────────────────────────
  {
    id: 'neurips',
    vendor: 'NeurIPS',
    url: 'https://nips.cc/',
    defaultCategories: ['AI'],
    tags: ['neurips', 'deep learning', 'ml research'],
  },
  {
    id: 'icml',
    vendor: 'ICML',
    url: 'https://icml.cc/',
    defaultCategories: ['AI'],
    tags: ['icml', 'machine learning research'],
  },
  {
    id: 'iclr',
    vendor: 'ICLR',
    url: 'https://iclr.cc/',
    defaultCategories: ['AI'],
    tags: ['iclr', 'deep learning research'],
  },
  {
    id: 'cvpr',
    vendor: 'CVPR',
    url: 'https://cvpr.thecvf.com/',
    defaultCategories: ['AI'],
    tags: ['cvpr', 'computer vision'],
  },
  {
    id: 'aaai',
    vendor: 'AAAI',
    url: 'https://aaai.org/conference/',
    defaultCategories: ['AI'],
    tags: ['aaai', 'ai research'],
  },
  {
    id: 'acl-nlp',
    vendor: 'ACL (NLP)',
    url: 'https://www.aclweb.org/portal/content/upcoming-acl-events',
    defaultCategories: ['AI'],
    tags: ['acl', 'nlp', 'natural language processing'],
  },
];
