module.exports = [

  // ── AI / ML Vendors ───────────────────────────────────────────────────────
  {
    id: 'nvidia',
    vendor: 'NVIDIA',
    url: 'https://www.nvidia.com/en-us/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['nvidia', 'gtc', 'gpu', 'ai'],
  },
  {
    id: 'databricks',
    vendor: 'Databricks',
    url: 'https://www.databricks.com/events',
    defaultCategories: ['AI', 'Data'],
    tags: ['databricks', 'data+ai summit', 'spark'],
  },
  {
    id: 'huggingface',
    vendor: 'Hugging Face',
    url: 'https://huggingface.co/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['hugging face', 'llm', 'open source ai'],
  },
  {
    id: 'scaleai',
    vendor: 'Scale AI',
    url: 'https://scale.com/events',
    defaultCategories: ['AI'],
    tags: ['scale ai', 'data labeling'],
  },
  {
    id: 'wandb',
    vendor: 'Weights & Biases',
    url: 'https://wandb.ai/site/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['weights and biases', 'wandb', 'mlops'],
  },
  {
    id: 'cohere',
    vendor: 'Cohere',
    url: 'https://cohere.com/events',
    defaultCategories: ['AI'],
    tags: ['cohere', 'llm', 'nlp'],
  },
  {
    id: 'datarobot',
    vendor: 'DataRobot',
    url: 'https://www.datarobot.com/events/',
    defaultCategories: ['AI'],
    tags: ['datarobot', 'automl'],
  },
  {
    id: 'h2oai',
    vendor: 'H2O.ai',
    url: 'https://h2oworld.h2o.ai/',
    defaultCategories: ['AI'],
    tags: ['h2o.ai', 'automl', 'machine learning'],
  },
  {
    id: 'anyscale',
    vendor: 'Anyscale',
    url: 'https://www.anyscale.com/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['anyscale', 'ray', 'distributed ml'],
  },
  {
    id: 'tecton',
    vendor: 'Tecton',
    url: 'https://www.tecton.ai/events/',
    defaultCategories: ['AI', 'Data'],
    tags: ['tecton', 'feature store', 'mlops'],
  },
  {
    id: 'lfai',
    vendor: 'LF AI & Data Foundation',
    url: 'https://lfaidata.foundation/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['lf ai', 'linux foundation', 'open source ai'],
  },
  {
    id: 'openai-events',
    vendor: 'OpenAI',
    url: 'https://openai.com/news',
    defaultCategories: ['AI'],
    tags: ['openai', 'gpt', 'chatgpt'],
  },
  {
    id: 'lightning-ai',
    vendor: 'Lightning AI',
    url: 'https://lightning.ai/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['lightning ai', 'pytorch lightning'],
  },
  {
    id: 'seldon',
    vendor: 'Seldon',
    url: 'https://www.seldon.io/events',
    defaultCategories: ['AI'],
    tags: ['seldon', 'mlops', 'model serving'],
  },
  {
    id: 'c3ai',
    vendor: 'C3.ai',
    url: 'https://c3.ai/events/',
    defaultCategories: ['AI'],
    tags: ['c3.ai', 'enterprise ai'],
  },
  {
    id: 'sas',
    vendor: 'SAS',
    url: 'https://www.sas.com/en_us/events/sas-global-forum.html',
    defaultCategories: ['AI', 'Data'],
    tags: ['sas', 'analytics', 'data science'],
  },
  {
    id: 'alteryx',
    vendor: 'Alteryx',
    url: 'https://www.alteryx.com/events',
    defaultCategories: ['AI', 'Data'],
    tags: ['alteryx', 'analytics', 'data prep'],
  },
  {
    id: 'domino-data',
    vendor: 'Domino Data Lab',
    url: 'https://www.dominodatalab.com/resources/events',
    defaultCategories: ['AI', 'Data'],
    tags: ['domino data lab', 'data science platform'],
  },

  // ── Foundation Model / LLM Providers ─────────────────────────────────────
  {
    id: 'anthropic',
    vendor: 'Anthropic',
    url: 'https://www.anthropic.com/news',
    defaultCategories: ['AI'],
    tags: ['anthropic', 'claude', 'llm', 'ai safety'],
  },
  {
    id: 'google-deepmind',
    vendor: 'Google DeepMind',
    url: 'https://deepmind.google/about/events/',
    defaultCategories: ['AI'],
    tags: ['deepmind', 'gemini', 'llm', 'ai research'],
  },
  {
    id: 'meta-ai',
    vendor: 'Meta AI',
    url: 'https://ai.meta.com/events/',
    defaultCategories: ['AI'],
    tags: ['meta ai', 'llama', 'open source llm'],
  },
  {
    id: 'microsoft-azure-ai',
    vendor: 'Microsoft Azure AI',
    url: 'https://azure.microsoft.com/en-us/community/events/',
    defaultCategories: ['AI', 'Cloud'],
    tags: ['azure', 'microsoft ai', 'copilot', 'llm'],
  },
  {
    id: 'amazon-ai',
    vendor: 'Amazon AI',
    url: 'https://aws.amazon.com/events/',
    defaultCategories: ['AI', 'Cloud'],
    tags: ['aws', 'amazon ai', 'bedrock', 'sagemaker'],
  },
  {
    id: 'mistral-ai',
    vendor: 'Mistral AI',
    url: 'https://mistral.ai/news/',
    defaultCategories: ['AI'],
    tags: ['mistral', 'llm', 'open weights', 'european ai'],
  },
  {
    id: 'stability-ai',
    vendor: 'Stability AI',
    url: 'https://stability.ai/events',
    defaultCategories: ['AI'],
    tags: ['stability ai', 'stable diffusion', 'generative ai', 'image ai'],
  },
  {
    id: 'ai21-labs',
    vendor: 'AI21 Labs',
    url: 'https://www.ai21.com/events',
    defaultCategories: ['AI'],
    tags: ['ai21', 'jurassic', 'llm', 'nlp'],
  },
  {
    id: 'aleph-alpha',
    vendor: 'Aleph Alpha',
    url: 'https://aleph-alpha.com/events/',
    defaultCategories: ['AI'],
    tags: ['aleph alpha', 'european ai', 'llm', 'explainability'],
  },
  {
    id: 'inflection-ai',
    vendor: 'Inflection AI',
    url: 'https://inflection.ai/events',
    defaultCategories: ['AI'],
    tags: ['inflection ai', 'pi', 'conversational ai', 'llm'],
  },
  {
    id: 'perplexity-ai',
    vendor: 'Perplexity AI',
    url: 'https://www.perplexity.ai/hub',
    defaultCategories: ['AI'],
    tags: ['perplexity', 'search ai', 'llm', 'answer engine'],
  },
  {
    id: 'together-ai',
    vendor: 'Together AI',
    url: 'https://www.together.ai/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['together ai', 'llm inference', 'open source models'],
  },
  {
    id: 'replicate',
    vendor: 'Replicate',
    url: 'https://replicate.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['replicate', 'model hosting', 'ml api', 'generative ai'],
  },
  {
    id: 'gradient-ai',
    vendor: 'Gradient AI',
    url: 'https://gradient.ai/events',
    defaultCategories: ['AI'],
    tags: ['gradient ai', 'llm fine-tuning', 'enterprise ai'],
  },
  {
    id: 'writer',
    vendor: 'Writer',
    url: 'https://writer.com/events/',
    defaultCategories: ['AI'],
    tags: ['writer', 'enterprise llm', 'content ai', 'generative ai'],
  },
  {
    id: 'jasper-ai',
    vendor: 'Jasper AI',
    url: 'https://www.jasper.ai/events',
    defaultCategories: ['AI'],
    tags: ['jasper', 'content generation', 'marketing ai', 'llm'],
  },
  {
    id: 'runway-ml',
    vendor: 'Runway ML',
    url: 'https://runwayml.com/blog',
    defaultCategories: ['AI'],
    tags: ['runway', 'generative video', 'creative ai', 'diffusion'],
  },
  {
    id: 'elevenlabs',
    vendor: 'ElevenLabs',
    url: 'https://elevenlabs.io/blog',
    defaultCategories: ['AI'],
    tags: ['elevenlabs', 'voice ai', 'text to speech', 'audio ai'],
  },
  {
    id: 'synthesia',
    vendor: 'Synthesia',
    url: 'https://www.synthesia.io/events',
    defaultCategories: ['AI'],
    tags: ['synthesia', 'ai video', 'avatar', 'generative ai'],
  },
  {
    id: 'pika-labs',
    vendor: 'Pika Labs',
    url: 'https://www.pika.art/blog',
    defaultCategories: ['AI'],
    tags: ['pika', 'video generation', 'generative ai', 'creative ai'],
  },
  {
    id: 'luma-ai',
    vendor: 'Luma AI',
    url: 'https://lumalabs.ai/events',
    defaultCategories: ['AI'],
    tags: ['luma ai', '3d generation', 'nerf', 'generative ai'],
  },
  {
    id: 'character-ai',
    vendor: 'Character AI',
    url: 'https://character.ai/blog',
    defaultCategories: ['AI'],
    tags: ['character ai', 'conversational ai', 'llm', 'chatbot'],
  },
  {
    id: 'xai-grok',
    vendor: 'xAI (Grok)',
    url: 'https://x.ai/blog',
    defaultCategories: ['AI'],
    tags: ['xai', 'grok', 'llm', 'elon musk ai'],
  },

  // ── MLOps / Model Lifecycle ───────────────────────────────────────────────
  {
    id: 'iterative-dvc',
    vendor: 'Iterative (DVC)',
    url: 'https://iterative.ai/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['iterative', 'dvc', 'mlops', 'data versioning'],
  },
  {
    id: 'bentoml',
    vendor: 'BentoML',
    url: 'https://www.bentoml.com/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['bentoml', 'model serving', 'mlops', 'deployment'],
  },
  {
    id: 'zenml',
    vendor: 'ZenML',
    url: 'https://www.zenml.io/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['zenml', 'mlops', 'pipelines', 'open source'],
  },
  {
    id: 'evidently-ai',
    vendor: 'Evidently AI',
    url: 'https://www.evidentlyai.com/events',
    defaultCategories: ['AI'],
    tags: ['evidently', 'model monitoring', 'mlops', 'data drift'],
  },
  {
    id: 'whylabs',
    vendor: 'WhyLabs',
    url: 'https://whylabs.ai/events',
    defaultCategories: ['AI'],
    tags: ['whylabs', 'model monitoring', 'data quality', 'observability'],
  },
  {
    id: 'fiddler-ai',
    vendor: 'Fiddler AI',
    url: 'https://www.fiddler.ai/events',
    defaultCategories: ['AI'],
    tags: ['fiddler', 'explainability', 'model monitoring', 'responsible ai'],
  },
  {
    id: 'arthur-ai',
    vendor: 'Arthur AI',
    url: 'https://www.arthur.ai/events',
    defaultCategories: ['AI'],
    tags: ['arthur ai', 'model monitoring', 'fairness', 'explainability'],
  },
  {
    id: 'arize-ai',
    vendor: 'Arize AI',
    url: 'https://arize.com/events/',
    defaultCategories: ['AI'],
    tags: ['arize', 'ml observability', 'model monitoring', 'mlops'],
  },
  {
    id: 'superwise',
    vendor: 'Superwise',
    url: 'https://superwise.ai/events',
    defaultCategories: ['AI'],
    tags: ['superwise', 'model observability', 'mlops', 'monitoring'],
  },
  {
    id: 'aporia',
    vendor: 'Aporia',
    url: 'https://www.aporia.com/events',
    defaultCategories: ['AI'],
    tags: ['aporia', 'ml monitoring', 'guardrails', 'responsible ai'],
  },
  {
    id: 'valohai',
    vendor: 'Valohai',
    url: 'https://valohai.com/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['valohai', 'mlops', 'pipeline orchestration', 'training'],
  },
  {
    id: 'cometml',
    vendor: 'CometML',
    url: 'https://www.comet.com/site/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['comet', 'experiment tracking', 'mlops', 'model management'],
  },
  {
    id: 'neptune-ai',
    vendor: 'Neptune AI',
    url: 'https://neptune.ai/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['neptune', 'experiment tracking', 'model registry', 'mlops'],
  },
  {
    id: 'clearml',
    vendor: 'ClearML',
    url: 'https://clear.ml/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['clearml', 'mlops', 'experiment management', 'open source'],
  },
  {
    id: 'pachyderm',
    vendor: 'Pachyderm',
    url: 'https://www.pachyderm.com/events/',
    defaultCategories: ['AI', 'Data'],
    tags: ['pachyderm', 'data versioning', 'mlops', 'pipelines'],
  },
  {
    id: 'metaflow',
    vendor: 'Metaflow',
    url: 'https://outerbounds.com/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['metaflow', 'netflix', 'ml workflows', 'python'],
  },
  {
    id: 'flyte',
    vendor: 'Flyte',
    url: 'https://flyte.org/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['flyte', 'ml orchestration', 'workflows', 'open source'],
  },
  {
    id: 'prefect',
    vendor: 'Prefect',
    url: 'https://www.prefect.io/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['prefect', 'workflow orchestration', 'dataops', 'python'],
  },
  {
    id: 'mlflow-events',
    vendor: 'MLflow (Databricks)',
    url: 'https://www.databricks.com/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['mlflow', 'experiment tracking', 'model registry', 'open source'],
  },

  // ── AI Governance / Safety / Explainability ───────────────────────────────
  {
    id: 'holistic-ai',
    vendor: 'Holistic AI',
    url: 'https://www.holisticai.com/events',
    defaultCategories: ['AI'],
    tags: ['ai governance', 'responsible ai', 'risk', 'compliance'],
  },
  {
    id: 'credo-ai',
    vendor: 'Credo AI',
    url: 'https://www.credo.ai/events',
    defaultCategories: ['AI'],
    tags: ['credo ai', 'ai governance', 'responsible ai', 'compliance'],
  },
  {
    id: 'fairly-ai',
    vendor: 'Fairly AI',
    url: 'https://fairly.ai/events',
    defaultCategories: ['AI'],
    tags: ['fairly ai', 'ai fairness', 'bias detection', 'governance'],
  },
  {
    id: 'ibm-watsonx',
    vendor: 'IBM Watsonx',
    url: 'https://www.ibm.com/events',
    defaultCategories: ['AI'],
    tags: ['ibm', 'watsonx', 'enterprise ai', 'governance'],
  },
  {
    id: 'robust-intelligence',
    vendor: 'Robust Intelligence',
    url: 'https://www.robustintelligence.com/events',
    defaultCategories: ['AI'],
    tags: ['robust intelligence', 'ai security', 'model testing', 'red teaming'],
  },
  {
    id: 'kolena',
    vendor: 'Kolena',
    url: 'https://www.kolena.com/events',
    defaultCategories: ['AI'],
    tags: ['kolena', 'model testing', 'evaluation', 'quality assurance'],
  },
  {
    id: 'truera',
    vendor: 'TruEra',
    url: 'https://truera.com/events/',
    defaultCategories: ['AI'],
    tags: ['truera', 'ai quality', 'explainability', 'model monitoring'],
  },
  {
    id: 'alibi-detect',
    vendor: 'Alibi Detect (Seldon)',
    url: 'https://www.seldon.io/events',
    defaultCategories: ['AI'],
    tags: ['alibi detect', 'outlier detection', 'drift', 'explainability'],
  },
  {
    id: 'ai-alliance',
    vendor: 'AI Alliance',
    url: 'https://thealliance.ai/events',
    defaultCategories: ['AI'],
    tags: ['ai alliance', 'open ai', 'governance', 'standards'],
  },
  {
    id: 'partnership-on-ai',
    vendor: 'Partnership on AI',
    url: 'https://partnershiponai.org/events/',
    defaultCategories: ['AI'],
    tags: ['partnership on ai', 'responsible ai', 'policy', 'safety'],
  },
  {
    id: 'responsible-ai-institute',
    vendor: 'Responsible AI Institute',
    url: 'https://www.responsible.ai/events',
    defaultCategories: ['AI'],
    tags: ['responsible ai', 'certification', 'governance', 'ethics'],
  },
  {
    id: 'nist-ai',
    vendor: 'NIST AI (Events)',
    url: 'https://www.nist.gov/artificial-intelligence',
    defaultCategories: ['AI'],
    tags: ['nist', 'ai standards', 'ai rmf', 'government ai'],
  },

  // ── Vector Databases & AI Infrastructure ─────────────────────────────────
  {
    id: 'pinecone',
    vendor: 'Pinecone',
    url: 'https://www.pinecone.io/events/',
    defaultCategories: ['AI', 'Data'],
    tags: ['pinecone', 'vector database', 'embeddings', 'rag'],
  },
  {
    id: 'weaviate',
    vendor: 'Weaviate',
    url: 'https://weaviate.io/community/events',
    defaultCategories: ['AI', 'Data'],
    tags: ['weaviate', 'vector database', 'semantic search', 'rag'],
  },
  {
    id: 'qdrant',
    vendor: 'Qdrant',
    url: 'https://qdrant.tech/blog/',
    defaultCategories: ['AI', 'Data'],
    tags: ['qdrant', 'vector database', 'similarity search', 'open source'],
  },
  {
    id: 'zilliz-milvus',
    vendor: 'Zilliz (Milvus)',
    url: 'https://zilliz.com/events',
    defaultCategories: ['AI', 'Data'],
    tags: ['zilliz', 'milvus', 'vector database', 'similarity search'],
  },
  {
    id: 'singlestore-ai',
    vendor: 'SingleStore AI',
    url: 'https://www.singlestore.com/events/',
    defaultCategories: ['AI', 'Data'],
    tags: ['singlestore', 'ai database', 'vector search', 'real-time'],
  },
  {
    id: 'redis-ai',
    vendor: 'Redis AI',
    url: 'https://redis.com/events/',
    defaultCategories: ['AI', 'Data'],
    tags: ['redis', 'vector search', 'in-memory', 'ai database'],
  },
  {
    id: 'activeloop',
    vendor: 'Activeloop',
    url: 'https://www.activeloop.ai/events',
    defaultCategories: ['AI', 'Data'],
    tags: ['activeloop', 'deep lake', 'dataset storage', 'embeddings'],
  },
  {
    id: 'llamaindex-events',
    vendor: 'LlamaIndex',
    url: 'https://www.llamaindex.ai/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['llamaindex', 'rag', 'llm framework', 'data indexing'],
  },
  {
    id: 'langchain-events',
    vendor: 'LangChain',
    url: 'https://www.langchain.com/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['langchain', 'llm framework', 'agents', 'rag'],
  },
  {
    id: 'haystack-deepset',
    vendor: 'Haystack (deepset)',
    url: 'https://haystack.deepset.ai/community',
    defaultCategories: ['AI', 'Developer'],
    tags: ['haystack', 'deepset', 'nlp', 'rag'],
  },
  {
    id: 'chroma',
    vendor: 'Chroma',
    url: 'https://www.trychroma.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['chroma', 'vector database', 'embeddings', 'open source'],
  },

  // ── AI Chips / Hardware ───────────────────────────────────────────────────
  {
    id: 'intel-habana',
    vendor: 'Intel Habana Labs',
    url: 'https://www.intel.com/content/www/us/en/events/overview.html',
    defaultCategories: ['AI'],
    tags: ['intel', 'habana', 'ai accelerator', 'deep learning chip'],
  },
  {
    id: 'amd-rocm',
    vendor: 'AMD ROCm',
    url: 'https://www.amd.com/en/developer/resources/events.html',
    defaultCategories: ['AI', 'Developer'],
    tags: ['amd', 'rocm', 'gpu', 'ai hardware'],
  },
  {
    id: 'graphcore',
    vendor: 'Graphcore',
    url: 'https://www.graphcore.ai/events',
    defaultCategories: ['AI'],
    tags: ['graphcore', 'ipu', 'ai chip', 'deep learning hardware'],
  },
  {
    id: 'cerebras',
    vendor: 'Cerebras Systems',
    url: 'https://www.cerebras.net/events/',
    defaultCategories: ['AI'],
    tags: ['cerebras', 'wafer scale', 'ai chip', 'training hardware'],
  },
  {
    id: 'sambanova',
    vendor: 'SambaNova Systems',
    url: 'https://sambanova.ai/events/',
    defaultCategories: ['AI'],
    tags: ['sambanova', 'ai chip', 'inference', 'dataflow architecture'],
  },
  {
    id: 'groq-chip',
    vendor: 'Groq',
    url: 'https://groq.com/events/',
    defaultCategories: ['AI'],
    tags: ['groq', 'lpu', 'inference chip', 'ai hardware'],
  },
  {
    id: 'tenstorrent',
    vendor: 'Tenstorrent',
    url: 'https://tenstorrent.com/blog/',
    defaultCategories: ['AI'],
    tags: ['tenstorrent', 'ai chip', 'risc-v', 'ml hardware'],
  },
  {
    id: 'axelera-ai',
    vendor: 'Axelera AI',
    url: 'https://www.axelera.ai/events/',
    defaultCategories: ['AI'],
    tags: ['axelera', 'edge ai', 'vision chip', 'inference'],
  },
  {
    id: 'd-matrix',
    vendor: 'D-Matrix',
    url: 'https://www.d-matrix.ai/news-events/',
    defaultCategories: ['AI'],
    tags: ['d-matrix', 'inference chip', 'in-memory compute', 'ai hardware'],
  },
  {
    id: 'rebellions',
    vendor: 'Rebellions',
    url: 'https://rebellions.ai/events',
    defaultCategories: ['AI'],
    tags: ['rebellions', 'ai chip', 'inference', 'npai'],
  },

  // ── AI for Healthcare / Life Sciences ────────────────────────────────────
  {
    id: 'pathai',
    vendor: 'PathAI',
    url: 'https://www.pathai.com/events/',
    defaultCategories: ['AI'],
    tags: ['pathai', 'pathology ai', 'digital pathology', 'healthcare ai'],
  },
  {
    id: 'tempus-ai',
    vendor: 'Tempus AI',
    url: 'https://www.tempus.com/events/',
    defaultCategories: ['AI'],
    tags: ['tempus', 'clinical ai', 'genomics', 'precision medicine'],
  },
  {
    id: 'benevolentai',
    vendor: 'BenevolentAI',
    url: 'https://www.benevolent.com/news-and-events/',
    defaultCategories: ['AI'],
    tags: ['benevolentai', 'drug discovery', 'biotech ai', 'life sciences'],
  },
  {
    id: 'insilico-medicine',
    vendor: 'Insilico Medicine',
    url: 'https://insilico.com/events',
    defaultCategories: ['AI'],
    tags: ['insilico', 'drug discovery', 'generative chemistry', 'longevity'],
  },
  {
    id: 'recursion',
    vendor: 'Recursion Pharmaceuticals',
    url: 'https://www.recursion.com/news',
    defaultCategories: ['AI'],
    tags: ['recursion', 'drug discovery', 'biopharma ai', 'life sciences'],
  },
  {
    id: 'veeva-crossix',
    vendor: 'Veeva Crossix',
    url: 'https://www.veeva.com/events/',
    defaultCategories: ['AI', 'Data'],
    tags: ['veeva', 'crossix', 'healthcare data', 'pharma analytics'],
  },
  {
    id: 'google-health-ai',
    vendor: 'Google Health AI',
    url: 'https://health.google/events/',
    defaultCategories: ['AI'],
    tags: ['google health', 'medical ai', 'clinical nlp', 'healthcare ai'],
  },
  {
    id: 'microsoft-health-ai',
    vendor: 'Microsoft Health AI',
    url: 'https://www.microsoft.com/en-us/health/events',
    defaultCategories: ['AI'],
    tags: ['microsoft health', 'azure health', 'clinical ai', 'interoperability'],
  },
  {
    id: 'nuance-microsoft',
    vendor: 'Nuance (Microsoft)',
    url: 'https://www.nuance.com/healthcare/events.html',
    defaultCategories: ['AI'],
    tags: ['nuance', 'dax', 'clinical documentation', 'voice ai'],
  },
  {
    id: 'enlitic',
    vendor: 'Enlitic',
    url: 'https://enlitic.com/events/',
    defaultCategories: ['AI'],
    tags: ['enlitic', 'radiology ai', 'medical imaging', 'dicom'],
  },
  {
    id: 'aidoc',
    vendor: 'Aidoc',
    url: 'https://www.aidoc.com/events/',
    defaultCategories: ['AI'],
    tags: ['aidoc', 'radiology ai', 'triage', 'medical imaging'],
  },
  {
    id: 'vizai',
    vendor: 'Viz.ai',
    url: 'https://www.viz.ai/events',
    defaultCategories: ['AI'],
    tags: ['viz.ai', 'care coordination', 'stroke ai', 'clinical ai'],
  },

  // ── AI for Legal / Finance / Enterprise ──────────────────────────────────
  {
    id: 'harvey-ai',
    vendor: 'Harvey AI',
    url: 'https://www.harvey.ai/blog',
    defaultCategories: ['AI'],
    tags: ['harvey', 'legal ai', 'law tech', 'contract review'],
  },
  {
    id: 'ironclad-ai',
    vendor: 'Ironclad AI',
    url: 'https://ironcladapp.com/events/',
    defaultCategories: ['AI'],
    tags: ['ironclad', 'contract management', 'legal ai', 'clm'],
  },
  {
    id: 'kira-systems',
    vendor: 'Kira Systems (Litera)',
    url: 'https://www.litera.com/events/',
    defaultCategories: ['AI'],
    tags: ['kira', 'litera', 'contract analysis', 'legal ai'],
  },
  {
    id: 'luminance',
    vendor: 'Luminance',
    url: 'https://www.luminance.com/events/',
    defaultCategories: ['AI'],
    tags: ['luminance', 'legal ai', 'due diligence', 'document review'],
  },
  {
    id: 'kensho',
    vendor: 'Kensho (S&P Global)',
    url: 'https://kensho.com/blog',
    defaultCategories: ['AI', 'Data'],
    tags: ['kensho', 's&p global', 'financial ai', 'analytics'],
  },
  {
    id: 'alphasense',
    vendor: 'AlphaSense',
    url: 'https://www.alpha-sense.com/events/',
    defaultCategories: ['AI'],
    tags: ['alphasense', 'market intelligence', 'financial research', 'nlp'],
  },
  {
    id: 'numerai',
    vendor: 'Numerai',
    url: 'https://numer.ai/tournament',
    defaultCategories: ['AI', 'Data'],
    tags: ['numerai', 'quant finance', 'hedge fund', 'data science'],
  },
  {
    id: 'aiera',
    vendor: 'Aiera',
    url: 'https://www.aiera.com/events',
    defaultCategories: ['AI'],
    tags: ['aiera', 'financial nlp', 'earnings calls', 'investment ai'],
  },
  {
    id: 'indico-data',
    vendor: 'Indico Data',
    url: 'https://indicodata.ai/events/',
    defaultCategories: ['AI'],
    tags: ['indico', 'intelligent document processing', 'enterprise ai', 'nlp'],
  },
  {
    id: 'automation-anywhere',
    vendor: 'Automation Anywhere',
    url: 'https://www.automationanywhere.com/company/events',
    defaultCategories: ['AI'],
    tags: ['automation anywhere', 'rpa', 'intelligent automation', 'enterprise ai'],
  },
  {
    id: 'uipath-ai',
    vendor: 'UiPath AI',
    url: 'https://www.uipath.com/events',
    defaultCategories: ['AI'],
    tags: ['uipath', 'rpa', 'process automation', 'agentic ai'],
  },
  {
    id: 'blueprism-ai',
    vendor: 'Blue Prism AI',
    url: 'https://www.blueprism.com/events/',
    defaultCategories: ['AI'],
    tags: ['blue prism', 'rpa', 'intelligent automation', 'enterprise ai'],
  },

  // ── Computer Vision / Robotics AI ────────────────────────────────────────
  {
    id: 'roboflow',
    vendor: 'Roboflow',
    url: 'https://roboflow.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['roboflow', 'computer vision', 'dataset', 'object detection'],
  },
  {
    id: 'landing-ai',
    vendor: 'Landing AI',
    url: 'https://landing.ai/events/',
    defaultCategories: ['AI'],
    tags: ['landing ai', 'visual ai', 'industrial inspection', 'andrew ng'],
  },
  {
    id: 'cognitivescale',
    vendor: 'CognitiveScale',
    url: 'https://www.cognitivescale.com/events/',
    defaultCategories: ['AI'],
    tags: ['cognitivescale', 'enterprise ai', 'trustworthy ai', 'graph ai'],
  },
  {
    id: 'labelbox',
    vendor: 'Labelbox',
    url: 'https://labelbox.com/events/',
    defaultCategories: ['AI', 'Data'],
    tags: ['labelbox', 'data labeling', 'annotation', 'training data'],
  },
  {
    id: 'cvat-intel',
    vendor: 'CVAT (Intel)',
    url: 'https://www.cvat.ai/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['cvat', 'annotation tool', 'computer vision', 'open source'],
  },
  {
    id: 'supervisely',
    vendor: 'Supervisely',
    url: 'https://supervisely.com/events/',
    defaultCategories: ['AI'],
    tags: ['supervisely', 'computer vision', 'data annotation', 'mlops'],
  },
  {
    id: 'clarifai',
    vendor: 'Clarifai',
    url: 'https://www.clarifai.com/events',
    defaultCategories: ['AI'],
    tags: ['clarifai', 'computer vision', 'visual ai', 'image recognition'],
  },
  {
    id: 'viso-suite',
    vendor: 'Viso Suite',
    url: 'https://viso.ai/events/',
    defaultCategories: ['AI'],
    tags: ['viso', 'computer vision platform', 'no-code cv', 'edge ai'],
  },
  {
    id: 'datagen',
    vendor: 'Datagen',
    url: 'https://datagen.tech/events/',
    defaultCategories: ['AI', 'Data'],
    tags: ['datagen', 'synthetic data', 'computer vision', 'training data'],
  },

  // ── Generative AI Tools / Dev Platforms ──────────────────────────────────
  {
    id: 'github-copilot',
    vendor: 'GitHub Copilot',
    url: 'https://github.blog/ai-and-ml/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['github', 'copilot', 'code generation', 'developer ai'],
  },
  {
    id: 'tabnine',
    vendor: 'Tabnine',
    url: 'https://www.tabnine.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['tabnine', 'code completion', 'developer ai', 'ide'],
  },
  {
    id: 'amazon-codewhisperer',
    vendor: 'Amazon CodeWhisperer',
    url: 'https://aws.amazon.com/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['codewhisperer', 'aws', 'code generation', 'developer ai'],
  },
  {
    id: 'replit-ai',
    vendor: 'Replit AI',
    url: 'https://blog.replit.com',
    defaultCategories: ['AI', 'Developer'],
    tags: ['replit', 'coding ai', 'online ide', 'code generation'],
  },
  {
    id: 'cursor-ai',
    vendor: 'Cursor',
    url: 'https://www.cursor.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['cursor', 'ai ide', 'code generation', 'developer tool'],
  },
  {
    id: 'codeium',
    vendor: 'Codeium',
    url: 'https://codeium.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['codeium', 'code completion', 'developer ai', 'ide plugin'],
  },
  {
    id: 'sourcegraph',
    vendor: 'Sourcegraph',
    url: 'https://sourcegraph.com/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['sourcegraph', 'cody', 'code search', 'developer ai'],
  },
  {
    id: 'codacy',
    vendor: 'Codacy',
    url: 'https://www.codacy.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['codacy', 'code quality', 'static analysis', 'developer ai'],
  },
  {
    id: 'deepcode-snyk',
    vendor: 'DeepCode (Snyk)',
    url: 'https://snyk.io/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['snyk', 'deepcode', 'security ai', 'code review'],
  },
  {
    id: 'galileo-ai',
    vendor: 'Galileo',
    url: 'https://www.rungalileo.io/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['galileo', 'llm evaluation', 'data quality', 'fine-tuning'],
  },
  {
    id: 'langsmith',
    vendor: 'LangSmith (LangChain)',
    url: 'https://www.langchain.com/langsmith',
    defaultCategories: ['AI', 'Developer'],
    tags: ['langsmith', 'llm observability', 'debugging', 'tracing'],
  },
  {
    id: 'humanloop',
    vendor: 'Humanloop',
    url: 'https://humanloop.com/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['humanloop', 'prompt management', 'llm ops', 'fine-tuning'],
  },
  {
    id: 'promptlayer',
    vendor: 'PromptLayer',
    url: 'https://promptlayer.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['promptlayer', 'prompt engineering', 'llm monitoring', 'developer tool'],
  },
  {
    id: 'flowise',
    vendor: 'Flowise',
    url: 'https://flowiseai.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['flowise', 'no-code llm', 'drag and drop ai', 'open source'],
  },
  {
    id: 'dify-ai',
    vendor: 'Dify',
    url: 'https://dify.ai/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['dify', 'llm app builder', 'rag', 'open source'],
  },

  // ── AI Research Organizations ─────────────────────────────────────────────
  {
    id: 'allen-ai2',
    vendor: 'Allen Institute for AI (AI2)',
    url: 'https://allenai.org/events',
    defaultCategories: ['AI'],
    tags: ['ai2', 'allen institute', 'nlp research', 'open research'],
  },
  {
    id: 'eleutherai',
    vendor: 'EleutherAI',
    url: 'https://www.eleuther.ai/events',
    defaultCategories: ['AI'],
    tags: ['eleutherai', 'open source llm', 'gpt-neox', 'ai research'],
  },
  {
    id: 'bigscience',
    vendor: 'BigScience / Hugging Face',
    url: 'https://bigscience.huggingface.co/',
    defaultCategories: ['AI'],
    tags: ['bigscience', 'bloom', 'multilingual llm', 'open research'],
  },
  {
    id: 'openmined',
    vendor: 'OpenMined',
    url: 'https://www.openmined.org/events',
    defaultCategories: ['AI'],
    tags: ['openmined', 'privacy ai', 'federated learning', 'differential privacy'],
  },
  {
    id: 'bair',
    vendor: 'Berkeley AI Research (BAIR)',
    url: 'https://bair.berkeley.edu/blog/',
    defaultCategories: ['AI'],
    tags: ['bair', 'berkeley', 'ai research', 'robotics'],
  },
  {
    id: 'stanford-hai',
    vendor: 'Stanford HAI',
    url: 'https://hai.stanford.edu/events',
    defaultCategories: ['AI'],
    tags: ['stanford hai', 'human-centered ai', 'policy', 'ai research'],
  },
  {
    id: 'mit-csail',
    vendor: 'MIT CSAIL',
    url: 'https://www.csail.mit.edu/events',
    defaultCategories: ['AI'],
    tags: ['mit csail', 'ai research', 'robotics', 'computer science'],
  },
  {
    id: 'oxford-fhi',
    vendor: 'Oxford Future of Humanity Institute',
    url: 'https://www.fhi.ox.ac.uk/events/',
    defaultCategories: ['AI'],
    tags: ['oxford fhi', 'ai safety', 'existential risk', 'alignment'],
  },
  {
    id: 'center-ai-safety',
    vendor: 'Center for AI Safety',
    url: 'https://www.safe.ai/events',
    defaultCategories: ['AI'],
    tags: ['cais', 'ai safety', 'alignment', 'risk'],
  },
  {
    id: 'redwood-research',
    vendor: 'Redwood Research',
    url: 'https://www.redwoodresearch.org/blog',
    defaultCategories: ['AI'],
    tags: ['redwood research', 'ai safety', 'alignment', 'interpretability'],
  },
  {
    id: 'conjecture',
    vendor: 'Conjecture',
    url: 'https://www.conjecture.dev/blog',
    defaultCategories: ['AI'],
    tags: ['conjecture', 'ai safety', 'alignment', 'research'],
  },
  {
    id: 'alignment-forum',
    vendor: 'Alignment Forum',
    url: 'https://www.alignmentforum.org/',
    defaultCategories: ['AI'],
    tags: ['alignment forum', 'ai safety', 'alignment research', 'community'],
  },

  // ── AI Research Conferences ────────────────────────────────────────────────
  {
    id: 'neurips',
    vendor: 'NeurIPS',
    url: 'https://nips.cc/',
    defaultCategories: ['AI'],
    tags: ['neurips', 'deep learning', 'ml research'],
  },
  {
    id: 'icml',
    vendor: 'ICML',
    url: 'https://icml.cc/',
    defaultCategories: ['AI'],
    tags: ['icml', 'machine learning research'],
  },
  {
    id: 'iclr',
    vendor: 'ICLR',
    url: 'https://iclr.cc/',
    defaultCategories: ['AI'],
    tags: ['iclr', 'deep learning research'],
  },
  {
    id: 'cvpr',
    vendor: 'CVPR',
    url: 'https://cvpr.thecvf.com/',
    defaultCategories: ['AI'],
    tags: ['cvpr', 'computer vision'],
  },
  {
    id: 'aaai',
    vendor: 'AAAI',
    url: 'https://aaai.org/conference/',
    defaultCategories: ['AI'],
    tags: ['aaai', 'ai research'],
  },
  {
    id: 'acl-nlp',
    vendor: 'ACL (NLP)',
    url: 'https://www.aclweb.org/portal/content/upcoming-acl-events',
    defaultCategories: ['AI'],
    tags: ['acl', 'nlp', 'natural language processing'],
  },
  {
    id: 'eccv',
    vendor: 'ECCV',
    url: 'https://eccv.ecva.net/',
    defaultCategories: ['AI'],
    tags: ['eccv', 'computer vision', 'european cv conference'],
  },
  {
    id: 'iccv',
    vendor: 'ICCV',
    url: 'https://iccv.thecvf.com/',
    defaultCategories: ['AI'],
    tags: ['iccv', 'computer vision', 'ml research'],
  },
  {
    id: 'emnlp',
    vendor: 'EMNLP',
    url: 'https://2024.emnlp.org/',
    defaultCategories: ['AI'],
    tags: ['emnlp', 'nlp', 'empirical methods'],
  },
  {
    id: 'naacl',
    vendor: 'NAACL',
    url: 'https://naacl.org/',
    defaultCategories: ['AI'],
    tags: ['naacl', 'nlp', 'north america'],
  },
  {
    id: 'interspeech',
    vendor: 'INTERSPEECH',
    url: 'https://interspeech2024.org/',
    defaultCategories: ['AI'],
    tags: ['interspeech', 'speech ai', 'audio ml', 'voice'],
  },
  {
    id: 'kdd',
    vendor: 'KDD',
    url: 'https://kdd.org/',
    defaultCategories: ['AI', 'Data'],
    tags: ['kdd', 'knowledge discovery', 'data mining', 'ml research'],
  },
  {
    id: 'ijcai',
    vendor: 'IJCAI',
    url: 'https://www.ijcai.org/',
    defaultCategories: ['AI'],
    tags: ['ijcai', 'ai research', 'international conference'],
  },
  {
    id: 'sigkdd',
    vendor: 'SIGKDD',
    url: 'https://www.kdd.org/conferences',
    defaultCategories: ['AI', 'Data'],
    tags: ['sigkdd', 'acm', 'data science', 'knowledge discovery'],
  },
  {
    id: 'world-summit-ai',
    vendor: 'World Summit AI',
    url: 'https://worldsummit.ai/',
    defaultCategories: ['AI'],
    tags: ['world summit ai', 'enterprise ai', 'amsterdam', 'global ai'],
  },
  {
    id: 'ai-summit-london',
    vendor: 'AI Summit London',
    url: 'https://theaisummit.com/london/',
    defaultCategories: ['AI'],
    tags: ['ai summit london', 'enterprise ai', 'uk ai', 'business ai'],
  },
  {
    id: 'ai-big-data-expo',
    vendor: 'AI & Big Data Expo',
    url: 'https://www.ai-expo.net/',
    defaultCategories: ['AI', 'Data'],
    tags: ['ai expo', 'big data', 'enterprise ai', 'global'],
  },
  {
    id: 'rework-ai-summit',
    vendor: 'RE·WORK AI Summit',
    url: 'https://www.re-work.co/events',
    defaultCategories: ['AI'],
    tags: ['rework', 'deep learning summit', 'applied ai', 'ml'],
  },
  {
    id: 'ai4',
    vendor: 'Ai4',
    url: 'https://ai4.io/',
    defaultCategories: ['AI'],
    tags: ['ai4', 'enterprise ai', 'las vegas', 'applied ai'],
  },
  {
    id: 'cogx',
    vendor: 'CogX',
    url: 'https://cogxfestival.com/',
    defaultCategories: ['AI'],
    tags: ['cogx', 'responsible tech', 'ai festival', 'london'],
  },
  {
    id: 'the-ai-conference',
    vendor: 'The AI Conference',
    url: 'https://aiconference.com/',
    defaultCategories: ['AI'],
    tags: ['ai conference', 'san francisco', 'enterprise ai', 'applied ml'],
  },
  {
    id: 'mlops-world',
    vendor: 'MLOps World',
    url: 'https://mlopsworld.com/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['mlops world', 'machine learning ops', 'production ml', 'conference'],
  },
  {
    id: 'applied-ml-days',
    vendor: 'Applied ML Days (EPFL)',
    url: 'https://appliedmldays.org/',
    defaultCategories: ['AI'],
    tags: ['amld', 'epfl', 'applied machine learning', 'europe'],
  },
  {
    id: 'ai4-government',
    vendor: 'AI4 (Government)',
    url: 'https://ai4.io/government/',
    defaultCategories: ['AI'],
    tags: ['ai4 government', 'public sector ai', 'federal ai', 'washington dc'],
  },
  {
    id: 'strata-data-ai',
    vendor: 'Strata Data & AI (O\'Reilly)',
    url: 'https://www.oreilly.com/radar/topics/oreilly-ai-superstream/',
    defaultCategories: ['AI', 'Data'],
    tags: ['strata', 'oreilly', 'data ai', 'machine learning conference'],
  },
  {
    id: 'ai-engineer-world',
    vendor: 'AI Engineer World\'s Fair',
    url: 'https://www.ai.engineer/worldsfair',
    defaultCategories: ['AI', 'Developer'],
    tags: ['ai engineer', 'llm engineering', 'developer ai', 'san francisco'],
  },
  {
    id: 'data-ai-summit',
    vendor: 'Data + AI Summit',
    url: 'https://www.databricks.com/dataaisummit/',
    defaultCategories: ['AI', 'Data'],
    tags: ['data ai summit', 'databricks', 'spark', 'llmops'],
  },
  {
    id: 'oreilly-ai-conf',
    vendor: 'O\'Reilly AI Conference',
    url: 'https://www.oreilly.com/conferences/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['oreilly', 'applied ai', 'developer conference', 'training'],
  },

  // ── Additional Foundation Model / LLM Providers ───────────────────────────
  {
    id: 'mosaicml',
    vendor: 'MosaicML (Databricks)',
    url: 'https://www.databricks.com/blog/category/engineering/mosaic',
    defaultCategories: ['AI', 'Developer'],
    tags: ['mosaicml', 'llm training', 'composer', 'open llm'],
  },
  {
    id: 'deepseek',
    vendor: 'DeepSeek',
    url: 'https://www.deepseek.com/',
    defaultCategories: ['AI'],
    tags: ['deepseek', 'open source llm', 'reasoning model', 'chinese ai'],
  },
  {
    id: '01-ai',
    vendor: '01.AI (Yi)',
    url: 'https://www.01.ai/',
    defaultCategories: ['AI'],
    tags: ['01.ai', 'yi model', 'open llm', 'multilingual'],
  },
  {
    id: 'moonshot-ai',
    vendor: 'Moonshot AI (Kimi)',
    url: 'https://www.moonshot.cn/',
    defaultCategories: ['AI'],
    tags: ['moonshot', 'kimi', 'long context llm', 'chinese ai'],
  },

  // ── Additional MLOps / Infrastructure ────────────────────────────────────
  {
    id: 'modal-labs',
    vendor: 'Modal Labs',
    url: 'https://modal.com/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['modal', 'cloud functions', 'gpu inference', 'python'],
  },
  {
    id: 'dstack',
    vendor: 'dstack',
    url: 'https://dstack.ai/blog/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['dstack', 'ml infrastructure', 'gpu cloud', 'open source'],
  },
  {
    id: 'runpod',
    vendor: 'RunPod',
    url: 'https://www.runpod.io/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['runpod', 'gpu cloud', 'serverless ai', 'inference'],
  },
  {
    id: 'vast-ai',
    vendor: 'Vast.ai',
    url: 'https://vast.ai/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['vast.ai', 'gpu rental', 'compute marketplace', 'training'],
  },

  // ── Additional Vector DB / RAG Tools ─────────────────────────────────────
  {
    id: 'pgvector',
    vendor: 'pgvector / Supabase AI',
    url: 'https://supabase.com/events',
    defaultCategories: ['AI', 'Developer'],
    tags: ['pgvector', 'supabase', 'postgres', 'vector search'],
  },
  {
    id: 'turbopuffer',
    vendor: 'Turbopuffer',
    url: 'https://turbopuffer.com/blog',
    defaultCategories: ['AI', 'Data'],
    tags: ['turbopuffer', 'vector database', 'scalable search', 'embeddings'],
  },
  {
    id: 'vectara',
    vendor: 'Vectara',
    url: 'https://vectara.com/events/',
    defaultCategories: ['AI', 'Developer'],
    tags: ['vectara', 'grounded generation', 'rag platform', 'enterprise search'],
  },

  // ── Additional AI Tools / Agents ──────────────────────────────────────────
  {
    id: 'cognition-ai',
    vendor: 'Cognition AI (Devin)',
    url: 'https://www.cognition.ai/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['cognition', 'devin', 'ai software engineer', 'coding agent'],
  },
  {
    id: 'adept-ai',
    vendor: 'Adept AI',
    url: 'https://www.adept.ai/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['adept', 'action transformer', 'ai agents', 'workflow automation'],
  },
  {
    id: 'coframe',
    vendor: 'Coframe',
    url: 'https://coframe.ai/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['coframe', 'ui optimization', 'generative ai', 'a/b testing'],
  },
  {
    id: 'fixie-ai',
    vendor: 'Fixie AI',
    url: 'https://www.fixie.ai/blog',
    defaultCategories: ['AI', 'Developer'],
    tags: ['fixie', 'llm agents', 'voice ai', 'conversational'],
  },

  // ── Additional AI Safety / Policy ────────────────────────────────────────
  {
    id: 'ai-safety-institute',
    vendor: 'AI Safety Institute (AISI)',
    url: 'https://www.gov.uk/government/organisations/ai-safety-institute',
    defaultCategories: ['AI'],
    tags: ['aisi', 'ai safety', 'uk government', 'policy'],
  },
  {
    id: 'future-of-life',
    vendor: 'Future of Life Institute',
    url: 'https://futureoflife.org/events/',
    defaultCategories: ['AI'],
    tags: ['fli', 'existential risk', 'ai safety', 'policy'],
  },
  {
    id: 'mozilla-ai',
    vendor: 'Mozilla AI',
    url: 'https://mozilla.ai/blog/',
    defaultCategories: ['AI'],
    tags: ['mozilla', 'trustworthy ai', 'open source ai', 'responsible ai'],
  },
  {
    id: 'levity-ai',
    vendor: 'Levity AI',
    url: 'https://levity.ai/blog',
    defaultCategories: ['AI'],
    tags: ['levity', 'no-code ai', 'document automation', 'workflow ai'],
  },

];
