module.exports = [

  // ── Cloud / Infrastructure ────────────────────────────────────────────────
  {
    id: 'ibm',
    vendor: 'IBM',
    url: 'https://www.ibm.com/events',
    defaultCategories: ['Cloud', 'AI'],
    tags: ['ibm', 'think', 'cloud'],
  },
  {
    id: 'oracle',
    vendor: 'Oracle',
    url: 'https://www.oracle.com/events/',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['oracle', 'cloudworld'],
  },
  {
    id: 'vmware',
    vendor: 'VMware / Broadcom',
    url: 'https://www.vmware.com/explore.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['vmware', 'broadcom', 'virtualization'],
  },
  {
    id: 'redhat',
    vendor: 'Red Hat',
    url: 'https://www.redhat.com/en/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['red hat', 'openshift', 'linux', 'ansible'],
  },
  {
    id: 'hpe',
    vendor: 'HPE',
    url: 'https://www.hpe.com/us/en/living-progress/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['hpe', 'hewlett packard', 'discover'],
  },
  {
    id: 'dell',
    vendor: 'Dell Technologies',
    url: 'https://www.dell.com/en-us/dt/events/index.htm',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['dell', 'dell tech world'],
  },
  {
    id: 'nutanix',
    vendor: 'Nutanix',
    url: 'https://www.nutanix.com/next',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['nutanix', 'hyperconverged', '.next'],
  },
  {
    id: 'cloudflare',
    vendor: 'Cloudflare',
    url: 'https://www.cloudflare.com/events/',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['cloudflare', 'cdn', 'zero trust'],
  },
  {
    id: 'akamai',
    vendor: 'Akamai',
    url: 'https://www.akamai.com/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['akamai', 'cdn', 'edge'],
  },
  {
    id: 'digitalocean',
    vendor: 'DigitalOcean',
    url: 'https://www.digitalocean.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['digitalocean', 'cloud'],
  },
  {
    id: 'linode-akamai',
    vendor: 'Linode / Akamai Cloud',
    url: 'https://www.linode.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['linode', 'akamai cloud'],
  },
  {
    id: 'netapp',
    vendor: 'NetApp',
    url: 'https://www.netapp.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['netapp', 'storage', 'insight'],
  },
  {
    id: 'pure-storage',
    vendor: 'Pure Storage',
    url: 'https://www.purestorage.com/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['pure storage', 'flash storage', 'accelerate'],
  },
  {
    id: 'veeam',
    vendor: 'Veeam',
    url: 'https://www.veeam.com/veeamon',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['veeam', 'backup', 'veeamon'],
  },

  // ── Enterprise SaaS ───────────────────────────────────────────────────────
  {
    id: 'salesforce',
    vendor: 'Salesforce',
    url: 'https://www.salesforce.com/events/',
    defaultCategories: ['Cloud', 'AI'],
    tags: ['salesforce', 'dreamforce', 'tdx', 'crm'],
  },
  {
    id: 'servicenow',
    vendor: 'ServiceNow',
    url: 'https://www.servicenow.com/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['servicenow', 'knowledge', 'itsm'],
  },
  {
    id: 'sap',
    vendor: 'SAP',
    url: 'https://www.sap.com/about/events.html',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['sap', 'sapphire', 'erp'],
  },
  {
    id: 'workday',
    vendor: 'Workday',
    url: 'https://www.workday.com/en-us/company/workday-events.html',
    defaultCategories: ['Cloud'],
    tags: ['workday', 'rising', 'hr tech'],
  },
  {
    id: 'twilio',
    vendor: 'Twilio',
    url: 'https://signal.twilio.com/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['twilio', 'signal', 'communications api'],
  },
  {
    id: 'stripe',
    vendor: 'Stripe',
    url: 'https://stripe.com/events',
    defaultCategories: ['Developer'],
    tags: ['stripe', 'payments', 'sessions'],
  },
  {
    id: 'hubspot',
    vendor: 'HubSpot',
    url: 'https://www.inbound.com/',
    defaultCategories: ['Cloud'],
    tags: ['hubspot', 'inbound', 'crm', 'marketing'],
  },
  {
    id: 'zendesk',
    vendor: 'Zendesk',
    url: 'https://www.zendesk.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['zendesk', 'relate', 'customer service'],
  },

  // ── Networking ────────────────────────────────────────────────────────────
  {
    id: 'cisco',
    vendor: 'Cisco',
    url: 'https://www.ciscolive.com/',
    defaultCategories: ['Cloud', 'IT / Ops', 'Cybersecurity'],
    tags: ['cisco', 'cisco live', 'networking'],
  },
  {
    id: 'juniper',
    vendor: 'Juniper Networks',
    url: 'https://www.juniper.net/us/en/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['juniper', 'nxtwork', 'networking'],
  },
  {
    id: 'f5',
    vendor: 'F5',
    url: 'https://www.f5.com/company/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['f5', 'appworld', 'load balancing'],
  },
  {
    id: 'arista',
    vendor: 'Arista Networks',
    url: 'https://www.arista.com/en/company/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['arista', 'eos', 'networking'],
  },
];
