module.exports = [

  // ── Cloud / Infrastructure ────────────────────────────────────────────────
  {
    id: 'ibm',
    vendor: 'IBM',
    url: 'https://www.ibm.com/events',
    defaultCategories: ['Cloud', 'AI'],
    tags: ['ibm', 'think', 'cloud'],
  },
  {
    id: 'oracle',
    vendor: 'Oracle',
    url: 'https://www.oracle.com/events/',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['oracle', 'cloudworld'],
  },
  {
    id: 'vmware',
    vendor: 'VMware / Broadcom',
    url: 'https://www.vmware.com/explore.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['vmware', 'broadcom', 'virtualization'],
  },
  {
    id: 'redhat',
    vendor: 'Red Hat',
    url: 'https://www.redhat.com/en/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['red hat', 'openshift', 'linux', 'ansible'],
  },
  {
    id: 'hpe',
    vendor: 'HPE',
    url: 'https://www.hpe.com/us/en/living-progress/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['hpe', 'hewlett packard', 'discover'],
  },
  {
    id: 'dell',
    vendor: 'Dell Technologies',
    url: 'https://www.dell.com/en-us/dt/events/index.htm',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['dell', 'dell tech world'],
  },
  {
    id: 'nutanix',
    vendor: 'Nutanix',
    url: 'https://www.nutanix.com/next',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['nutanix', 'hyperconverged', '.next'],
  },
  {
    id: 'cloudflare',
    vendor: 'Cloudflare',
    url: 'https://www.cloudflare.com/events/',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['cloudflare', 'cdn', 'zero trust'],
  },
  {
    id: 'akamai',
    vendor: 'Akamai',
    url: 'https://www.akamai.com/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['akamai', 'cdn', 'edge'],
  },
  {
    id: 'digitalocean',
    vendor: 'DigitalOcean',
    url: 'https://www.digitalocean.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['digitalocean', 'cloud'],
  },
  {
    id: 'linode-akamai',
    vendor: 'Linode / Akamai Cloud',
    url: 'https://www.linode.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['linode', 'akamai cloud'],
  },
  {
    id: 'netapp',
    vendor: 'NetApp',
    url: 'https://www.netapp.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['netapp', 'storage', 'insight'],
  },
  {
    id: 'pure-storage',
    vendor: 'Pure Storage',
    url: 'https://www.purestorage.com/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['pure storage', 'flash storage', 'accelerate'],
  },
  {
    id: 'veeam',
    vendor: 'Veeam',
    url: 'https://www.veeam.com/veeamon',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['veeam', 'backup', 'veeamon'],
  },

  // ── Hyperscale Cloud Providers ────────────────────────────────────────────
  {
    id: 'aws',
    vendor: 'Amazon Web Services',
    url: 'https://aws.amazon.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['aws', 'amazon', 'reinvent', 'cloud'],
  },
  {
    id: 'azure',
    vendor: 'Microsoft Azure',
    url: 'https://azure.microsoft.com/en-us/community/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['azure', 'microsoft', 'cloud'],
  },
  {
    id: 'google-cloud',
    vendor: 'Google Cloud',
    url: 'https://cloud.google.com/events',
    defaultCategories: ['Cloud', 'AI', 'Developer'],
    tags: ['google cloud', 'gcp', 'next', 'cloud'],
  },
  {
    id: 'alibaba-cloud',
    vendor: 'Alibaba Cloud',
    url: 'https://www.alibabacloud.com/events',
    defaultCategories: ['Cloud'],
    tags: ['alibaba', 'aliyun', 'cloud'],
  },
  {
    id: 'tencent-cloud',
    vendor: 'Tencent Cloud',
    url: 'https://intl.cloud.tencent.com/events',
    defaultCategories: ['Cloud'],
    tags: ['tencent', 'cloud', 'asia'],
  },
  {
    id: 'huawei-cloud',
    vendor: 'Huawei Cloud',
    url: 'https://www.huaweicloud.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['huawei', 'cloud', 'hdc'],
  },
  {
    id: 'ovhcloud',
    vendor: 'OVHcloud',
    url: 'https://www.ovhcloud.com/en/events/',
    defaultCategories: ['Cloud'],
    tags: ['ovhcloud', 'cloud', 'europe'],
  },
  {
    id: 'hetzner',
    vendor: 'Hetzner',
    url: 'https://www.hetzner.com/events',
    defaultCategories: ['Cloud'],
    tags: ['hetzner', 'cloud', 'hosting'],
  },

  // ── Cloud Management / FinOps ─────────────────────────────────────────────
  {
    id: 'hashicorp',
    vendor: 'HashiCorp',
    url: 'https://www.hashicorp.com/events',
    defaultCategories: ['Cloud', 'Developer', 'IT / Ops'],
    tags: ['hashicorp', 'terraform', 'vault', 'infrastructure as code'],
  },
  {
    id: 'pulumi',
    vendor: 'Pulumi',
    url: 'https://www.pulumi.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['pulumi', 'infrastructure as code', 'iac'],
  },
  {
    id: 'spacelift',
    vendor: 'Spacelift',
    url: 'https://spacelift.io/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['spacelift', 'iac', 'terraform'],
  },
  {
    id: 'env0',
    vendor: 'Env0',
    url: 'https://www.env0.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['env0', 'iac', 'finops'],
  },
  {
    id: 'scalr',
    vendor: 'Scalr',
    url: 'https://www.scalr.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['scalr', 'terraform', 'governance'],
  },
  {
    id: 'cloudhealth',
    vendor: 'CloudHealth by VMware',
    url: 'https://cloudhealth.vmware.com/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['cloudhealth', 'finops', 'cloud cost'],
  },
  {
    id: 'apptio',
    vendor: 'Apptio (IBM)',
    url: 'https://www.apptio.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['apptio', 'finops', 'tbm', 'cloud cost'],
  },
  {
    id: 'cloudcheckr',
    vendor: 'CloudCheckr',
    url: 'https://cloudcheckr.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['cloudcheckr', 'finops', 'cloud cost management'],
  },
  {
    id: 'cloudability',
    vendor: 'Cloudability (Apptio)',
    url: 'https://www.cloudability.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['cloudability', 'finops', 'cloud spend'],
  },
  {
    id: 'spot-netapp',
    vendor: 'Spot by NetApp',
    url: 'https://spot.io/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['spot', 'netapp', 'cloud optimization', 'finops'],
  },
  {
    id: 'parkmycloud',
    vendor: 'ParkMyCloud',
    url: 'https://www.parkmycloud.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['parkmycloud', 'finops', 'cloud cost'],
  },
  {
    id: 'nops',
    vendor: 'Nops',
    url: 'https://www.nops.io/events/',
    defaultCategories: ['Cloud'],
    tags: ['nops', 'finops', 'aws cost', 'cloud savings'],
  },
  {
    id: 'densify',
    vendor: 'Densify',
    url: 'https://www.densify.com/events',
    defaultCategories: ['Cloud'],
    tags: ['densify', 'cloud optimization', 'finops'],
  },
  {
    id: 'harness',
    vendor: 'Harness',
    url: 'https://www.harness.io/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['harness', 'ci/cd', 'devops', 'finops'],
  },
  {
    id: 'flexera',
    vendor: 'Flexera',
    url: 'https://www.flexera.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['flexera', 'itam', 'finops', 'cloud cost'],
  },

  // ── Serverless / PaaS / App Platforms ────────────────────────────────────
  {
    id: 'heroku',
    vendor: 'Heroku',
    url: 'https://www.heroku.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['heroku', 'paas', 'salesforce', 'platform'],
  },
  {
    id: 'flyio',
    vendor: 'Fly.io',
    url: 'https://fly.io/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['fly.io', 'paas', 'edge', 'containers'],
  },
  {
    id: 'railway',
    vendor: 'Railway',
    url: 'https://railway.app/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['railway', 'paas', 'deployment'],
  },
  {
    id: 'render',
    vendor: 'Render',
    url: 'https://render.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['render', 'paas', 'cloud hosting'],
  },
  {
    id: 'vercel',
    vendor: 'Vercel',
    url: 'https://vercel.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['vercel', 'serverless', 'next.js', 'edge'],
  },
  {
    id: 'netlify',
    vendor: 'Netlify',
    url: 'https://www.netlify.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['netlify', 'jamstack', 'edge', 'serverless'],
  },
  {
    id: 'platform-sh',
    vendor: 'Platform.sh',
    url: 'https://platform.sh/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['platform.sh', 'paas', 'web hosting'],
  },
  {
    id: 'kinsta',
    vendor: 'Kinsta',
    url: 'https://kinsta.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['kinsta', 'wordpress', 'managed hosting'],
  },
  {
    id: 'wp-engine',
    vendor: 'WP Engine',
    url: 'https://wpengine.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['wp engine', 'wordpress', 'managed hosting'],
  },
  {
    id: 'pantheon',
    vendor: 'Pantheon',
    url: 'https://pantheon.io/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['pantheon', 'drupal', 'wordpress', 'webops'],
  },
  {
    id: 'cloudways',
    vendor: 'Cloudways',
    url: 'https://www.cloudways.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['cloudways', 'managed cloud', 'hosting'],
  },
  {
    id: 'supabase',
    vendor: 'Supabase',
    url: 'https://supabase.com/events',
    defaultCategories: ['Cloud', 'Developer', 'Data'],
    tags: ['supabase', 'postgres', 'backend as a service', 'open source'],
  },
  {
    id: 'neon',
    vendor: 'Neon',
    url: 'https://neon.tech/events',
    defaultCategories: ['Cloud', 'Developer', 'Data'],
    tags: ['neon', 'serverless postgres', 'database'],
  },
  {
    id: 'planetscale',
    vendor: 'PlanetScale',
    url: 'https://planetscale.com/events',
    defaultCategories: ['Cloud', 'Developer', 'Data'],
    tags: ['planetscale', 'mysql', 'serverless database'],
  },

  // ── CDN / Edge / DNS ──────────────────────────────────────────────────────
  {
    id: 'fastly',
    vendor: 'Fastly',
    url: 'https://www.fastly.com/events',
    defaultCategories: ['Cloud'],
    tags: ['fastly', 'cdn', 'edge cloud'],
  },
  {
    id: 'edgio',
    vendor: 'Edgio (Limelight)',
    url: 'https://edg.io/events/',
    defaultCategories: ['Cloud'],
    tags: ['edgio', 'limelight', 'cdn', 'edge'],
  },
  {
    id: 'keycdn',
    vendor: 'KeyCDN',
    url: 'https://www.keycdn.com/events',
    defaultCategories: ['Cloud'],
    tags: ['keycdn', 'cdn', 'performance'],
  },
  {
    id: 'bunnycdn',
    vendor: 'BunnyCDN',
    url: 'https://bunny.net/events',
    defaultCategories: ['Cloud'],
    tags: ['bunnycdn', 'cdn', 'edge storage'],
  },
  {
    id: 'gcore',
    vendor: 'Gcore',
    url: 'https://gcore.com/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['gcore', 'cdn', 'edge cloud', 'ddos'],
  },
  {
    id: 'ns1',
    vendor: 'NS1 (IBM)',
    url: 'https://ns1.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['ns1', 'dns', 'traffic management'],
  },
  {
    id: 'dnsimple',
    vendor: 'DNSimple',
    url: 'https://dnsimple.com/events',
    defaultCategories: ['Cloud'],
    tags: ['dnsimple', 'dns', 'domain management'],
  },
  {
    id: 'cloudns',
    vendor: 'ClouDNS',
    url: 'https://www.cloudns.net/events/',
    defaultCategories: ['Cloud'],
    tags: ['cloudns', 'dns', 'managed dns'],
  },
  {
    id: 'imperva-cdn',
    vendor: 'Imperva CDN',
    url: 'https://www.imperva.com/company/events/',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['imperva', 'cdn', 'waf', 'ddos'],
  },
  {
    id: 'stackpath',
    vendor: 'StackPath',
    url: 'https://www.stackpath.com/events/',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['stackpath', 'cdn', 'edge', 'security'],
  },

  // ── Storage & Backup / DR ─────────────────────────────────────────────────
  {
    id: 'commvault',
    vendor: 'Commvault',
    url: 'https://www.commvault.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['commvault', 'backup', 'data protection', 'recovery'],
  },
  {
    id: 'rubrik',
    vendor: 'Rubrik',
    url: 'https://www.rubrik.com/events',
    defaultCategories: ['Cloud', 'IT / Ops', 'Cybersecurity'],
    tags: ['rubrik', 'backup', 'cloud data management', 'cyber recovery'],
  },
  {
    id: 'cohesity',
    vendor: 'Cohesity',
    url: 'https://www.cohesity.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['cohesity', 'data management', 'backup'],
  },
  {
    id: 'zerto',
    vendor: 'Zerto (HPE)',
    url: 'https://www.zerto.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['zerto', 'disaster recovery', 'replication'],
  },
  {
    id: 'arcserve',
    vendor: 'Arcserve',
    url: 'https://www.arcserve.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['arcserve', 'backup', 'ransomware recovery'],
  },
  {
    id: 'druva',
    vendor: 'Druva',
    url: 'https://www.druva.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['druva', 'saas backup', 'cloud data protection'],
  },
  {
    id: 'hycu',
    vendor: 'HYCU',
    url: 'https://www.hycu.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['hycu', 'backup', 'multicloud'],
  },
  {
    id: 'catalogic',
    vendor: 'Catalogic Software',
    url: 'https://www.catalogicsoftware.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['catalogic', 'backup', 'data protection'],
  },
  {
    id: 'bacula-systems',
    vendor: 'Bacula Systems',
    url: 'https://www.baculasystems.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['bacula', 'backup', 'open source'],
  },
  {
    id: 'veritas',
    vendor: 'Veritas',
    url: 'https://www.veritas.com/en/us/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['veritas', 'backup', 'data management', 'netbackup'],
  },
  {
    id: 'actifio',
    vendor: 'Actifio (Google)',
    url: 'https://www.actifio.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['actifio', 'google', 'backup', 'copy data management'],
  },
  {
    id: 'msp360',
    vendor: 'MSP360',
    url: 'https://www.msp360.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['msp360', 'backup', 'msp', 'cloud backup'],
  },

  // ── Enterprise SaaS ───────────────────────────────────────────────────────
  {
    id: 'salesforce',
    vendor: 'Salesforce',
    url: 'https://www.salesforce.com/events/',
    defaultCategories: ['Cloud', 'AI'],
    tags: ['salesforce', 'dreamforce', 'tdx', 'crm'],
  },
  {
    id: 'servicenow',
    vendor: 'ServiceNow',
    url: 'https://www.servicenow.com/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['servicenow', 'knowledge', 'itsm'],
  },
  {
    id: 'sap',
    vendor: 'SAP',
    url: 'https://www.sap.com/about/events.html',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['sap', 'sapphire', 'erp'],
  },
  {
    id: 'workday',
    vendor: 'Workday',
    url: 'https://www.workday.com/en-us/company/workday-events.html',
    defaultCategories: ['Cloud'],
    tags: ['workday', 'rising', 'hr tech'],
  },
  {
    id: 'twilio',
    vendor: 'Twilio',
    url: 'https://signal.twilio.com/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['twilio', 'signal', 'communications api'],
  },
  {
    id: 'stripe',
    vendor: 'Stripe',
    url: 'https://stripe.com/events',
    defaultCategories: ['Developer'],
    tags: ['stripe', 'payments', 'sessions'],
  },
  {
    id: 'hubspot',
    vendor: 'HubSpot',
    url: 'https://www.inbound.com/',
    defaultCategories: ['Cloud'],
    tags: ['hubspot', 'inbound', 'crm', 'marketing'],
  },
  {
    id: 'zendesk',
    vendor: 'Zendesk',
    url: 'https://www.zendesk.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['zendesk', 'relate', 'customer service'],
  },

  // ── Enterprise SaaS — CRM / Marketing ────────────────────────────────────
  {
    id: 'microsoft-dynamics',
    vendor: 'Microsoft Dynamics',
    url: 'https://dynamics.microsoft.com/en-us/events/',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['microsoft', 'dynamics', 'crm', 'erp'],
  },
  {
    id: 'oracle-cx',
    vendor: 'Oracle CX',
    url: 'https://www.oracle.com/cx/events/',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['oracle', 'cx', 'customer experience', 'crm'],
  },
  {
    id: 'adobe-experience-cloud',
    vendor: 'Adobe Experience Cloud',
    url: 'https://business.adobe.com/events/',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['adobe', 'experience cloud', 'summit', 'marketing'],
  },
  {
    id: 'marketo',
    vendor: 'Marketo (Adobe)',
    url: 'https://business.adobe.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['marketo', 'adobe', 'marketing automation'],
  },
  {
    id: 'zoho',
    vendor: 'Zoho CRM',
    url: 'https://www.zoho.com/events.html',
    defaultCategories: ['Cloud'],
    tags: ['zoho', 'crm', 'saas'],
  },
  {
    id: 'freshworks',
    vendor: 'Freshworks',
    url: 'https://www.freshworks.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['freshworks', 'crm', 'itsm', 'customer service'],
  },
  {
    id: 'sugarcrm',
    vendor: 'SugarCRM',
    url: 'https://www.sugarcrm.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['sugarcrm', 'crm', 'sales automation'],
  },
  {
    id: 'creatio',
    vendor: 'Creatio',
    url: 'https://www.creatio.com/events',
    defaultCategories: ['Cloud'],
    tags: ['creatio', 'crm', 'low-code', 'bpm'],
  },
  {
    id: 'veeva',
    vendor: 'Veeva Systems',
    url: 'https://www.veeva.com/events/',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['veeva', 'life sciences', 'crm', 'vault'],
  },
  {
    id: 'braze',
    vendor: 'Braze',
    url: 'https://www.braze.com/events',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['braze', 'customer engagement', 'marketing', 'bonfire'],
  },

  // ── Enterprise SaaS — ITSM / Support ─────────────────────────────────────
  {
    id: 'bmc-software',
    vendor: 'BMC Software',
    url: 'https://www.bmc.com/forms/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['bmc', 'itsm', 'helix', 'aiops'],
  },
  {
    id: 'ivanti',
    vendor: 'Ivanti',
    url: 'https://www.ivanti.com/company/events',
    defaultCategories: ['Cloud', 'IT / Ops', 'Cybersecurity'],
    tags: ['ivanti', 'itsm', 'endpoint management', 'zero trust'],
  },
  {
    id: 'topdesk',
    vendor: 'TOPdesk',
    url: 'https://www.topdesk.com/en/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['topdesk', 'itsm', 'service desk'],
  },
  {
    id: 'freshservice',
    vendor: 'Freshservice',
    url: 'https://www.freshworks.com/freshservice/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['freshservice', 'itsm', 'service desk'],
  },
  {
    id: 'atlassian',
    vendor: 'Atlassian',
    url: 'https://www.atlassian.com/company/events',
    defaultCategories: ['Cloud', 'Developer', 'IT / Ops'],
    tags: ['atlassian', 'jira', 'confluence', 'team anywhere'],
  },
  {
    id: 'solarwinds-itsm',
    vendor: 'SolarWinds ITSM',
    url: 'https://www.solarwinds.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['solarwinds', 'itsm', 'monitoring', 'service desk'],
  },
  {
    id: 'manageengine',
    vendor: 'ManageEngine',
    url: 'https://www.manageengine.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['manageengine', 'itsm', 'it management', 'zoho'],
  },
  {
    id: 'hornbill',
    vendor: 'Hornbill',
    url: 'https://www.hornbill.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['hornbill', 'itsm', 'service management'],
  },

  // ── Enterprise SaaS — HR / HCM ────────────────────────────────────────────
  {
    id: 'oracle-hcm',
    vendor: 'Oracle HCM',
    url: 'https://www.oracle.com/human-capital-management/events/',
    defaultCategories: ['Cloud'],
    tags: ['oracle', 'hcm', 'hr tech'],
  },
  {
    id: 'adp',
    vendor: 'ADP',
    url: 'https://www.adp.com/events.aspx',
    defaultCategories: ['Cloud'],
    tags: ['adp', 'payroll', 'hr tech', 'workforce'],
  },
  {
    id: 'ceridian',
    vendor: 'Ceridian Dayforce',
    url: 'https://www.ceridian.com/insights-events',
    defaultCategories: ['Cloud'],
    tags: ['ceridian', 'dayforce', 'hcm', 'payroll'],
  },
  {
    id: 'ukg',
    vendor: 'UKG',
    url: 'https://www.ukg.com/ukg-connections',
    defaultCategories: ['Cloud'],
    tags: ['ukg', 'kronos', 'hr tech', 'workforce management'],
  },
  {
    id: 'cornerstone',
    vendor: 'Cornerstone OnDemand',
    url: 'https://www.cornerstoneondemand.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['cornerstone', 'lms', 'talent management', 'hr tech'],
  },
  {
    id: 'paycom',
    vendor: 'Paycom',
    url: 'https://www.paycom.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['paycom', 'payroll', 'hr tech'],
  },

  // ── Enterprise SaaS — Finance / ERP ──────────────────────────────────────
  {
    id: 'sage',
    vendor: 'Sage Group',
    url: 'https://www.sage.com/en-us/events/',
    defaultCategories: ['Cloud'],
    tags: ['sage', 'erp', 'accounting', 'finance'],
  },
  {
    id: 'unit4',
    vendor: 'Unit4',
    url: 'https://www.unit4.com/about/events',
    defaultCategories: ['Cloud'],
    tags: ['unit4', 'erp', 'finance', 'hcm'],
  },
  {
    id: 'epicor',
    vendor: 'Epicor',
    url: 'https://www.epicor.com/en-us/events/',
    defaultCategories: ['Cloud'],
    tags: ['epicor', 'erp', 'manufacturing', 'distribution'],
  },
  {
    id: 'infor',
    vendor: 'Infor',
    url: 'https://www.infor.com/events',
    defaultCategories: ['Cloud', 'Data'],
    tags: ['infor', 'erp', 'cloud', 'industry'],
  },
  {
    id: 'acumatica',
    vendor: 'Acumatica',
    url: 'https://www.acumatica.com/acumatica-summit/',
    defaultCategories: ['Cloud'],
    tags: ['acumatica', 'erp', 'cloud erp', 'small business'],
  },

  // ── Enterprise SaaS — Collaboration ──────────────────────────────────────
  {
    id: 'microsoft-365',
    vendor: 'Microsoft 365',
    url: 'https://www.microsoft.com/en-us/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['microsoft', 'teams', 'microsoft 365', 'collaboration'],
  },
  {
    id: 'zoom',
    vendor: 'Zoom',
    url: 'https://events.zoom.us/',
    defaultCategories: ['Cloud'],
    tags: ['zoom', 'video conferencing', 'zoomtopia'],
  },
  {
    id: 'box',
    vendor: 'Box',
    url: 'https://www.box.com/events',
    defaultCategories: ['Cloud'],
    tags: ['box', 'content cloud', 'collaboration'],
  },
  {
    id: 'dropbox',
    vendor: 'Dropbox',
    url: 'https://www.dropbox.com/events',
    defaultCategories: ['Cloud'],
    tags: ['dropbox', 'file sync', 'collaboration'],
  },
  {
    id: 'notion',
    vendor: 'Notion',
    url: 'https://www.notion.so/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['notion', 'productivity', 'collaboration', 'wiki'],
  },
  {
    id: 'miro',
    vendor: 'Miro',
    url: 'https://miro.com/events/',
    defaultCategories: ['Cloud'],
    tags: ['miro', 'whiteboard', 'collaboration', 'visual'],
  },
  {
    id: 'egnyte',
    vendor: 'Egnyte',
    url: 'https://www.egnyte.com/events/',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['egnyte', 'content management', 'governance'],
  },
  {
    id: 'citrix',
    vendor: 'Citrix',
    url: 'https://www.citrix.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['citrix', 'virtual desktop', 'daas', 'workspace'],
  },

  // ── Networking ────────────────────────────────────────────────────────────
  {
    id: 'cisco',
    vendor: 'Cisco',
    url: 'https://www.ciscolive.com/',
    defaultCategories: ['Cloud', 'IT / Ops', 'Cybersecurity'],
    tags: ['cisco', 'cisco live', 'networking'],
  },
  {
    id: 'juniper',
    vendor: 'Juniper Networks',
    url: 'https://www.juniper.net/us/en/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['juniper', 'nxtwork', 'networking'],
  },
  {
    id: 'f5',
    vendor: 'F5',
    url: 'https://www.f5.com/company/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['f5', 'appworld', 'load balancing'],
  },
  {
    id: 'arista',
    vendor: 'Arista Networks',
    url: 'https://www.arista.com/en/company/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['arista', 'eos', 'networking'],
  },

  // ── Cloud Networking / SD-WAN ─────────────────────────────────────────────
  {
    id: 'fortinet-sdwan',
    vendor: 'Fortinet SD-WAN',
    url: 'https://www.fortinet.com/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['fortinet', 'sd-wan', 'firewall', 'sase'],
  },
  {
    id: 'palo-alto-prisma-sdwan',
    vendor: 'Palo Alto Prisma SD-WAN',
    url: 'https://www.paloaltonetworks.com/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['palo alto', 'prisma', 'sd-wan', 'sase'],
  },
  {
    id: 'aryaka',
    vendor: 'Aryaka',
    url: 'https://www.aryaka.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['aryaka', 'sd-wan', 'managed network', 'sase'],
  },
  {
    id: 'masergy',
    vendor: 'Masergy (Comcast)',
    url: 'https://masergy.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['masergy', 'sd-wan', 'managed security', 'comcast'],
  },
  {
    id: 'cradlepoint',
    vendor: 'Cradlepoint (Ericsson)',
    url: 'https://cradlepoint.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['cradlepoint', 'sd-wan', 'iot', 'cellular'],
  },
  {
    id: 'gtt',
    vendor: 'GTT Communications',
    url: 'https://www.gtt.net/us-en/resources/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['gtt', 'sd-wan', 'managed network', 'enterprise connectivity'],
  },

  // ── Telco / Cloud Communications ─────────────────────────────────────────
  {
    id: 'bandwidth',
    vendor: 'Bandwidth',
    url: 'https://www.bandwidth.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['bandwidth', 'cpaas', 'voice', 'messaging'],
  },
  {
    id: 'ringcentral',
    vendor: 'RingCentral',
    url: 'https://www.ringcentral.com/us/en/events.html',
    defaultCategories: ['Cloud'],
    tags: ['ringcentral', 'ucaas', 'voip', 'contact center'],
  },
  {
    id: '8x8',
    vendor: '8x8',
    url: 'https://www.8x8.com/company/events',
    defaultCategories: ['Cloud'],
    tags: ['8x8', 'ucaas', 'ccaas', 'cloud communications'],
  },
  {
    id: 'vonage',
    vendor: 'Vonage (Ericsson)',
    url: 'https://www.vonage.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['vonage', 'cpaas', 'video api', 'ericsson'],
  },
  {
    id: 'telnyx',
    vendor: 'Telnyx',
    url: 'https://telnyx.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['telnyx', 'cpaas', 'voice', 'sms api'],
  },
  {
    id: 'lumen',
    vendor: 'Lumen Technologies',
    url: 'https://www.lumen.com/en-us/resources/events.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['lumen', 'edge cloud', 'network', 'connectivity'],
  },
  {
    id: 'zayo',
    vendor: 'Zayo',
    url: 'https://www.zayo.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['zayo', 'fiber', 'connectivity', 'network'],
  },
  {
    id: 'pccw-global',
    vendor: 'PCCW Global',
    url: 'https://www.pccwglobal.com/en/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['pccw', 'global network', 'connectivity', 'telco'],
  },

  // ── Cloud Security ────────────────────────────────────────────────────────
  {
    id: 'zscaler',
    vendor: 'Zscaler',
    url: 'https://www.zscaler.com/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['zscaler', 'zero trust', 'sase', 'cloud security'],
  },
  {
    id: 'netskope',
    vendor: 'Netskope',
    url: 'https://www.netskope.com/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['netskope', 'sase', 'casb', 'cloud security'],
  },
  {
    id: 'lookout',
    vendor: 'Lookout',
    url: 'https://www.lookout.com/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['lookout', 'mobile security', 'cloud security'],
  },
  {
    id: 'skyhigh-security',
    vendor: 'Skyhigh Security',
    url: 'https://www.skyhighsecurity.com/events/',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['skyhigh', 'casb', 'sase', 'cloud security'],
  },
  {
    id: 'iboss',
    vendor: 'iboss',
    url: 'https://www.iboss.com/events/',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['iboss', 'zero trust', 'sase', 'web gateway'],
  },
  {
    id: 'menlo-security',
    vendor: 'Menlo Security',
    url: 'https://www.menlosecurity.com/events/',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['menlo', 'browser isolation', 'secure web gateway'],
  },
  {
    id: 'forcepoint-one',
    vendor: 'Forcepoint ONE',
    url: 'https://www.forcepoint.com/events',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['forcepoint', 'sase', 'data security', 'cloud proxy'],
  },
  {
    id: 'mcafee-enterprise',
    vendor: 'McAfee Enterprise',
    url: 'https://www.mcafee.com/enterprise/en-us/events.html',
    defaultCategories: ['Cloud', 'Cybersecurity'],
    tags: ['mcafee', 'endpoint security', 'casb', 'cloud security'],
  },

  // ── Hyperconverged / On-prem Cloud ────────────────────────────────────────
  {
    id: 'scale-computing',
    vendor: 'Scale Computing',
    url: 'https://www.scalecomputing.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['scale computing', 'hyperconverged', 'edge computing'],
  },
  {
    id: 'starwind',
    vendor: 'StarWind',
    url: 'https://www.starwindsoftware.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['starwind', 'hyperconverged', 'vsan', 'storage'],
  },
  {
    id: 'stormagic',
    vendor: 'StorMagic',
    url: 'https://stormagic.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['stormagic', 'hyper-converged', 'edge storage'],
  },
  {
    id: 'datacore',
    vendor: 'DataCore',
    url: 'https://www.datacore.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['datacore', 'software-defined storage', 'hyperconverged'],
  },
  {
    id: 'maxta',
    vendor: 'Maxta',
    url: 'https://www.maxta.com/events',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['maxta', 'hyperconverged', 'storage'],
  },
  {
    id: 'suse',
    vendor: 'SUSE Enterprise Storage',
    url: 'https://www.suse.com/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['suse', 'linux', 'enterprise storage', 'ceph'],
  },

  // ── Container / Kubernetes Platforms ─────────────────────────────────────
  {
    id: 'suse-rancher',
    vendor: 'SUSE Rancher',
    url: 'https://www.suse.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['suse', 'rancher', 'kubernetes', 'containers'],
  },
  {
    id: 'mirantis',
    vendor: 'Mirantis',
    url: 'https://www.mirantis.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['mirantis', 'kubernetes', 'containers', 'openstack'],
  },
  {
    id: 'platform9',
    vendor: 'Platform9',
    url: 'https://platform9.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['platform9', 'kubernetes', 'managed k8s'],
  },
  {
    id: 'giant-swarm',
    vendor: 'Giant Swarm',
    url: 'https://www.giantswarm.io/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['giant swarm', 'kubernetes', 'managed k8s'],
  },
  {
    id: 'd2iq',
    vendor: 'D2iQ',
    url: 'https://d2iq.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['d2iq', 'kubernetes', 'dkp', 'enterprise k8s'],
  },
  {
    id: 'kubermatic',
    vendor: 'Kubermatic',
    url: 'https://www.kubermatic.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['kubermatic', 'kubernetes', 'gitops', 'multicloud'],
  },
  {
    id: 'spectro-cloud',
    vendor: 'Spectro Cloud',
    url: 'https://www.spectrocloud.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['spectro cloud', 'kubernetes', 'palette', 'edge k8s'],
  },
  {
    id: 'rafay',
    vendor: 'Rafay',
    url: 'https://rafay.co/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['rafay', 'kubernetes', 'platform engineering'],
  },
  {
    id: 'nirmata',
    vendor: 'Nirmata',
    url: 'https://nirmata.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['nirmata', 'kubernetes', 'kyverno', 'policy management'],
  },

  // ── Cloud Conferences ─────────────────────────────────────────────────────
  {
    id: 'aws-reinvent',
    vendor: 'AWS re:Invent',
    url: 'https://reinvent.awsevents.com/',
    defaultCategories: ['Cloud', 'Developer', 'AI'],
    tags: ['aws', 'reinvent', 'amazon', 'conference'],
  },
  {
    id: 'microsoft-build',
    vendor: 'Microsoft Build',
    url: 'https://build.microsoft.com/',
    defaultCategories: ['Cloud', 'Developer', 'AI'],
    tags: ['microsoft', 'build', 'developer', 'conference'],
  },
  {
    id: 'google-cloud-next',
    vendor: 'Google Cloud Next',
    url: 'https://cloud.withgoogle.com/next',
    defaultCategories: ['Cloud', 'Developer', 'AI'],
    tags: ['google cloud', 'next', 'gcp', 'conference'],
  },
  {
    id: 'kubecon',
    vendor: 'KubeCon / CloudNativeCon (CNCF)',
    url: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['kubecon', 'cncf', 'kubernetes', 'cloud native'],
  },
  {
    id: 'gartner-it-summit',
    vendor: 'Gartner IT Symposium/Xpo',
    url: 'https://www.gartner.com/en/conferences/hub/it-symposium-conferences',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['gartner', 'it symposium', 'cio', 'analyst'],
  },
  {
    id: 'gartner-infra-ops',
    vendor: 'Gartner Infrastructure & Operations',
    url: 'https://www.gartner.com/en/conferences/hub/infrastructure-operations-conferences',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['gartner', 'infrastructure', 'operations', 'analyst'],
  },
  {
    id: 'cloud-expo-europe',
    vendor: 'Cloud Expo Europe',
    url: 'https://www.cloudexpoeurope.com/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['cloud expo', 'europe', 'conference'],
  },
  {
    id: 'cloudfest',
    vendor: 'CloudFest',
    url: 'https://www.cloudfest.com/',
    defaultCategories: ['Cloud'],
    tags: ['cloudfest', 'hosting', 'conference'],
  },
  {
    id: 'finops-x',
    vendor: 'FinOps X',
    url: 'https://x.finops.org/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['finops', 'cloud cost', 'conference'],
  },
  {
    id: 'microsoft-ignite',
    vendor: 'Microsoft Ignite',
    url: 'https://ignite.microsoft.com/',
    defaultCategories: ['Cloud', 'Developer', 'AI'],
    tags: ['microsoft', 'ignite', 'azure', 'conference'],
  },
  {
    id: 'aws-remars',
    vendor: 'AWS re:Mars',
    url: 'https://remars.amazonwebservices.com/',
    defaultCategories: ['Cloud', 'AI'],
    tags: ['aws', 'remars', 'machine learning', 'ai'],
  },
  {
    id: 'google-io',
    vendor: 'Google I/O',
    url: 'https://io.google/',
    defaultCategories: ['Cloud', 'Developer', 'AI'],
    tags: ['google', 'i/o', 'developer', 'android'],
  },
  {
    id: 'microsoft-inspire',
    vendor: 'Microsoft Inspire',
    url: 'https://inspire.microsoft.com/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['microsoft', 'inspire', 'partner', 'conference'],
  },
  {
    id: 'cloud-devops-world',
    vendor: 'Cloud & DevOps World',
    url: 'https://www.clouddevopsworld.com/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['cloud', 'devops', 'conference', 'tech'],
  },
];
