// Cybersecurity vendor event configs.
// Each entry is scraped by the generic vendor-scraper engine.
// selectors: optional overrides — engine falls back to generic selectors if omitted.

module.exports = [

  // ── Endpoint Security / EDR ───────────────────────────────────────────────
  {
    id: 'crowdstrike',
    vendor: 'CrowdStrike',
    url: 'https://www.crowdstrike.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['edr', 'xdr', 'endpoint', 'threat hunting'],
  },
  {
    id: 'sentinelone',
    vendor: 'SentinelOne',
    url: 'https://www.sentinelone.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['edr', 'xdr', 'endpoint', 'ai security'],
  },
  {
    id: 'carbon-black',
    vendor: 'VMware Carbon Black',
    url: 'https://carbonblack.vmware.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['edr', 'endpoint', 'vmware', 'carbon black'],
  },
  {
    id: 'cylance',
    vendor: 'BlackBerry Cylance',
    url: 'https://www.blackberry.com/us/en/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['edr', 'endpoint', 'ai security', 'cylance'],
  },
  {
    id: 'sophos',
    vendor: 'Sophos',
    url: 'https://www.sophos.com/en-us/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'edr', 'firewall', 'mdr'],
  },
  {
    id: 'eset',
    vendor: 'ESET',
    url: 'https://www.eset.com/us/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'antivirus', 'edr', 'threat detection'],
  },
  {
    id: 'bitdefender',
    vendor: 'Bitdefender',
    url: 'https://www.bitdefender.com/en-us/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'edr', 'antivirus', 'threat intelligence'],
  },
  {
    id: 'malwarebytes',
    vendor: 'Malwarebytes',
    url: 'https://www.malwarebytes.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'malware', 'edr', 'threat remediation'],
  },
  {
    id: 'trendmicro',
    vendor: 'Trend Micro',
    url: 'https://www.trendmicro.com/en_us/events.html',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'xdr', 'cloud security', 'threat intelligence'],
  },
  {
    id: 'trellix',
    vendor: 'Trellix',
    url: 'https://www.trellix.com/about/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['edr', 'xdr', 'siem', 'mcafee'],
  },
  {
    id: 'broadcom-symantec',
    vendor: 'Broadcom Symantec',
    url: 'https://www.broadcom.com/company/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'dlp', 'network security', 'symantec'],
  },
  {
    id: 'deep-instinct',
    vendor: 'Deep Instinct',
    url: 'https://www.deepinstinct.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'deep learning', 'ai security', 'prevention'],
  },
  {
    id: 'cybereason',
    vendor: 'Cybereason',
    url: 'https://www.cybereason.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['edr', 'xdr', 'endpoint', 'threat hunting'],
  },
  {
    id: 'morphisec',
    vendor: 'Morphisec',
    url: 'https://www.morphisec.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'moving target defense', 'prevention', 'edr'],
  },
  {
    id: 'webroot',
    vendor: 'OpenText Webroot',
    url: 'https://www.webroot.com/us/en/about/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'dns security', 'threat intelligence', 'smb'],
  },
  {
    id: 'huntress',
    vendor: 'Huntress',
    url: 'https://www.huntress.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['mdr', 'edr', 'mssp', 'smb security'],
  },
  {
    id: 'xcitium',
    vendor: 'Xcitium',
    url: 'https://www.xcitium.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'zero trust', 'containment', 'comodo'],
  },
  {
    id: 'tanium',
    vendor: 'Tanium',
    url: 'https://www.tanium.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'asset management', 'patch management', 'xem'],
  },
  {
    id: 'ivanti',
    vendor: 'Ivanti',
    url: 'https://www.ivanti.com/company/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['endpoint', 'patch management', 'itsm', 'zero trust'],
  },
  {
    id: 'attivo',
    vendor: 'SentinelOne Attivo',
    url: 'https://www.attivonetworks.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['deception', 'identity security', 'lateral movement', 'edr'],
  },

  // ── Network Security / NGFW ───────────────────────────────────────────────
  {
    id: 'paloalto',
    vendor: 'Palo Alto Networks',
    url: 'https://www.paloaltonetworks.com/events',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['ngfw', 'sase', 'zero trust', 'xdr'],
  },
  {
    id: 'fortinet',
    vendor: 'Fortinet',
    url: 'https://www.fortinet.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['ngfw', 'sase', 'sd-wan', 'network security'],
  },
  {
    id: 'checkpoint',
    vendor: 'Check Point',
    url: 'https://www.checkpoint.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['ngfw', 'cloud security', 'threat prevention', 'zero trust'],
  },
  {
    id: 'sonicwall',
    vendor: 'SonicWall',
    url: 'https://www.sonicwall.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['ngfw', 'network security', 'smb', 'threat prevention'],
  },
  {
    id: 'watchguard',
    vendor: 'WatchGuard',
    url: 'https://www.watchguard.com/wgrd-events',
    defaultCategories: ['Cybersecurity'],
    tags: ['ngfw', 'network security', 'mfa', 'smb'],
  },
  {
    id: 'barracuda',
    vendor: 'Barracuda',
    url: 'https://www.barracuda.com/company/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['email security', 'network security', 'firewall', 'cloud'],
  },
  {
    id: 'cato-networks',
    vendor: 'Cato Networks',
    url: 'https://www.catonetworks.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['sase', 'sd-wan', 'network security', 'zero trust'],
  },
  {
    id: 'netskope',
    vendor: 'Netskope',
    url: 'https://www.netskope.com/events',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['sase', 'casb', 'sse', 'zero trust'],
  },
  {
    id: 'versa-networks',
    vendor: 'Versa Networks',
    url: 'https://versa-networks.com/company/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['sase', 'sd-wan', 'network security', 'zero trust'],
  },
  {
    id: 'illumio',
    vendor: 'Illumio',
    url: 'https://www.illumio.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['microsegmentation', 'zero trust', 'network security', 'ransomware'],
  },
  {
    id: 'tufin',
    vendor: 'Tufin',
    url: 'https://www.tufin.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['network security', 'firewall policy', 'security automation', 'compliance'],
  },
  {
    id: 'algosec',
    vendor: 'AlgoSec',
    url: 'https://www.algosec.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['network security', 'firewall management', 'compliance', 'automation'],
  },
  {
    id: 'firemon',
    vendor: 'FireMon',
    url: 'https://www.firemon.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['network security', 'policy management', 'firewall', 'compliance'],
  },
  {
    id: 'guardicore',
    vendor: 'Guardicore (Akamai)',
    url: 'https://www.akamai.com/events',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['microsegmentation', 'zero trust', 'network security', 'akamai'],
  },
  {
    id: 'skybox-security',
    vendor: 'Skybox Security',
    url: 'https://www.skyboxsecurity.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['network security', 'attack surface', 'firewall', 'vulnerability management'],
  },

  // ── SIEM / SOAR / Analytics ───────────────────────────────────────────────
  {
    id: 'splunk',
    vendor: 'Splunk',
    url: 'https://conf.splunk.com/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['siem', 'soar', 'observability', 'data analytics'],
  },
  {
    id: 'ibm-qradar',
    vendor: 'IBM QRadar',
    url: 'https://www.ibm.com/events/think/',
    defaultCategories: ['Cybersecurity'],
    tags: ['siem', 'soar', 'threat intelligence', 'ibm security'],
  },
  {
    id: 'logrhythm',
    vendor: 'LogRhythm',
    url: 'https://logrhythm.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['siem', 'soar', 'ueba', 'threat detection'],
  },
  {
    id: 'exabeam',
    vendor: 'Exabeam',
    url: 'https://www.exabeam.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['siem', 'ueba', 'soar', 'threat detection'],
  },
  {
    id: 'securonix',
    vendor: 'Securonix',
    url: 'https://www.securonix.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['siem', 'ueba', 'soar', 'cloud security'],
  },
  {
    id: 'devo',
    vendor: 'Devo',
    url: 'https://www.devo.com/events/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['siem', 'security analytics', 'cloud siem', 'threat detection'],
  },
  {
    id: 'arcsight',
    vendor: 'OpenText ArcSight',
    url: 'https://www.opentext.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['siem', 'soar', 'threat detection', 'compliance'],
  },
  {
    id: 'rapid7',
    vendor: 'Rapid7',
    url: 'https://www.rapid7.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['siem', 'vulnerability management', 'soar', 'mdr'],
  },
  {
    id: 'swimlane',
    vendor: 'Swimlane',
    url: 'https://swimlane.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['soar', 'security automation', 'orchestration', 'low-code'],
  },
  {
    id: 'torq',
    vendor: 'Torq',
    url: 'https://torq.io/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['soar', 'hyperautomation', 'security automation', 'no-code'],
  },
  {
    id: 'levelblue',
    vendor: 'LevelBlue',
    url: 'https://levelblue.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['siem', 'threat intelligence', 'mdr', 'att&ck'],
  },
  {
    id: 'ms-sentinel',
    vendor: 'Microsoft Sentinel',
    url: 'https://events.microsoft.com/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['siem', 'soar', 'cloud security', 'microsoft'],
  },
  {
    id: 'sumo-logic',
    vendor: 'Sumo Logic',
    url: 'https://www.sumologic.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['siem', 'log management', 'security analytics', 'cloud'],
  },
  {
    id: 'chronicle',
    vendor: 'Google Chronicle',
    url: 'https://cloud.google.com/blog/products/identity-security',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['siem', 'threat intelligence', 'google security', 'cloud'],
  },
  {
    id: 'stellar-cyber',
    vendor: 'Stellar Cyber',
    url: 'https://stellarcyber.ai/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['open xdr', 'siem', 'ai security', 'threat detection'],
  },

  // ── Identity & Access Management ──────────────────────────────────────────
  {
    id: 'okta',
    vendor: 'Okta',
    url: 'https://www.okta.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['iam', 'sso', 'mfa', 'zero trust'],
  },
  {
    id: 'cyberark',
    vendor: 'CyberArk',
    url: 'https://www.cyberark.com/impact/',
    defaultCategories: ['Cybersecurity'],
    tags: ['pam', 'identity security', 'privileged access', 'zero trust'],
  },
  {
    id: 'sailpoint',
    vendor: 'SailPoint',
    url: 'https://www.sailpoint.com/navigate/',
    defaultCategories: ['Cybersecurity'],
    tags: ['iam', 'identity governance', 'access management', 'compliance'],
  },
  {
    id: 'beyondtrust',
    vendor: 'BeyondTrust',
    url: 'https://www.beyondtrust.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['pam', 'privileged access', 'identity security', 'remote access'],
  },
  {
    id: 'ping-identity',
    vendor: 'Ping Identity',
    url: 'https://www.pingidentity.com/en/company/events.html',
    defaultCategories: ['Cybersecurity'],
    tags: ['iam', 'sso', 'mfa', 'identity security'],
  },
  {
    id: 'one-identity',
    vendor: 'One Identity',
    url: 'https://www.oneidentity.com/company/events.aspx',
    defaultCategories: ['Cybersecurity'],
    tags: ['iam', 'pam', 'identity governance', 'active directory'],
  },
  {
    id: 'forgerock',
    vendor: 'ForgeRock (OpenText)',
    url: 'https://www.opentext.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['iam', 'ciam', 'identity platform', 'access management'],
  },
  {
    id: 'thales-digital-identity',
    vendor: 'Thales Digital Identity',
    url: 'https://cpl.thalesgroup.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['iam', 'pki', 'digital identity', 'authentication'],
  },
  {
    id: 'entrust',
    vendor: 'Entrust',
    url: 'https://www.entrust.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['digital identity', 'pki', 'iam', 'encryption'],
  },
  {
    id: 'yubico',
    vendor: 'Yubico',
    url: 'https://www.yubico.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['mfa', 'hardware security key', 'phishing resistant', 'fido2'],
  },
  {
    id: 'delinea',
    vendor: 'Delinea',
    url: 'https://delinea.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['pam', 'privileged access', 'identity security', 'zero trust'],
  },
  {
    id: 'saviynt',
    vendor: 'Saviynt',
    url: 'https://saviynt.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['iam', 'identity governance', 'cloud pam', 'access management'],
  },
  {
    id: 'omada-identity',
    vendor: 'Omada Identity',
    url: 'https://www.omadaidentity.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['iam', 'identity governance', 'iga', 'compliance'],
  },
  {
    id: 'radiant-logic',
    vendor: 'Radiant Logic',
    url: 'https://www.radiantlogic.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['identity data', 'iam', 'directory services', 'identity fabric'],
  },
  {
    id: 'auth0',
    vendor: 'Auth0 (Okta)',
    url: 'https://auth0.com/events',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['ciam', 'developer identity', 'authentication', 'api security'],
  },
  {
    id: 'silverfort',
    vendor: 'Silverfort',
    url: 'https://www.silverfort.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['identity protection', 'mfa', 'zero trust', 'lateral movement'],
  },
  {
    id: 'wallix',
    vendor: 'Wallix',
    url: 'https://www.wallix.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['pam', 'privileged access', 'session management', 'compliance'],
  },
  {
    id: 'strongdm',
    vendor: 'StrongDM',
    url: 'https://www.strongdm.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['pam', 'infrastructure access', 'zero trust', 'devops'],
  },
  {
    id: 'transmit-security',
    vendor: 'Transmit Security',
    url: 'https://transmitsecurity.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['ciam', 'passwordless', 'fraud prevention', 'identity'],
  },
  {
    id: 'beyond-identity',
    vendor: 'Beyond Identity',
    url: 'https://www.beyondidentity.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['passwordless', 'mfa', 'zero trust', 'phishing resistant'],
  },

  // ── Vulnerability Management / Attack Surface ─────────────────────────────
  {
    id: 'tenable',
    vendor: 'Tenable',
    url: 'https://www.tenable.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['vulnerability management', 'nessus', 'attack surface', 'compliance'],
  },
  {
    id: 'qualys',
    vendor: 'Qualys',
    url: 'https://www.qualys.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['vulnerability management', 'cloud security', 'compliance', 'asset management'],
  },
  {
    id: 'fortra-tripwire',
    vendor: 'Fortra Tripwire',
    url: 'https://www.fortra.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['vulnerability management', 'configuration management', 'compliance', 'file integrity'],
  },
  {
    id: 'vulcan-cyber',
    vendor: 'Vulcan Cyber',
    url: 'https://vulcan.io/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['vulnerability management', 'remediation', 'risk prioritization', 'appsec'],
  },
  {
    id: 'rezilion',
    vendor: 'Rezilion',
    url: 'https://www.rezilion.com/events/',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['vulnerability management', 'software supply chain', 'sbom', 'devsecops'],
  },
  {
    id: 'nucleus-security',
    vendor: 'Nucleus Security',
    url: 'https://nucleussec.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['vulnerability management', 'risk prioritization', 'remediation', 'compliance'],
  },
  {
    id: 'cymulate',
    vendor: 'Cymulate',
    url: 'https://cymulate.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['breach simulation', 'attack surface', 'vulnerability management', 'red team'],
  },
  {
    id: 'attackiq',
    vendor: 'AttackIQ',
    url: 'https://www.attackiq.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['breach simulation', 'mitre att&ck', 'security validation', 'red team'],
  },
  {
    id: 'safebreach',
    vendor: 'SafeBreach',
    url: 'https://www.safebreach.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['breach simulation', 'security validation', 'attack surface', 'red team'],
  },
  {
    id: 'xm-cyber',
    vendor: 'XM Cyber',
    url: 'https://www.xmcyber.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['attack path management', 'exposure management', 'attack surface', 'risk'],
  },
  {
    id: 'censys',
    vendor: 'Censys',
    url: 'https://censys.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['attack surface management', 'asset discovery', 'exposure management', 'threat intelligence'],
  },
  {
    id: 'runzero',
    vendor: 'runZero',
    url: 'https://www.runzero.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['asset discovery', 'attack surface', 'network visibility', 'asset management'],
  },
  {
    id: 'picus-security',
    vendor: 'Picus Security',
    url: 'https://www.picussecurity.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['breach simulation', 'security validation', 'mitre att&ck', 'threat exposure'],
  },
  {
    id: 'brinqa',
    vendor: 'Brinqa',
    url: 'https://www.brinqa.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['attack surface', 'risk-based vulnerability management', 'exposure management', 'remediation'],
  },

  // ── Cloud Security / CSPM / CNAPP ─────────────────────────────────────────
  {
    id: 'wiz',
    vendor: 'Wiz',
    url: 'https://www.wiz.io/events',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['cnapp', 'cspm', 'cloud security', 'vulnerability management'],
  },
  {
    id: 'lacework',
    vendor: 'Lacework',
    url: 'https://www.lacework.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['cnapp', 'cspm', 'cloud security', 'anomaly detection'],
  },
  {
    id: 'orca-security',
    vendor: 'Orca Security',
    url: 'https://orca.security/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['cnapp', 'cspm', 'cloud security', 'agentless'],
  },
  {
    id: 'aqua-security',
    vendor: 'Aqua Security',
    url: 'https://www.aquasec.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['container security', 'cloud native', 'devsecops', 'kubernetes'],
  },
  {
    id: 'sysdig',
    vendor: 'Sysdig',
    url: 'https://sysdig.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['container security', 'cloud native', 'kubernetes', 'runtime security'],
  },
  {
    id: 'snyk',
    vendor: 'Snyk',
    url: 'https://snyk.io/events/',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['devsecops', 'software supply chain', 'open source security', 'appsec'],
  },
  {
    id: 'checkmarx',
    vendor: 'Checkmarx',
    url: 'https://checkmarx.com/events/',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['appsec', 'sast', 'devsecops', 'code security'],
  },
  {
    id: 'veracode',
    vendor: 'Veracode',
    url: 'https://www.veracode.com/resources/events',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['appsec', 'sast', 'dast', 'devsecops'],
  },
  {
    id: 'mend',
    vendor: 'Mend (WhiteSource)',
    url: 'https://www.mend.io/events/',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['sca', 'open source security', 'software supply chain', 'devsecops'],
  },
  {
    id: 'synopsys',
    vendor: 'Synopsys',
    url: 'https://www.synopsys.com/events.html',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['appsec', 'sast', 'sca', 'software security'],
  },
  {
    id: 'prisma-cloud',
    vendor: 'Prisma Cloud (Palo Alto)',
    url: 'https://www.paloaltonetworks.com/events',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['cnapp', 'cspm', 'cloud security', 'devsecops'],
  },
  {
    id: 'cloudguard',
    vendor: 'Check Point CloudGuard',
    url: 'https://www.checkpoint.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['cloud security', 'cnapp', 'cspm', 'workload protection'],
  },
  {
    id: 'anchore',
    vendor: 'Anchore',
    url: 'https://anchore.com/events/',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['container security', 'sbom', 'software supply chain', 'devsecops'],
  },
  {
    id: 'ermetic',
    vendor: 'Ermetic (Tenable)',
    url: 'https://ermetic.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['ciem', 'cloud identity', 'cspm', 'cloud security'],
  },
  {
    id: 'trend-cloud-one',
    vendor: 'Trend Cloud One',
    url: 'https://www.trendmicro.com/en_us/events.html',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['cloud security', 'workload protection', 'container security', 'cnapp'],
  },

  // ── Application Security / API Security ───────────────────────────────────
  {
    id: 'imperva',
    vendor: 'Imperva',
    url: 'https://www.imperva.com/resources/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['waf', 'ddos', 'api security', 'data security'],
  },
  {
    id: 'radware',
    vendor: 'Radware',
    url: 'https://www.radware.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['ddos', 'waf', 'api security', 'cloud security'],
  },
  {
    id: 'fastly-security',
    vendor: 'Fastly Security',
    url: 'https://www.fastly.com/events',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['waf', 'cdn security', 'ddos', 'edge security'],
  },
  {
    id: 'human-security',
    vendor: 'HUMAN Security',
    url: 'https://www.humansecurity.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['bot management', 'fraud prevention', 'account takeover', 'ad fraud'],
  },
  {
    id: 'noname-security',
    vendor: 'Noname Security',
    url: 'https://nonamesecurity.com/events',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['api security', 'api posture', 'runtime protection', 'discovery'],
  },
  {
    id: 'salt-security',
    vendor: 'Salt Security',
    url: 'https://salt.security/events/',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['api security', 'api protection', 'threat prevention', 'ai security'],
  },
  {
    id: 'traceable-ai',
    vendor: 'Traceable AI',
    url: 'https://www.traceable.ai/events',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['api security', 'api observability', 'threat detection', 'ai security'],
  },
  {
    id: 'wallarm',
    vendor: 'Wallarm',
    url: 'https://www.wallarm.com/events',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['waf', 'api security', 'appsec', 'runtime protection'],
  },
  {
    id: 'contrast-security',
    vendor: 'Contrast Security',
    url: 'https://www.contrastsecurity.com/events',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['iast', 'rasp', 'appsec', 'devsecops'],
  },
  {
    id: 'fortify',
    vendor: 'OpenText Fortify',
    url: 'https://www.opentext.com/events',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['sast', 'dast', 'appsec', 'code security'],
  },
  {
    id: '42crunch',
    vendor: '42Crunch',
    url: 'https://42crunch.com/events/',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['api security', 'openapi', 'api audit', 'devsecops'],
  },
  {
    id: 'portswigger',
    vendor: 'PortSwigger (Burp Suite)',
    url: 'https://portswigger.net/events',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['web security testing', 'dast', 'penetration testing', 'appsec'],
  },

  // ── Email & Messaging Security ────────────────────────────────────────────
  {
    id: 'proofpoint',
    vendor: 'Proofpoint',
    url: 'https://www.proofpoint.com/us/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['email security', 'phishing', 'dlp', 'threat protection'],
  },
  {
    id: 'mimecast',
    vendor: 'Mimecast',
    url: 'https://www.mimecast.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['email security', 'threat protection', 'archiving', 'continuity'],
  },
  {
    id: 'abnormal-security',
    vendor: 'Abnormal Security',
    url: 'https://abnormalsecurity.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['email security', 'ato', 'ai security', 'phishing'],
  },
  {
    id: 'tessian',
    vendor: 'Tessian (Proofpoint)',
    url: 'https://www.proofpoint.com/us/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['email security', 'human layer security', 'dlp', 'insider threat'],
  },
  {
    id: 'avanan',
    vendor: 'Avanan (Check Point)',
    url: 'https://www.avanan.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['email security', 'cloud email', 'microsoft 365', 'phishing'],
  },
  {
    id: 'cofense',
    vendor: 'Cofense',
    url: 'https://cofense.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['phishing', 'email security', 'security awareness', 'incident response'],
  },
  {
    id: 'ironscales',
    vendor: 'IRONSCALES',
    url: 'https://ironscales.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['email security', 'anti-phishing', 'ai security', 'security awareness'],
  },
  {
    id: 'egress',
    vendor: 'Egress',
    url: 'https://www.egress.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['email security', 'dlp', 'insider threat', 'human layer security'],
  },
  {
    id: 'valimail',
    vendor: 'Valimail',
    url: 'https://www.valimail.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['email authentication', 'dmarc', 'phishing prevention', 'brand protection'],
  },
  {
    id: 'agari',
    vendor: 'Agari (HelpSystems)',
    url: 'https://www.fortra.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['email security', 'phishing', 'dmarc', 'brand protection'],
  },

  // ── Threat Intelligence ───────────────────────────────────────────────────
  {
    id: 'recordedfuture',
    vendor: 'Recorded Future',
    url: 'https://www.recordedfuture.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'dark web', 'risk intelligence', 'threat hunting'],
  },
  {
    id: 'mandiant',
    vendor: 'Mandiant (Google)',
    url: 'https://mwise.mandiant.com/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'incident response', 'threat hunting', 'google security'],
  },
  {
    id: 'threatconnect',
    vendor: 'ThreatConnect',
    url: 'https://threatconnect.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'soar', 'risk quantification', 'threat hunting'],
  },
  {
    id: 'anomali',
    vendor: 'Anomali',
    url: 'https://www.anomali.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'siem', 'threat detection', 'security analytics'],
  },
  {
    id: 'threatquotient',
    vendor: 'ThreatQuotient',
    url: 'https://www.threatq.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'threat operations', 'soar', 'data-driven security'],
  },
  {
    id: 'reliaquest',
    vendor: 'ReliaQuest',
    url: 'https://www.reliaquest.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'mdr', 'digital shadows', 'threat detection'],
  },
  {
    id: 'zerofox',
    vendor: 'ZeroFOX',
    url: 'https://www.zerofox.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['digital risk protection', 'threat intelligence', 'social media security', 'dark web'],
  },
  {
    id: 'intel471',
    vendor: 'Intel 471',
    url: 'https://intel471.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'cybercrime', 'dark web', 'adversary intelligence'],
  },
  {
    id: 'flashpoint',
    vendor: 'Flashpoint',
    url: 'https://flashpoint.io/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'dark web', 'vulnerability intelligence', 'fraud'],
  },
  {
    id: 'cyble',
    vendor: 'Cyble',
    url: 'https://cyble.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'dark web', 'attack surface', 'ai security'],
  },
  {
    id: 'group-ib',
    vendor: 'Group-IB',
    url: 'https://www.group-ib.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'cybercrime', 'incident response', 'fraud prevention'],
  },
  {
    id: 'kela-cyber',
    vendor: 'KELA Cyber',
    url: 'https://ke-la.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'dark web', 'cybercrime', 'ransomware'],
  },

  // ── Data Security / DLP / DSPM ────────────────────────────────────────────
  {
    id: 'forcepoint',
    vendor: 'Forcepoint',
    url: 'https://www.forcepoint.com/company/events',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['dlp', 'data security', 'insider threat', 'zero trust'],
  },
  {
    id: 'digital-guardian',
    vendor: 'Fortra Digital Guardian',
    url: 'https://www.fortra.com/events',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['dlp', 'data protection', 'insider threat', 'endpoint dlp'],
  },
  {
    id: 'varonis',
    vendor: 'Varonis',
    url: 'https://www.varonis.com/events',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['data security', 'dspm', 'insider threat', 'data access governance'],
  },
  {
    id: 'bigid',
    vendor: 'BigID',
    url: 'https://bigid.com/events/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['dspm', 'data privacy', 'data discovery', 'compliance'],
  },
  {
    id: 'securiti',
    vendor: 'Securiti',
    url: 'https://securiti.ai/events/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['dspm', 'data privacy', 'data governance', 'ai security'],
  },
  {
    id: 'nightfall-ai',
    vendor: 'Nightfall AI',
    url: 'https://www.nightfall.ai/events',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['dlp', 'cloud dlp', 'ai security', 'data discovery'],
  },
  {
    id: 'spirion',
    vendor: 'Spirion',
    url: 'https://www.spirion.com/events/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['data discovery', 'dspm', 'data classification', 'privacy'],
  },
  {
    id: 'code42',
    vendor: 'Code42 (Incydr)',
    url: 'https://www.code42.com/events/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['insider threat', 'data protection', 'dlp', 'ip theft'],
  },
  {
    id: 'pkware',
    vendor: 'PKWARE',
    url: 'https://www.pkware.com/events/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['data protection', 'encryption', 'data classification', 'compliance'],
  },
  {
    id: 'seclore',
    vendor: 'Seclore',
    url: 'https://www.seclore.com/events/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['data-centric security', 'digital rights management', 'dlp', 'data protection'],
  },

  // ── GRC / Risk / Compliance ───────────────────────────────────────────────
  {
    id: 'onetrust',
    vendor: 'OneTrust',
    url: 'https://www.onetrust.com/events/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['grc', 'privacy', 'compliance', 'trust management'],
  },
  {
    id: 'trustarc',
    vendor: 'TrustArc',
    url: 'https://trustarc.com/events/',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['privacy', 'compliance', 'gdpr', 'risk management'],
  },
  {
    id: 'rsa-archer',
    vendor: 'RSA Archer',
    url: 'https://www.rsa.com/en-us/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['grc', 'risk management', 'compliance', 'audit management'],
  },
  {
    id: 'metricstream',
    vendor: 'MetricStream',
    url: 'https://www.metricstream.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['grc', 'risk management', 'compliance', 'audit management'],
  },
  {
    id: 'logicgate',
    vendor: 'LogicGate',
    url: 'https://www.logicgate.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['grc', 'risk management', 'compliance', 'no-code'],
  },
  {
    id: 'bitsight',
    vendor: 'BitSight',
    url: 'https://www.bitsight.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['cyber risk', 'security ratings', 'third-party risk', 'vendor risk'],
  },
  {
    id: 'securityscorecard',
    vendor: 'SecurityScorecard',
    url: 'https://securityscorecard.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['cyber risk', 'security ratings', 'third-party risk', 'vendor risk'],
  },
  {
    id: 'riskcon',
    vendor: 'RiskRecon (Mastercard)',
    url: 'https://www.riskrecon.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['third-party risk', 'security ratings', 'vendor risk', 'cyber risk'],
  },
  {
    id: 'upguard',
    vendor: 'UpGuard',
    url: 'https://www.upguard.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['attack surface', 'third-party risk', 'security ratings', 'vendor risk'],
  },
  {
    id: 'prevalent',
    vendor: 'Prevalent',
    url: 'https://www.prevalent.net/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['third-party risk', 'vendor risk', 'grc', 'supply chain'],
  },
  {
    id: 'riskonnect',
    vendor: 'Riskonnect',
    url: 'https://riskonnect.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['grc', 'enterprise risk', 'compliance', 'risk management'],
  },
  {
    id: 'galvanize',
    vendor: 'Galvanize (Diligent)',
    url: 'https://www.diligent.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['grc', 'audit management', 'compliance', 'risk management'],
  },
  {
    id: 'pathlock',
    vendor: 'Pathlock',
    url: 'https://pathlock.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['grc', 'access governance', 'erp security', 'compliance'],
  },
  {
    id: 'processunity',
    vendor: 'ProcessUnity',
    url: 'https://www.processunity.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['third-party risk', 'vendor risk', 'grc', 'supply chain'],
  },
  {
    id: 'resolver',
    vendor: 'Resolver',
    url: 'https://www.resolver.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['grc', 'incident management', 'risk management', 'compliance'],
  },

  // ── Security Awareness & Training ─────────────────────────────────────────
  {
    id: 'knowbe4',
    vendor: 'KnowBe4',
    url: 'https://www.knowbe4.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['security awareness', 'phishing simulation', 'training', 'human risk'],
  },
  {
    id: 'proofpoint-awareness',
    vendor: 'Proofpoint Security Awareness',
    url: 'https://www.proofpoint.com/us/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['security awareness', 'phishing simulation', 'training', 'human layer'],
  },
  {
    id: 'infosec-institute',
    vendor: 'Infosec Institute',
    url: 'https://www.infosecinstitute.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['security training', 'certification', 'security awareness', 'skills development'],
  },
  {
    id: 'terranova-security',
    vendor: 'Terranova Security',
    url: 'https://terranovasecurity.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['security awareness', 'phishing simulation', 'training', 'human risk'],
  },
  {
    id: 'ninjio',
    vendor: 'NINJIO',
    url: 'https://ninjio.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['security awareness', 'micro-learning', 'phishing simulation', 'training'],
  },
  {
    id: 'living-security',
    vendor: 'Living Security',
    url: 'https://livingsecurity.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['security awareness', 'human risk management', 'training', 'behavior change'],
  },
  {
    id: 'immersive-labs',
    vendor: 'Immersive Labs',
    url: 'https://www.immersivelabs.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['cyber resilience', 'skills development', 'crisis simulation', 'training'],
  },
  {
    id: 'sans',
    vendor: 'SANS Institute',
    url: 'https://www.sans.org/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['security training', 'certification', 'penetration testing', 'incident response'],
    selectors: {
      cards: '.event-listing, article, .course-event',
      title: 'h3, h4, .event-name',
      date:  'time, .event-date, [class*="date"]',
      location: '.event-location, [class*="location"]',
    },
  },

  // ── MDR / MSSP ────────────────────────────────────────────────────────────
  {
    id: 'arctic-wolf',
    vendor: 'Arctic Wolf',
    url: 'https://arcticwolf.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['mdr', 'soc', 'threat detection', 'concierge security'],
  },
  {
    id: 'expel',
    vendor: 'Expel',
    url: 'https://expel.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['mdr', 'soc', 'transparency', 'threat detection'],
  },
  {
    id: 'red-canary',
    vendor: 'Red Canary',
    url: 'https://redcanary.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['mdr', 'threat detection', 'incident response', 'edr'],
  },
  {
    id: 'deepwatch',
    vendor: 'Deepwatch',
    url: 'https://www.deepwatch.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['mdr', 'soc', 'threat detection', 'managed security'],
  },
  {
    id: 'esentire',
    vendor: 'eSentire',
    url: 'https://www.esentire.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['mdr', 'soc', 'threat response', 'managed security'],
  },
  {
    id: 'secureworks',
    vendor: 'Secureworks',
    url: 'https://www.secureworks.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['mdr', 'threat detection', 'incident response', 'security operations'],
  },
  {
    id: 'criticalstart',
    vendor: 'CRITICALSTART',
    url: 'https://www.criticalstart.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['mdr', 'soc', 'zero trust analytics', 'threat detection'],
  },
  {
    id: 'netsurion',
    vendor: 'Netsurion',
    url: 'https://www.netsurion.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['mdr', 'managed siem', 'soc', 'threat detection'],
  },
  {
    id: 'kroll',
    vendor: 'Kroll',
    url: 'https://www.kroll.com/en/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['incident response', 'forensics', 'cyber risk', 'mdr'],
  },
  {
    id: 'optiv',
    vendor: 'Optiv',
    url: 'https://www.optiv.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['mssp', 'security advisory', 'cyber program', 'managed security'],
  },

  // ── OT / ICS / IoT Security ───────────────────────────────────────────────
  {
    id: 'claroty',
    vendor: 'Claroty',
    url: 'https://claroty.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['ot security', 'ics', 'iot security', 'critical infrastructure'],
  },
  {
    id: 'nozomi-networks',
    vendor: 'Nozomi Networks',
    url: 'https://www.nozominetworks.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['ot security', 'ics', 'iot security', 'operational technology'],
  },
  {
    id: 'dragos',
    vendor: 'Dragos',
    url: 'https://www.dragos.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['ics security', 'ot security', 'critical infrastructure', 'threat intelligence'],
  },
  {
    id: 'armis',
    vendor: 'Armis',
    url: 'https://www.armis.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['iot security', 'asset intelligence', 'ot security', 'healthcare security'],
  },
  {
    id: 'forescout',
    vendor: 'Forescout',
    url: 'https://www.forescout.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['iot security', 'ot security', 'network access control', 'asset discovery'],
  },
  {
    id: 'txone-networks',
    vendor: 'TXOne Networks',
    url: 'https://www.txone.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['ot security', 'ics security', 'industrial cybersecurity', 'endpoint'],
  },
  {
    id: 'asimily',
    vendor: 'Asimily',
    url: 'https://asimily.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['iot security', 'medical device security', 'healthcare security', 'risk management'],
  },
  {
    id: 'medigate',
    vendor: 'Medigate (Claroty)',
    url: 'https://claroty.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['healthcare iot', 'medical device security', 'biomed security', 'ot security'],
  },
  {
    id: 'cylera',
    vendor: 'Cylera',
    url: 'https://www.cylera.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['healthcare iot', 'medical device security', 'ot security', 'asset management'],
  },
  {
    id: 'ordr',
    vendor: 'Ordr',
    url: 'https://ordr.net/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['iot security', 'device intelligence', 'network security', 'asset discovery'],
  },
  {
    id: 'sternum',
    vendor: 'Sternum',
    url: 'https://sternumiot.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['iot security', 'firmware security', 'embedded security', 'runtime protection'],
  },
  {
    id: 'honeywell-cyber',
    vendor: 'Honeywell Cyber Security',
    url: 'https://www.honeywell.com/us/en/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['ot security', 'ics security', 'industrial cybersecurity', 'critical infrastructure'],
  },

  // ── PKI / Encryption / HSM ────────────────────────────────────────────────
  {
    id: 'digicert',
    vendor: 'DigiCert',
    url: 'https://www.digicert.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['pki', 'ssl/tls', 'digital certificates', 'iam'],
  },
  {
    id: 'sectigo',
    vendor: 'Sectigo',
    url: 'https://www.sectigo.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['pki', 'ssl/tls', 'digital certificates', 'iot security'],
  },
  {
    id: 'venafi',
    vendor: 'Venafi (CyberArk)',
    url: 'https://venafi.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['machine identity', 'pki', 'certificate management', 'code signing'],
  },
  {
    id: 'keyfactor',
    vendor: 'Keyfactor',
    url: 'https://www.keyfactor.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['pki', 'machine identity', 'certificate management', 'iot security'],
  },
  {
    id: 'entrust-nshield',
    vendor: 'Entrust nShield',
    url: 'https://www.entrust.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['hsm', 'encryption', 'key management', 'pki'],
  },
  {
    id: 'utimaco',
    vendor: 'Utimaco',
    url: 'https://utimaco.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['hsm', 'encryption', 'key management', 'compliance'],
  },
  {
    id: 'securosys',
    vendor: 'Securosys',
    url: 'https://www.securosys.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['hsm', 'key management', 'pki', 'encryption'],
  },
  {
    id: 'appviewx',
    vendor: 'AppViewX',
    url: 'https://www.appviewx.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['machine identity', 'pki automation', 'certificate management', 'zero trust'],
  },

  // ── Insider Threat / UEBA ─────────────────────────────────────────────────
  {
    id: 'dtex-systems',
    vendor: 'DTEX Systems',
    url: 'https://dtexsystems.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['insider threat', 'ueba', 'workforce intelligence', 'behavior analytics'],
  },
  {
    id: 'teramind',
    vendor: 'Teramind',
    url: 'https://www.teramind.co/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['insider threat', 'employee monitoring', 'ueba', 'dlp'],
  },
  {
    id: 'observeit',
    vendor: 'Proofpoint ObserveIT',
    url: 'https://www.proofpoint.com/us/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['insider threat', 'ueba', 'user behavior', 'dlp'],
  },
  {
    id: 'forcepoint-insider',
    vendor: 'Forcepoint Insider Threat',
    url: 'https://www.forcepoint.com/company/events',
    defaultCategories: ['Cybersecurity', 'Data'],
    tags: ['insider threat', 'ueba', 'behavior analytics', 'dlp'],
  },

  // ── Bug Bounty / Penetration Testing ──────────────────────────────────────
  {
    id: 'hackerone',
    vendor: 'HackerOne',
    url: 'https://www.hackerone.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['bug bounty', 'penetration testing', 'vulnerability disclosure', 'ethical hacking'],
  },
  {
    id: 'bugcrowd',
    vendor: 'Bugcrowd',
    url: 'https://www.bugcrowd.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['bug bounty', 'penetration testing', 'crowdsourced security', 'vulnerability'],
  },
  {
    id: 'intigriti',
    vendor: 'Intigriti',
    url: 'https://www.intigriti.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['bug bounty', 'ethical hacking', 'vulnerability disclosure', 'pentesting'],
  },
  {
    id: 'yeswehack',
    vendor: 'YesWeHack',
    url: 'https://www.yeswehack.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['bug bounty', 'ethical hacking', 'vulnerability disclosure', 'pentesting'],
  },
  {
    id: 'cobalt',
    vendor: 'Cobalt',
    url: 'https://cobalt.io/events',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['penetration testing', 'ptaas', 'appsec', 'bug bounty'],
  },
  {
    id: 'synack',
    vendor: 'Synack',
    url: 'https://www.synack.com/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['penetration testing', 'red team', 'crowdsourced security', 'vulnerability'],
  },
  {
    id: 'ncc-group',
    vendor: 'NCC Group',
    url: 'https://www.nccgroup.com/us/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['penetration testing', 'security research', 'consulting', 'red team'],
  },
  {
    id: 'bishop-fox',
    vendor: 'Bishop Fox',
    url: 'https://bishopfox.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['penetration testing', 'red team', 'attack surface', 'offensive security'],
  },

  // ── Research / Non-profits / Government ───────────────────────────────────
  {
    id: 'mitre-attack',
    vendor: 'MITRE',
    url: 'https://attack.mitre.org/resources/attackcon/',
    defaultCategories: ['Cybersecurity'],
    tags: ['threat intelligence', 'att&ck', 'research', 'framework'],
  },
  {
    id: 'first',
    vendor: 'FIRST.org',
    url: 'https://www.first.org/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['incident response', 'csirt', 'vulnerability coordination', 'research'],
  },
  {
    id: 'cisa',
    vendor: 'CISA',
    url: 'https://www.cisa.gov/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['critical infrastructure', 'government', 'cybersecurity policy', 'resilience'],
  },
  {
    id: 'isaca',
    vendor: 'ISACA',
    url: 'https://www.isaca.org/training-and-events/conferences',
    defaultCategories: ['Cybersecurity'],
    tags: ['grc', 'audit', 'it governance', 'certification'],
  },
  {
    id: 'isc2',
    vendor: '(ISC)²',
    url: 'https://www.isc2.org/Events',
    defaultCategories: ['Cybersecurity'],
    tags: ['certification', 'cissp', 'training', 'professional development'],
  },
  {
    id: 'issa',
    vendor: 'ISSA',
    url: 'https://www.issa.org/events/',
    defaultCategories: ['Cybersecurity'],
    tags: ['security professionals', 'community', 'networking', 'education'],
  },
  {
    id: 'csa',
    vendor: 'Cloud Security Alliance',
    url: 'https://cloudsecurityalliance.org/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['cloud security', 'research', 'certification', 'best practices'],
  },
  {
    id: 'owasp',
    vendor: 'OWASP',
    url: 'https://owasp.org/events/',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['web security', 'appsec', 'open source', 'community'],
  },
  {
    id: 'enisa',
    vendor: 'ENISA',
    url: 'https://www.enisa.europa.eu/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['eu cybersecurity', 'policy', 'standards', 'research'],
  },
  {
    id: 'ncsc',
    vendor: 'NCSC',
    url: 'https://www.ncsc.gov.uk/section/about-ncsc/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['uk cybersecurity', 'government', 'cyber resilience', 'standards'],
  },

  // ── Security Conferences ──────────────────────────────────────────────────
  {
    id: 'rsaconference',
    vendor: 'RSA Conference',
    url: 'https://www.rsaconference.com/events',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'cybersecurity', 'networking', 'exhibition'],
  },
  {
    id: 'blackhat',
    vendor: 'Black Hat',
    url: 'https://www.blackhat.com/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'security research', 'briefings', 'training'],
  },
  {
    id: 'defcon',
    vendor: 'DEF CON',
    url: 'https://defcon.org/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'hacking', 'ctf', 'security research'],
  },
  {
    id: 'infosecurity-europe',
    vendor: 'Infosecurity Europe',
    url: 'https://www.infosecurityeurope.com/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'europe', 'exhibition', 'networking'],
  },
  {
    id: 'gartner-security',
    vendor: 'Gartner Security & Risk',
    url: 'https://www.gartner.com/en/conferences/hub/security-conferences',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'analyst', 'strategy', 'risk management'],
  },
  {
    id: 'identiverse',
    vendor: 'Identiverse',
    url: 'https://identiverse.com/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'identity', 'iam', 'access management'],
  },
  {
    id: 'sector',
    vendor: 'SecTor',
    url: 'https://www.sector.ca/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'canada', 'security research', 'networking'],
  },
  {
    id: 'nullcon',
    vendor: 'Nullcon',
    url: 'https://nullcon.net/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'security research', 'india', 'hacking'],
  },
  {
    id: 'cansecwest',
    vendor: 'CanSecWest',
    url: 'https://cansecwest.com/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'security research', 'canada', 'pwn2own'],
  },
  {
    id: 'hitcon',
    vendor: 'HITCON',
    url: 'https://hitcon.org/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'taiwan', 'security research', 'ctf'],
  },
  {
    id: 'hitb',
    vendor: 'Hack In The Box (HITB)',
    url: 'https://conference.hitb.org/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'security research', 'hacking', 'asia'],
  },
  {
    id: 'cyberuk',
    vendor: 'CyberUK (NCSC)',
    url: 'https://www.ncsc.gov.uk/cyberuk',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'uk government', 'cyber resilience', 'policy'],
  },
  {
    id: 'govware',
    vendor: 'GovWare',
    url: 'https://www.govware.sg/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'asia', 'government security', 'singapore'],
  },
  {
    id: 'hacklu',
    vendor: 'Hack.lu',
    url: 'https://hack.lu/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'europe', 'security research', 'luxembourg'],
  },
  {
    id: 'hacktivity',
    vendor: 'Hacktivity',
    url: 'https://hacktivity.com/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'europe', 'security research', 'hungary'],
  },
  {
    id: 'cloudsec',
    vendor: 'CloudSec',
    url: 'https://cloudsec.com/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['conference', 'cloud security', 'devsecops', 'networking'],
  },
  {
    id: 'cybersec-europe',
    vendor: 'Cybersec Europe',
    url: 'https://www.cybersec.be/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'europe', 'exhibition', 'networking'],
  },
  {
    id: 's4-ics',
    vendor: 'S4 (ICS Security)',
    url: 'https://s4xevents.com/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'ics security', 'ot security', 'scada'],
  },
  {
    id: 'shmoocon',
    vendor: 'ShmooCon',
    url: 'https://www.shmoocon.org/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'hacking', 'security research', 'washington dc'],
  },
  {
    id: 'bsides',
    vendor: 'BSides Security',
    url: 'https://www.securitybsides.com/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'community', 'grassroots', 'security research'],
  },
  {
    id: 'usenix-security',
    vendor: 'USENIX Security',
    url: 'https://www.usenix.org/conferences',
    defaultCategories: ['Cybersecurity'],
    tags: ['academic conference', 'security research', 'systems security', 'privacy'],
  },
  {
    id: 'ieee-security',
    vendor: 'IEEE Security & Privacy',
    url: 'https://www.ieee-security.org/TC/SP2025/',
    defaultCategories: ['Cybersecurity'],
    tags: ['academic conference', 'security research', 'privacy', 'ieee'],
  },
  {
    id: 'acm-ccs',
    vendor: 'ACM CCS',
    url: 'https://www.sigsac.org/ccs/',
    defaultCategories: ['Cybersecurity'],
    tags: ['academic conference', 'security research', 'cryptography', 'acm'],
  },
  {
    id: 'virus-bulletin',
    vendor: 'Virus Bulletin',
    url: 'https://www.virusbulletin.com/conference/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'malware', 'threat intelligence', 'antivirus'],
  },
  {
    id: 'first-conference',
    vendor: 'FIRST Conference',
    url: 'https://www.first.org/conference/',
    defaultCategories: ['Cybersecurity'],
    tags: ['conference', 'incident response', 'csirt', 'vulnerability'],
  },

];
