module.exports = [

  // ── Data Platforms ────────────────────────────────────────────────────────
  {
    id: 'snowflake',
    vendor: 'Snowflake',
    url: 'https://www.snowflake.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['snowflake', 'data cloud', 'summit'],
  },
  {
    id: 'confluent',
    vendor: 'Confluent',
    url: 'https://www.confluent.io/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['confluent', 'kafka', 'kafka summit', 'current'],
  },
  {
    id: 'mongodb',
    vendor: 'MongoDB',
    url: 'https://www.mongodb.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['mongodb', '.live', 'nosql'],
  },
  {
    id: 'elastic',
    vendor: 'Elastic',
    url: 'https://www.elastic.co/events/',
    defaultCategories: ['Data', 'Cybersecurity'],
    tags: ['elastic', 'elasticsearch', 'elasticon'],
  },
  {
    id: 'dbt-labs',
    vendor: 'dbt Labs',
    url: 'https://coalesce.getdbt.com/',
    defaultCategories: ['Data'],
    tags: ['dbt', 'coalesce', 'data transformation'],
  },
  {
    id: 'fivetran',
    vendor: 'Fivetran',
    url: 'https://fivetran.com/events',
    defaultCategories: ['Data'],
    tags: ['fivetran', 'data pipeline', 'etl'],
  },
  {
    id: 'informatica',
    vendor: 'Informatica',
    url: 'https://www.informatica.com/events.html',
    defaultCategories: ['Data'],
    tags: ['informatica', 'data integration', 'mdm'],
  },
  {
    id: 'cloudera',
    vendor: 'Cloudera',
    url: 'https://www.cloudera.com/events.html',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['cloudera', 'evolve', 'hadoop', 'data lakehouse'],
  },
  {
    id: 'starburst',
    vendor: 'Starburst',
    url: 'https://www.starburst.io/events/',
    defaultCategories: ['Data'],
    tags: ['starburst', 'trino', 'data mesh'],
  },
  {
    id: 'airbyte',
    vendor: 'Airbyte',
    url: 'https://airbyte.com/events',
    defaultCategories: ['Data'],
    tags: ['airbyte', 'data pipeline', 'etl'],
  },
  {
    id: 'talend',
    vendor: 'Talend',
    url: 'https://www.talend.com/resources/events/',
    defaultCategories: ['Data'],
    tags: ['talend', 'data integration'],
  },
  {
    id: 'teradata',
    vendor: 'Teradata',
    url: 'https://www.teradata.com/events',
    defaultCategories: ['Data'],
    tags: ['teradata', 'data warehouse', 'partners'],
  },
  {
    id: 'dremio',
    vendor: 'Dremio',
    url: 'https://www.dremio.com/resources/events/',
    defaultCategories: ['Data'],
    tags: ['dremio', 'data lakehouse', 'apache arrow'],
  },
  {
    id: 'apache-foundation',
    vendor: 'Apache Software Foundation',
    url: 'https://www.apache.org/events/current-event.html',
    defaultCategories: ['Data', 'Developer'],
    tags: ['apache', 'open source', 'apachecon'],
  },

  // ── Cloud Data Warehouses / Lakehouses ────────────────────────────────────
  {
    id: 'databricks',
    vendor: 'Databricks',
    url: 'https://www.databricks.com/events',
    defaultCategories: ['Data', 'AI', 'Cloud'],
    tags: ['databricks', 'data ai summit', 'lakehouse', 'spark'],
  },
  {
    id: 'google-bigquery',
    vendor: 'Google BigQuery',
    url: 'https://cloud.google.com/events',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['bigquery', 'google cloud', 'data warehouse'],
  },
  {
    id: 'amazon-redshift',
    vendor: 'Amazon Redshift',
    url: 'https://aws.amazon.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['redshift', 'aws', 'data warehouse', 're:invent'],
  },
  {
    id: 'azure-synapse',
    vendor: 'Azure Synapse Analytics',
    url: 'https://azure.microsoft.com/en-us/community/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['synapse', 'microsoft', 'azure', 'data lakehouse'],
  },
  {
    id: 'singlestore',
    vendor: 'SingleStore',
    url: 'https://www.singlestore.com/events/',
    defaultCategories: ['Data'],
    tags: ['singlestore', 'real-time analytics', 'database'],
  },
  {
    id: 'yellowbrick',
    vendor: 'Yellowbrick Data',
    url: 'https://www.yellowbrick.com/resources/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['yellowbrick', 'data warehouse', 'hybrid cloud'],
  },
  {
    id: 'firebolt',
    vendor: 'Firebolt',
    url: 'https://www.firebolt.io/events',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['firebolt', 'cloud data warehouse', 'analytics'],
  },
  {
    id: 'motherduck',
    vendor: 'MotherDuck',
    url: 'https://motherduck.com/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['motherduck', 'duckdb', 'serverless analytics'],
  },
  {
    id: 'starrocks',
    vendor: 'StarRocks',
    url: 'https://www.starrocks.io/events',
    defaultCategories: ['Data'],
    tags: ['starrocks', 'real-time analytics', 'lakehouse'],
  },
  {
    id: 'apache-iceberg',
    vendor: 'Apache Iceberg',
    url: 'https://iceberg.apache.org/community/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['iceberg', 'apache', 'open table format', 'lakehouse'],
  },

  // ── Relational Databases ──────────────────────────────────────────────────
  {
    id: 'postgresql',
    vendor: 'PostgreSQL',
    url: 'https://www.postgresql.org/about/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['postgresql', 'pgconf', 'open source', 'rdbms'],
  },
  {
    id: 'mariadb',
    vendor: 'MariaDB Foundation',
    url: 'https://mariadb.org/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['mariadb', 'open source', 'mysql', 'rdbms'],
  },
  {
    id: 'mssql',
    vendor: 'Microsoft SQL Server',
    url: 'https://azure.microsoft.com/en-us/community/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['sql server', 'microsoft', 'azure', 'rdbms'],
  },
  {
    id: 'enterprisedb',
    vendor: 'EnterpriseDB (EDB)',
    url: 'https://www.enterprisedb.com/events',
    defaultCategories: ['Data'],
    tags: ['edb', 'postgres', 'enterprise database'],
  },
  {
    id: 'cockroachdb',
    vendor: 'CockroachDB',
    url: 'https://www.cockroachlabs.com/events/',
    defaultCategories: ['Data', 'Cloud', 'Developer'],
    tags: ['cockroachdb', 'distributed sql', 'cloud native'],
  },
  {
    id: 'planetscale',
    vendor: 'PlanetScale',
    url: 'https://planetscale.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['planetscale', 'mysql', 'serverless database'],
  },
  {
    id: 'neon',
    vendor: 'Neon',
    url: 'https://neon.tech/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['neon', 'serverless postgres', 'cloud database'],
  },
  {
    id: 'supabase',
    vendor: 'Supabase',
    url: 'https://supabase.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['supabase', 'postgres', 'open source', 'backend'],
  },
  {
    id: 'timescaledb',
    vendor: 'TimescaleDB',
    url: 'https://www.timescale.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['timescale', 'time series', 'postgresql'],
  },
  {
    id: 'percona',
    vendor: 'Percona',
    url: 'https://www.percona.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['percona', 'percona live', 'mysql', 'postgresql'],
  },
  {
    id: 'citus-data',
    vendor: 'Citus Data (Microsoft)',
    url: 'https://azure.microsoft.com/en-us/community/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['citus', 'postgresql', 'distributed database', 'microsoft'],
  },

  // ── NoSQL / Document / Key-Value Databases ────────────────────────────────
  {
    id: 'datastax',
    vendor: 'DataStax',
    url: 'https://www.datastax.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['datastax', 'cassandra', 'nosql', 'astra'],
  },
  {
    id: 'redis',
    vendor: 'Redis',
    url: 'https://redis.io/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['redis', 'redis days', 'in-memory', 'cache'],
  },
  {
    id: 'couchbase',
    vendor: 'Couchbase',
    url: 'https://www.couchbase.com/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['couchbase', 'nosql', 'connect'],
  },
  {
    id: 'arangodb',
    vendor: 'ArangoDB',
    url: 'https://www.arangodb.com/community/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['arangodb', 'multi-model', 'nosql', 'graph'],
  },
  {
    id: 'ravendb',
    vendor: 'RavenDB',
    url: 'https://ravendb.net/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['ravendb', 'nosql', 'document database'],
  },
  {
    id: 'aerospike',
    vendor: 'Aerospike',
    url: 'https://aerospike.com/events/',
    defaultCategories: ['Data'],
    tags: ['aerospike', 'real-time', 'key-value', 'nosql'],
  },
  {
    id: 'fauna',
    vendor: 'Fauna',
    url: 'https://fauna.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['fauna', 'serverless database', 'document'],
  },
  {
    id: 'apache-cassandra',
    vendor: 'Apache Cassandra',
    url: 'https://cassandra.apache.org/_/events.html',
    defaultCategories: ['Data', 'Developer'],
    tags: ['cassandra', 'apache', 'nosql', 'distributed'],
  },

  // ── Graph Databases ───────────────────────────────────────────────────────
  {
    id: 'neo4j',
    vendor: 'Neo4j',
    url: 'https://neo4j.com/events/',
    defaultCategories: ['Data', 'AI'],
    tags: ['neo4j', 'nodes', 'graph database', 'graphql'],
  },
  {
    id: 'tigergraph',
    vendor: 'TigerGraph',
    url: 'https://www.tigergraph.com/events/',
    defaultCategories: ['Data', 'AI'],
    tags: ['tigergraph', 'graph analytics', 'graph database'],
  },
  {
    id: 'amazon-neptune',
    vendor: 'Amazon Neptune',
    url: 'https://aws.amazon.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['neptune', 'aws', 'graph database', 'knowledge graph'],
  },
  {
    id: 'azure-cosmos-db',
    vendor: 'Azure Cosmos DB',
    url: 'https://azure.microsoft.com/en-us/community/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['cosmos db', 'microsoft', 'azure', 'multi-model'],
  },
  {
    id: 'memgraph',
    vendor: 'Memgraph',
    url: 'https://memgraph.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['memgraph', 'graph database', 'real-time', 'streaming'],
  },
  {
    id: 'dgraph',
    vendor: 'Dgraph',
    url: 'https://dgraph.io/community',
    defaultCategories: ['Data', 'Developer'],
    tags: ['dgraph', 'graph database', 'graphql', 'open source'],
  },
  {
    id: 'janusgraph',
    vendor: 'JanusGraph',
    url: 'https://janusgraph.org/changelog/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['janusgraph', 'open source', 'graph database', 'distributed'],
  },
  {
    id: 'orientdb',
    vendor: 'OrientDB',
    url: 'https://orientdb.org/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['orientdb', 'multi-model', 'graph database', 'nosql'],
  },

  // ── Time Series / IoT Databases ───────────────────────────────────────────
  {
    id: 'influxdata',
    vendor: 'InfluxData',
    url: 'https://www.influxdata.com/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['influxdb', 'time series', 'iot', 'influxdays'],
  },
  {
    id: 'questdb',
    vendor: 'QuestDB',
    url: 'https://questdb.io/community/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['questdb', 'time series', 'open source', 'analytics'],
  },
  {
    id: 'tdengine',
    vendor: 'TDengine',
    url: 'https://tdengine.com/events/',
    defaultCategories: ['Data'],
    tags: ['tdengine', 'time series', 'iot', 'big data'],
  },
  {
    id: 'prometheus',
    vendor: 'Prometheus (CNCF)',
    url: 'https://prometheus.io/community/',
    defaultCategories: ['Data', 'Developer', 'Cloud'],
    tags: ['prometheus', 'cncf', 'metrics', 'monitoring'],
  },
  {
    id: 'victoriametrics',
    vendor: 'VictoriaMetrics',
    url: 'https://victoriametrics.com/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['victoriametrics', 'time series', 'metrics', 'monitoring'],
  },
  {
    id: 'amazon-timestream',
    vendor: 'Amazon Timestream',
    url: 'https://aws.amazon.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['timestream', 'aws', 'time series', 'iot'],
  },

  // ── Search / Vector Databases ─────────────────────────────────────────────
  {
    id: 'algolia',
    vendor: 'Algolia',
    url: 'https://www.algolia.com/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['algolia', 'search', 'search api'],
  },
  {
    id: 'pinecone',
    vendor: 'Pinecone',
    url: 'https://www.pinecone.io/events/',
    defaultCategories: ['Data', 'AI'],
    tags: ['pinecone', 'vector database', 'ai', 'embeddings'],
  },
  {
    id: 'weaviate',
    vendor: 'Weaviate',
    url: 'https://weaviate.io/community/events',
    defaultCategories: ['Data', 'AI'],
    tags: ['weaviate', 'vector database', 'ai', 'semantic search'],
  },
  {
    id: 'qdrant',
    vendor: 'Qdrant',
    url: 'https://qdrant.tech/events/',
    defaultCategories: ['Data', 'AI'],
    tags: ['qdrant', 'vector database', 'ai', 'similarity search'],
  },
  {
    id: 'opensearch',
    vendor: 'OpenSearch',
    url: 'https://opensearch.org/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['opensearch', 'search', 'open source', 'aws'],
  },
  {
    id: 'vespa',
    vendor: 'Vespa',
    url: 'https://vespa.ai/events',
    defaultCategories: ['Data', 'AI', 'Developer'],
    tags: ['vespa', 'search', 'vector database', 'ai'],
  },
  {
    id: 'apache-solr',
    vendor: 'Apache Solr',
    url: 'https://solr.apache.org/community.html',
    defaultCategories: ['Data', 'Developer'],
    tags: ['solr', 'apache', 'open source', 'search'],
  },
  {
    id: 'typesense',
    vendor: 'Typesense',
    url: 'https://typesense.org/community/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['typesense', 'open source', 'search', 'developer'],
  },
  {
    id: 'meilisearch',
    vendor: 'Meilisearch',
    url: 'https://www.meilisearch.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['meilisearch', 'open source', 'search', 'developer'],
  },

  // ── Data Integration / ETL / ELT ──────────────────────────────────────────
  {
    id: 'mulesoft',
    vendor: 'MuleSoft (Salesforce)',
    url: 'https://www.mulesoft.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['mulesoft', 'integration', 'api', 'salesforce'],
  },
  {
    id: 'boomi',
    vendor: 'Boomi',
    url: 'https://boomi.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['boomi', 'integration', 'ipaas', 'data integration'],
  },
  {
    id: 'snaplogic',
    vendor: 'SnapLogic',
    url: 'https://www.snaplogic.com/events',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['snaplogic', 'integration', 'ipaas', 'pipeline'],
  },
  {
    id: 'jitterbit',
    vendor: 'Jitterbit',
    url: 'https://www.jitterbit.com/events/',
    defaultCategories: ['Data'],
    tags: ['jitterbit', 'integration', 'api', 'etl'],
  },
  {
    id: 'matillion',
    vendor: 'Matillion',
    url: 'https://www.matillion.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['matillion', 'elt', 'data integration', 'cloud'],
  },
  {
    id: 'aws-glue',
    vendor: 'AWS Glue',
    url: 'https://aws.amazon.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['aws glue', 'etl', 'aws', 'serverless'],
  },
  {
    id: 'hevo-data',
    vendor: 'Hevo Data',
    url: 'https://hevodata.com/events/',
    defaultCategories: ['Data'],
    tags: ['hevo', 'data pipeline', 'etl', 'no-code'],
  },

  // ── Streaming / Event Processing ──────────────────────────────────────────
  {
    id: 'apache-flink',
    vendor: 'Apache Flink',
    url: 'https://flink.apache.org/community.html',
    defaultCategories: ['Data', 'Developer'],
    tags: ['apache flink', 'streaming', 'event processing', 'real-time'],
  },
  {
    id: 'redpanda',
    vendor: 'Redpanda',
    url: 'https://redpanda.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['redpanda', 'kafka compatible', 'streaming', 'messaging'],
  },
  {
    id: 'streamnative',
    vendor: 'StreamNative (Apache Pulsar)',
    url: 'https://streamnative.io/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['streamnative', 'pulsar', 'messaging', 'streaming'],
  },
  {
    id: 'apache-nifi',
    vendor: 'Apache NiFi',
    url: 'https://nifi.apache.org/community.html',
    defaultCategories: ['Data', 'Developer'],
    tags: ['nifi', 'apache', 'data flow', 'streaming'],
  },
  {
    id: 'hazelcast',
    vendor: 'Hazelcast',
    url: 'https://hazelcast.com/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['hazelcast', 'in-memory', 'streaming', 'distributed'],
  },
  {
    id: 'striim',
    vendor: 'Striim',
    url: 'https://www.striim.com/events/',
    defaultCategories: ['Data'],
    tags: ['striim', 'streaming integration', 'real-time', 'etl'],
  },
  {
    id: 'azure-event-hubs',
    vendor: 'Azure Event Hubs',
    url: 'https://azure.microsoft.com/en-us/community/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['event hubs', 'azure', 'microsoft', 'streaming'],
  },
  {
    id: 'apache-spark',
    vendor: 'Apache Spark',
    url: 'https://spark.apache.org/community.html',
    defaultCategories: ['Data', 'Developer'],
    tags: ['apache spark', 'big data', 'streaming', 'batch processing'],
  },

  // ── Data Quality / Observability ──────────────────────────────────────────
  {
    id: 'great-expectations',
    vendor: 'Great Expectations',
    url: 'https://greatexpectations.io/community/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['great expectations', 'data quality', 'open source', 'testing'],
  },
  {
    id: 'monte-carlo',
    vendor: 'Monte Carlo Data',
    url: 'https://www.montecarlodata.com/events/',
    defaultCategories: ['Data'],
    tags: ['monte carlo', 'data observability', 'data quality'],
  },
  {
    id: 'bigeye',
    vendor: 'Bigeye',
    url: 'https://www.bigeye.com/events',
    defaultCategories: ['Data'],
    tags: ['bigeye', 'data observability', 'data quality', 'monitoring'],
  },
  {
    id: 'soda',
    vendor: 'Soda',
    url: 'https://www.soda.io/events',
    defaultCategories: ['Data'],
    tags: ['soda', 'data quality', 'data testing', 'pipeline'],
  },
  {
    id: 'acceldata',
    vendor: 'Acceldata',
    url: 'https://www.acceldata.io/events',
    defaultCategories: ['Data'],
    tags: ['acceldata', 'data observability', 'data reliability'],
  },
  {
    id: 'anomalo',
    vendor: 'Anomalo',
    url: 'https://www.anomalo.com/events',
    defaultCategories: ['Data'],
    tags: ['anomalo', 'data quality', 'anomaly detection', 'monitoring'],
  },
  {
    id: 'datafold',
    vendor: 'Datafold',
    url: 'https://www.datafold.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['datafold', 'data diff', 'data quality', 'testing'],
  },
  {
    id: 'precisely',
    vendor: 'Precisely',
    url: 'https://www.precisely.com/events',
    defaultCategories: ['Data'],
    tags: ['precisely', 'data quality', 'data integrity', 'enrichment'],
  },
  {
    id: 'ataccama',
    vendor: 'Ataccama',
    url: 'https://www.ataccama.com/events',
    defaultCategories: ['Data'],
    tags: ['ataccama', 'data quality', 'data governance', 'mdm'],
  },

  // ── Data Catalog / Governance / Metadata ──────────────────────────────────
  {
    id: 'alation',
    vendor: 'Alation',
    url: 'https://www.alation.com/events/',
    defaultCategories: ['Data'],
    tags: ['alation', 'data catalog', 'data governance', 'metadata'],
  },
  {
    id: 'collibra',
    vendor: 'Collibra',
    url: 'https://www.collibra.com/us/en/events',
    defaultCategories: ['Data'],
    tags: ['collibra', 'data governance', 'data catalog', 'data quality'],
  },
  {
    id: 'atlan',
    vendor: 'Atlan',
    url: 'https://atlan.com/events/',
    defaultCategories: ['Data'],
    tags: ['atlan', 'data catalog', 'metadata management', 'collaboration'],
  },
  {
    id: 'datahub',
    vendor: 'DataHub (Acryl Data)',
    url: 'https://datahubproject.io/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['datahub', 'metadata', 'data catalog', 'open source'],
  },
  {
    id: 'amundsen',
    vendor: 'Amundsen',
    url: 'https://www.amundsen.io/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['amundsen', 'data catalog', 'metadata', 'open source'],
  },
  {
    id: 'apache-atlas',
    vendor: 'Apache Atlas',
    url: 'https://atlas.apache.org/#/Community',
    defaultCategories: ['Data', 'Developer'],
    tags: ['apache atlas', 'metadata', 'data governance', 'open source'],
  },
  {
    id: 'select-star',
    vendor: 'Select Star',
    url: 'https://www.selectstar.com/events',
    defaultCategories: ['Data'],
    tags: ['select star', 'data catalog', 'data discovery', 'lineage'],
  },
  {
    id: 'secoda',
    vendor: 'Secoda',
    url: 'https://www.secoda.co/events',
    defaultCategories: ['Data'],
    tags: ['secoda', 'data catalog', 'data discovery', 'metadata'],
  },
  {
    id: 'metaphor-data',
    vendor: 'Metaphor Data',
    url: 'https://metaphor.io/events',
    defaultCategories: ['Data'],
    tags: ['metaphor', 'data catalog', 'metadata', 'data governance'],
  },

  // ── DataOps / Pipeline Orchestration ─────────────────────────────────────
  {
    id: 'astronomer',
    vendor: 'Astronomer (Apache Airflow)',
    url: 'https://www.astronomer.io/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['astronomer', 'apache airflow', 'dataops', 'orchestration'],
  },
  {
    id: 'prefect',
    vendor: 'Prefect',
    url: 'https://www.prefect.io/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['prefect', 'workflow orchestration', 'dataops', 'pipeline'],
  },
  {
    id: 'dagster',
    vendor: 'Dagster',
    url: 'https://dagster.io/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['dagster', 'data orchestration', 'dataops', 'pipeline'],
  },
  {
    id: 'mage-ai',
    vendor: 'Mage AI',
    url: 'https://www.mage.ai/events',
    defaultCategories: ['Data', 'AI', 'Developer'],
    tags: ['mage', 'data pipeline', 'orchestration', 'open source'],
  },
  {
    id: 'ascend-io',
    vendor: 'Ascend.io',
    url: 'https://www.ascend.io/resources/events/',
    defaultCategories: ['Data'],
    tags: ['ascend', 'data automation', 'dataops', 'pipeline'],
  },
  {
    id: 'portable',
    vendor: 'Portable',
    url: 'https://portable.io/events',
    defaultCategories: ['Data'],
    tags: ['portable', 'data pipeline', 'etl', 'connectors'],
  },
  {
    id: 'orchestra',
    vendor: 'Orchestra',
    url: 'https://www.getorchestra.io/events',
    defaultCategories: ['Data'],
    tags: ['orchestra', 'data orchestration', 'dataops', 'pipeline'],
  },

  // ── Observability / Monitoring ────────────────────────────────────────────
  {
    id: 'grafana',
    vendor: 'Grafana Labs',
    url: 'https://grafana.com/events/',
    defaultCategories: ['Data', 'Cloud', 'Developer'],
    tags: ['grafana', 'observability', 'grafanacon'],
  },
  {
    id: 'datadog',
    vendor: 'Datadog',
    url: 'https://www.datadoghq.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['datadog', 'dash', 'observability'],
  },
  {
    id: 'newrelic',
    vendor: 'New Relic',
    url: 'https://newrelic.com/events',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['new relic', 'futurestack', 'observability'],
  },
  {
    id: 'dynatrace',
    vendor: 'Dynatrace',
    url: 'https://www.dynatrace.com/perform/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['dynatrace', 'perform', 'apm'],
  },
  {
    id: 'splunk-conf',
    vendor: 'Splunk',
    url: 'https://conf.splunk.com/',
    defaultCategories: ['Data', 'Cybersecurity'],
    tags: ['splunk', '.conf', 'siem', 'observability'],
  },
  {
    id: 'sumologic',
    vendor: 'Sumo Logic',
    url: 'https://www.sumologic.com/events/',
    defaultCategories: ['Data', 'Cybersecurity'],
    tags: ['sumo logic', 'illuminate', 'log management'],
  },
  {
    id: 'honeycomb',
    vendor: 'Honeycomb',
    url: 'https://www.honeycomb.io/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['honeycomb', 'observability'],
  },
  {
    id: 'appdynamics',
    vendor: 'AppDynamics (Cisco)',
    url: 'https://www.appdynamics.com/events',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['appdynamics', 'apm', 'cisco', 'observability'],
  },
  {
    id: 'opentelemetry',
    vendor: 'OpenTelemetry (CNCF)',
    url: 'https://opentelemetry.io/community/',
    defaultCategories: ['Data', 'Developer', 'Cloud'],
    tags: ['opentelemetry', 'otel', 'cncf', 'observability'],
  },
  {
    id: 'lightstep',
    vendor: 'Lightstep (ServiceNow)',
    url: 'https://lightstep.com/events',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['lightstep', 'distributed tracing', 'apm', 'observability'],
  },

  // ── Analytics / BI ────────────────────────────────────────────────────────
  {
    id: 'tableau',
    vendor: 'Tableau (Salesforce)',
    url: 'https://www.tableau.com/events',
    defaultCategories: ['Data'],
    tags: ['tableau', 'bi', 'data visualization'],
  },
  {
    id: 'looker',
    vendor: 'Looker (Google)',
    url: 'https://cloud.google.com/events',
    defaultCategories: ['Data'],
    tags: ['looker', 'bi', 'google'],
  },
  {
    id: 'thoughtspot',
    vendor: 'ThoughtSpot',
    url: 'https://www.thoughtspot.com/events',
    defaultCategories: ['Data'],
    tags: ['thoughtspot', 'analytics', 'beyond'],
  },
  {
    id: 'microstrategy',
    vendor: 'MicroStrategy',
    url: 'https://www.microstrategy.com/en/company/events',
    defaultCategories: ['Data'],
    tags: ['microstrategy', 'analytics', 'world'],
  },
  {
    id: 'power-bi',
    vendor: 'Microsoft Power BI',
    url: 'https://powerbi.microsoft.com/en-us/community/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['power bi', 'microsoft', 'bi', 'data visualization'],
  },
  {
    id: 'qlik',
    vendor: 'Qlik',
    url: 'https://www.qlik.com/us/events',
    defaultCategories: ['Data'],
    tags: ['qlik', 'bi', 'data analytics', 'qlikworld'],
  },
  {
    id: 'sisense',
    vendor: 'Sisense',
    url: 'https://www.sisense.com/events/',
    defaultCategories: ['Data'],
    tags: ['sisense', 'bi', 'embedded analytics'],
  },
  {
    id: 'domo',
    vendor: 'Domo',
    url: 'https://www.domo.com/domopalooza',
    defaultCategories: ['Data'],
    tags: ['domo', 'domopalooza', 'bi', 'cloud analytics'],
  },
  {
    id: 'tibco-spotfire',
    vendor: 'TIBCO Spotfire',
    url: 'https://www.tibco.com/events',
    defaultCategories: ['Data'],
    tags: ['tibco', 'spotfire', 'analytics', 'bi'],
  },
  {
    id: 'sap-analytics',
    vendor: 'SAP Analytics Cloud',
    url: 'https://events.sap.com/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['sap', 'analytics cloud', 'sapphire', 'bi'],
  },
  {
    id: 'ibm-cognos',
    vendor: 'IBM Cognos',
    url: 'https://www.ibm.com/events/',
    defaultCategories: ['Data'],
    tags: ['ibm', 'cognos', 'analytics', 'bi'],
  },
  {
    id: 'yellowfin-bi',
    vendor: 'Yellowfin BI',
    url: 'https://www.yellowfinbi.com/events',
    defaultCategories: ['Data'],
    tags: ['yellowfin', 'bi', 'embedded analytics', 'dashboard'],
  },
  {
    id: 'gooddata',
    vendor: 'GoodData',
    url: 'https://www.gooddata.com/events/',
    defaultCategories: ['Data'],
    tags: ['gooddata', 'analytics', 'embedded analytics', 'bi'],
  },

  // ── Data Science / Notebook Platforms ─────────────────────────────────────
  {
    id: 'jupyter',
    vendor: 'Jupyter (NumFOCUS)',
    url: 'https://numfocus.org/events',
    defaultCategories: ['Data', 'Developer', 'AI'],
    tags: ['jupyter', 'numfocus', 'notebook', 'data science'],
  },
  {
    id: 'anaconda',
    vendor: 'Anaconda',
    url: 'https://www.anaconda.com/events',
    defaultCategories: ['Data', 'AI'],
    tags: ['anaconda', 'python', 'data science', 'conda'],
  },
  {
    id: 'posit',
    vendor: 'Posit (RStudio)',
    url: 'https://posit.co/about/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['posit', 'rstudio', 'r', 'data science'],
  },
  {
    id: 'saturn-cloud',
    vendor: 'Saturn Cloud',
    url: 'https://saturncloud.io/events/',
    defaultCategories: ['Data', 'AI', 'Cloud'],
    tags: ['saturn cloud', 'gpu', 'data science', 'python'],
  },
  {
    id: 'deepnote',
    vendor: 'Deepnote',
    url: 'https://deepnote.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['deepnote', 'notebook', 'collaboration', 'data science'],
  },
  {
    id: 'observable',
    vendor: 'Observable',
    url: 'https://observablehq.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['observable', 'notebook', 'data visualization', 'javascript'],
  },
  {
    id: 'hex',
    vendor: 'Hex',
    url: 'https://hex.tech/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['hex', 'notebook', 'data analytics', 'collaboration'],
  },
  {
    id: 'paperspace',
    vendor: 'Paperspace (DigitalOcean)',
    url: 'https://www.paperspace.com/events',
    defaultCategories: ['Data', 'AI', 'Cloud'],
    tags: ['paperspace', 'gpu', 'ml', 'data science'],
  },

  // ── Cloud-native Data Platforms ───────────────────────────────────────────
  {
    id: 'palantir',
    vendor: 'Palantir',
    url: 'https://www.palantir.com/events/',
    defaultCategories: ['Data', 'AI'],
    tags: ['palantir', 'data platform', 'government', 'enterprise ai'],
  },
  {
    id: 'splice-machine',
    vendor: 'Splice Machine',
    url: 'https://splicemachine.com/events/',
    defaultCategories: ['Data', 'AI'],
    tags: ['splice machine', 'ml database', 'real-time ai', 'sql'],
  },
  {
    id: 'cazena',
    vendor: 'Cazena',
    url: 'https://cazena.com/events',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['cazena', 'cloud data platform', 'analytics', 'migration'],
  },

  // ── Data Sharing / Marketplace ────────────────────────────────────────────
  {
    id: 'aws-data-exchange',
    vendor: 'AWS Data Exchange',
    url: 'https://aws.amazon.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['aws data exchange', 'data marketplace', 'aws', 'data sharing'],
  },
  {
    id: 'narrative-io',
    vendor: 'Narrative I/O',
    url: 'https://www.narrative.io/events',
    defaultCategories: ['Data'],
    tags: ['narrative', 'data marketplace', 'data commerce', 'data sharing'],
  },
  {
    id: 'liveramp',
    vendor: 'LiveRamp',
    url: 'https://liveramp.com/events/',
    defaultCategories: ['Data'],
    tags: ['liveramp', 'data connectivity', 'data marketplace', 'identity'],
  },
  {
    id: 'dawex',
    vendor: 'Dawex',
    url: 'https://www.dawex.com/en/events/',
    defaultCategories: ['Data'],
    tags: ['dawex', 'data marketplace', 'data exchange', 'data sharing'],
  },

  // ── Data Conferences ──────────────────────────────────────────────────────
  {
    id: 'strata-data-ai',
    vendor: "Strata Data & AI (O'Reilly)",
    url: 'https://www.oreilly.com/conferences/',
    defaultCategories: ['Data', 'AI'],
    tags: ['strata', "o'reilly", 'data conference', 'ai'],
  },
  {
    id: 'cncf-kubecon-data',
    vendor: 'KubeCon + CloudNativeCon (CNCF)',
    url: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/',
    defaultCategories: ['Data', 'Cloud', 'Developer'],
    tags: ['kubecon', 'cncf', 'cloud native', 'kubernetes'],
  },
  {
    id: 'big-data-london',
    vendor: 'Big Data London',
    url: 'https://www.bigdataldn.com/',
    defaultCategories: ['Data'],
    tags: ['big data london', 'conference', 'data engineering', 'analytics'],
  },
  {
    id: 'data-council',
    vendor: 'Data Council',
    url: 'https://www.datacouncil.ai/talks',
    defaultCategories: ['Data', 'AI'],
    tags: ['data council', 'data engineering', 'conference', 'community'],
  },
  {
    id: 'dataengconf',
    vendor: 'DataEngConf',
    url: 'https://www.dataengconf.com/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['dataengconf', 'data engineering', 'conference', 'pipeline'],
  },
  {
    id: 'vldb',
    vendor: 'VLDB Conference',
    url: 'https://vldb.org/2025/',
    defaultCategories: ['Data'],
    tags: ['vldb', 'very large database', 'academic', 'research'],
  },
  {
    id: 'sigmod',
    vendor: 'SIGMOD',
    url: 'https://2025.sigmod.org/',
    defaultCategories: ['Data'],
    tags: ['sigmod', 'acm', 'database research', 'academic'],
  },
  {
    id: 'cidr',
    vendor: 'CIDR',
    url: 'https://www.cidrdb.org/',
    defaultCategories: ['Data'],
    tags: ['cidr', 'innovative database research', 'academic', 'systems'],
  },
  {
    id: 'qcon-data',
    vendor: 'QCon (Data Track)',
    url: 'https://qconferences.com/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['qcon', 'software architecture', 'data', 'developer'],
  },
  {
    id: 'data-innovation-summit',
    vendor: 'Data Innovation Summit',
    url: 'https://datainnovationsummit.com/',
    defaultCategories: ['Data', 'AI'],
    tags: ['data innovation', 'summit', 'big data', 'ai'],
  },
  {
    id: 'gartner-data-analytics',
    vendor: 'Gartner Data & Analytics Summit',
    url: 'https://www.gartner.com/en/conferences/na/data-analytics-us',
    defaultCategories: ['Data'],
    tags: ['gartner', 'data analytics', 'analyst summit', 'enterprise'],
  },
  {
    id: 'tdwi',
    vendor: 'TDWI',
    url: 'https://tdwi.org/Events/Home.aspx',
    defaultCategories: ['Data'],
    tags: ['tdwi', 'business intelligence', 'data management', 'conference'],
  },

];
