module.exports = [

  // ── Data Platforms ────────────────────────────────────────────────────────
  {
    id: 'snowflake',
    vendor: 'Snowflake',
    url: 'https://www.snowflake.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['snowflake', 'data cloud', 'summit'],
  },
  {
    id: 'confluent',
    vendor: 'Confluent',
    url: 'https://www.confluent.io/events/',
    defaultCategories: ['Data', 'Developer'],
    tags: ['confluent', 'kafka', 'kafka summit', 'current'],
  },
  {
    id: 'mongodb',
    vendor: 'MongoDB',
    url: 'https://www.mongodb.com/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['mongodb', '.live', 'nosql'],
  },
  {
    id: 'elastic',
    vendor: 'Elastic',
    url: 'https://www.elastic.co/events/',
    defaultCategories: ['Data', 'Cybersecurity'],
    tags: ['elastic', 'elasticsearch', 'elasticon'],
  },
  {
    id: 'dbt-labs',
    vendor: 'dbt Labs',
    url: 'https://coalesce.getdbt.com/',
    defaultCategories: ['Data'],
    tags: ['dbt', 'coalesce', 'data transformation'],
  },
  {
    id: 'fivetran',
    vendor: 'Fivetran',
    url: 'https://fivetran.com/events',
    defaultCategories: ['Data'],
    tags: ['fivetran', 'data pipeline', 'etl'],
  },
  {
    id: 'informatica',
    vendor: 'Informatica',
    url: 'https://www.informatica.com/events.html',
    defaultCategories: ['Data'],
    tags: ['informatica', 'data integration', 'mdm'],
  },
  {
    id: 'cloudera',
    vendor: 'Cloudera',
    url: 'https://www.cloudera.com/events.html',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['cloudera', 'evolve', 'hadoop', 'data lakehouse'],
  },
  {
    id: 'starburst',
    vendor: 'Starburst',
    url: 'https://www.starburst.io/events/',
    defaultCategories: ['Data'],
    tags: ['starburst', 'trino', 'data mesh'],
  },
  {
    id: 'airbyte',
    vendor: 'Airbyte',
    url: 'https://airbyte.com/events',
    defaultCategories: ['Data'],
    tags: ['airbyte', 'data pipeline', 'etl'],
  },
  {
    id: 'talend',
    vendor: 'Talend',
    url: 'https://www.talend.com/resources/events/',
    defaultCategories: ['Data'],
    tags: ['talend', 'data integration'],
  },
  {
    id: 'teradata',
    vendor: 'Teradata',
    url: 'https://www.teradata.com/events',
    defaultCategories: ['Data'],
    tags: ['teradata', 'data warehouse', 'partners'],
  },
  {
    id: 'dremio',
    vendor: 'Dremio',
    url: 'https://www.dremio.com/resources/events/',
    defaultCategories: ['Data'],
    tags: ['dremio', 'data lakehouse', 'apache arrow'],
  },
  {
    id: 'apache-foundation',
    vendor: 'Apache Software Foundation',
    url: 'https://www.apache.org/events/current-event.html',
    defaultCategories: ['Data', 'Developer'],
    tags: ['apache', 'open source', 'apachecon'],
  },

  // ── Observability / Monitoring ────────────────────────────────────────────
  {
    id: 'grafana',
    vendor: 'Grafana Labs',
    url: 'https://grafana.com/events/',
    defaultCategories: ['Data', 'Cloud', 'Developer'],
    tags: ['grafana', 'observability', 'grafanacon'],
  },
  {
    id: 'datadog',
    vendor: 'Datadog',
    url: 'https://www.datadoghq.com/events/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['datadog', 'dash', 'observability'],
  },
  {
    id: 'newrelic',
    vendor: 'New Relic',
    url: 'https://newrelic.com/events',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['new relic', 'futurestack', 'observability'],
  },
  {
    id: 'dynatrace',
    vendor: 'Dynatrace',
    url: 'https://www.dynatrace.com/perform/',
    defaultCategories: ['Data', 'Cloud'],
    tags: ['dynatrace', 'perform', 'apm'],
  },
  {
    id: 'splunk-conf',
    vendor: 'Splunk',
    url: 'https://conf.splunk.com/',
    defaultCategories: ['Data', 'Cybersecurity'],
    tags: ['splunk', '.conf', 'siem', 'observability'],
  },
  {
    id: 'sumologic',
    vendor: 'Sumo Logic',
    url: 'https://www.sumologic.com/events/',
    defaultCategories: ['Data', 'Cybersecurity'],
    tags: ['sumo logic', 'illuminate', 'log management'],
  },
  {
    id: 'honeycomb',
    vendor: 'Honeycomb',
    url: 'https://www.honeycomb.io/events',
    defaultCategories: ['Data', 'Developer'],
    tags: ['honeycomb', 'observability'],
  },

  // ── Analytics / BI ────────────────────────────────────────────────────────
  {
    id: 'tableau',
    vendor: 'Tableau (Salesforce)',
    url: 'https://www.tableau.com/events',
    defaultCategories: ['Data'],
    tags: ['tableau', 'bi', 'data visualization'],
  },
  {
    id: 'looker',
    vendor: 'Looker (Google)',
    url: 'https://cloud.google.com/events',
    defaultCategories: ['Data'],
    tags: ['looker', 'bi', 'google'],
  },
  {
    id: 'thoughtspot',
    vendor: 'ThoughtSpot',
    url: 'https://www.thoughtspot.com/events',
    defaultCategories: ['Data'],
    tags: ['thoughtspot', 'analytics', 'beyond'],
  },
  {
    id: 'microstrategy',
    vendor: 'MicroStrategy',
    url: 'https://www.microstrategy.com/en/company/events',
    defaultCategories: ['Data'],
    tags: ['microstrategy', 'analytics', 'world'],
  },
];
