module.exports = [

  // ── DevOps / Platform Engineering ────────────────────────────────────────
  {
    id: 'hashicorp',
    vendor: 'HashiCorp',
    url: 'https://www.hashicorp.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['hashicorp', 'hashiconf', 'terraform', 'vault'],
  },
  {
    id: 'github',
    vendor: 'GitHub',
    url: 'https://githubuniverse.com/',
    defaultCategories: ['Developer'],
    tags: ['github', 'universe', 'git', 'devops'],
  },
  {
    id: 'gitlab',
    vendor: 'GitLab',
    url: 'https://about.gitlab.com/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['gitlab', 'commit', 'devsecops'],
  },
  {
    id: 'atlassian',
    vendor: 'Atlassian',
    url: 'https://www.atlassian.com/events',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['atlassian', 'team', 'jira', 'confluence'],
  },
  {
    id: 'jfrog',
    vendor: 'JFrog',
    url: 'https://jfrog.com/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['jfrog', 'swampup', 'devops', 'artifactory'],
  },
  {
    id: 'docker',
    vendor: 'Docker',
    url: 'https://www.docker.com/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['docker', 'dockercon', 'containers'],
  },
  {
    id: 'pagerduty',
    vendor: 'PagerDuty',
    url: 'https://www.pagerduty.com/events/',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['pagerduty', 'summit', 'incident management'],
  },
  {
    id: 'harness',
    vendor: 'Harness',
    url: 'https://www.harness.io/events',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['harness', 'unscripted', 'ci/cd'],
  },
  {
    id: 'circleci',
    vendor: 'CircleCI',
    url: 'https://circleci.com/events/',
    defaultCategories: ['Developer'],
    tags: ['circleci', 'ci/cd'],
  },
  {
    id: 'puppet',
    vendor: 'Puppet',
    url: 'https://puppet.com/events/',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['puppet', 'configuration management', 'devops'],
  },
  {
    id: 'progress-chef',
    vendor: 'Progress / Chef',
    url: 'https://www.progress.com/events',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['chef', 'progress', 'configuration management'],
  },
  {
    id: 'sonatype',
    vendor: 'Sonatype',
    url: 'https://www.sonatype.com/events',
    defaultCategories: ['Developer', 'Cybersecurity'],
    tags: ['sonatype', 'nexus', 'software supply chain'],
  },
  {
    id: 'buildkite',
    vendor: 'Buildkite',
    url: 'https://buildkite.com/events',
    defaultCategories: ['Developer'],
    tags: ['buildkite', 'ci/cd'],
  },
  {
    id: 'launchdarkly',
    vendor: 'LaunchDarkly',
    url: 'https://launchdarkly.com/events/',
    defaultCategories: ['Developer'],
    tags: ['launchdarkly', 'feature flags'],
  },
  {
    id: 'split-io',
    vendor: 'Split.io',
    url: 'https://www.split.io/events/',
    defaultCategories: ['Developer'],
    tags: ['split', 'feature flags', 'experimentation'],
  },
  {
    id: 'backstage',
    vendor: 'Backstage (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['backstage', 'developer portal', 'platform engineering'],
  },

  // ── Developer Communities / Conferences ───────────────────────────────────
  {
    id: 'devopsdays',
    vendor: 'DevOpsDays',
    url: 'https://devopsdays.org/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['devopsdays', 'devops', 'community'],
    selectors: {
      cards: '.event, article, .events-list li, tr',
      title: 'h3, h4, a, td:first-child',
      date:  'time, .date, td:nth-child(2)',
      location: '.location, td:nth-child(3)',
    },
  },
  {
    id: 'srecona',
    vendor: 'SREcon',
    url: 'https://www.usenix.org/srecon',
    defaultCategories: ['IT / Ops', 'Cloud'],
    tags: ['srecon', 'site reliability', 'sre'],
  },
  {
    id: 'velocity',
    vendor: 'Velocity (O\'Reilly)',
    url: 'https://www.oreilly.com/radar/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['velocity', 'oreilly', 'infrastructure'],
  },
  {
    id: 'devoxx',
    vendor: 'Devoxx',
    url: 'https://devoxx.com/',
    defaultCategories: ['Developer'],
    tags: ['devoxx', 'java', 'developer conference'],
  },
  {
    id: 'qcon',
    vendor: 'QCon',
    url: 'https://qconferences.com/',
    defaultCategories: ['Developer'],
    tags: ['qcon', 'software architecture'],
  },
  {
    id: 'goto-conf',
    vendor: 'GOTO Conferences',
    url: 'https://gotoaarhus.com/',
    defaultCategories: ['Developer'],
    tags: ['goto', 'software development'],
  },
  {
    id: 'software-circus',
    vendor: 'Software Circus',
    url: 'https://www.softwarecircus.io/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['software circus', 'cloud native'],
  },
];
