module.exports = [

  // ── DevOps / Platform Engineering ────────────────────────────────────────
  {
    id: 'hashicorp',
    vendor: 'HashiCorp',
    url: 'https://www.hashicorp.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['hashicorp', 'hashiconf', 'terraform', 'vault'],
  },
  {
    id: 'github',
    vendor: 'GitHub',
    url: 'https://githubuniverse.com/',
    defaultCategories: ['Developer'],
    tags: ['github', 'universe', 'git', 'devops'],
  },
  {
    id: 'gitlab',
    vendor: 'GitLab',
    url: 'https://about.gitlab.com/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['gitlab', 'commit', 'devsecops'],
  },
  {
    id: 'atlassian',
    vendor: 'Atlassian',
    url: 'https://www.atlassian.com/events',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['atlassian', 'team', 'jira', 'confluence'],
  },
  {
    id: 'jfrog',
    vendor: 'JFrog',
    url: 'https://jfrog.com/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['jfrog', 'swampup', 'devops', 'artifactory'],
  },
  {
    id: 'docker',
    vendor: 'Docker',
    url: 'https://www.docker.com/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['docker', 'dockercon', 'containers'],
  },
  {
    id: 'pagerduty',
    vendor: 'PagerDuty',
    url: 'https://www.pagerduty.com/events/',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['pagerduty', 'summit', 'incident management'],
  },
  {
    id: 'harness',
    vendor: 'Harness',
    url: 'https://www.harness.io/events',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['harness', 'unscripted', 'ci/cd'],
  },
  {
    id: 'circleci',
    vendor: 'CircleCI',
    url: 'https://circleci.com/events/',
    defaultCategories: ['Developer'],
    tags: ['circleci', 'ci/cd'],
  },
  {
    id: 'puppet',
    vendor: 'Puppet',
    url: 'https://puppet.com/events/',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['puppet', 'configuration management', 'devops'],
  },
  {
    id: 'progress-chef',
    vendor: 'Progress / Chef',
    url: 'https://www.progress.com/events',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['chef', 'progress', 'configuration management'],
  },
  {
    id: 'sonatype',
    vendor: 'Sonatype',
    url: 'https://www.sonatype.com/events',
    defaultCategories: ['Developer', 'Cybersecurity'],
    tags: ['sonatype', 'nexus', 'software supply chain'],
  },
  {
    id: 'buildkite',
    vendor: 'Buildkite',
    url: 'https://buildkite.com/events',
    defaultCategories: ['Developer'],
    tags: ['buildkite', 'ci/cd'],
  },
  {
    id: 'launchdarkly',
    vendor: 'LaunchDarkly',
    url: 'https://launchdarkly.com/events/',
    defaultCategories: ['Developer'],
    tags: ['launchdarkly', 'feature flags'],
  },
  {
    id: 'split-io',
    vendor: 'Split.io',
    url: 'https://www.split.io/events/',
    defaultCategories: ['Developer'],
    tags: ['split', 'feature flags', 'experimentation'],
  },
  {
    id: 'backstage',
    vendor: 'Backstage (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['backstage', 'developer portal', 'platform engineering'],
  },

  // ── CI/CD Platforms ───────────────────────────────────────────────────────
  {
    id: 'jenkins',
    vendor: 'Jenkins / CloudBees',
    url: 'https://www.cloudbees.com/events',
    defaultCategories: ['Developer'],
    tags: ['jenkins', 'devops world', 'ci/cd', 'automation'],
  },
  {
    id: 'travis-ci',
    vendor: 'Travis CI',
    url: 'https://www.travis-ci.com/',
    defaultCategories: ['Developer'],
    tags: ['travis ci', 'ci/cd', 'continuous integration'],
  },
  {
    id: 'teamcity',
    vendor: 'TeamCity (JetBrains)',
    url: 'https://www.jetbrains.com/company/events/',
    defaultCategories: ['Developer'],
    tags: ['teamcity', 'jetbrains', 'ci/cd', 'build'],
  },
  {
    id: 'buddy',
    vendor: 'Buddy',
    url: 'https://buddy.works/',
    defaultCategories: ['Developer'],
    tags: ['buddy', 'ci/cd', 'deployment', 'automation'],
  },
  {
    id: 'codefresh',
    vendor: 'Codefresh',
    url: 'https://codefresh.io/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['codefresh', 'ci/cd', 'gitops', 'kubernetes'],
  },
  {
    id: 'argo-cd',
    vendor: 'Argo CD (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['argo', 'gitops', 'kubernetes', 'cncf'],
  },
  {
    id: 'tekton',
    vendor: 'Tekton (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['tekton', 'ci/cd', 'kubernetes', 'cncf'],
  },

  // ── Source Code Management / Git ──────────────────────────────────────────
  {
    id: 'perforce',
    vendor: 'Perforce',
    url: 'https://www.perforce.com/events',
    defaultCategories: ['Developer'],
    tags: ['perforce', 'version control', 'scm', 'devops'],
  },

  // ── Testing / QA Platforms ────────────────────────────────────────────────
  {
    id: 'selenium',
    vendor: 'Selenium / SeleniumConf',
    url: 'https://seleniumconf.com/',
    defaultCategories: ['Developer'],
    tags: ['selenium', 'seleniumconf', 'test automation', 'browser testing'],
  },
  {
    id: 'appium',
    vendor: 'Appium',
    url: 'https://appiumconf.com/',
    defaultCategories: ['Developer'],
    tags: ['appium', 'mobile testing', 'test automation'],
  },
  {
    id: 'cypress',
    vendor: 'Cypress',
    url: 'https://www.cypress.io/events',
    defaultCategories: ['Developer'],
    tags: ['cypress', 'e2e testing', 'test automation'],
  },
  {
    id: 'playwright',
    vendor: 'Playwright (Microsoft)',
    url: 'https://playwright.dev/',
    defaultCategories: ['Developer'],
    tags: ['playwright', 'e2e testing', 'browser automation'],
  },
  {
    id: 'postman',
    vendor: 'Postman',
    url: 'https://www.postman.com/events/',
    defaultCategories: ['Developer'],
    tags: ['postman', 'api testing', 'postcon'],
  },
  {
    id: 'smartbear',
    vendor: 'SmartBear',
    url: 'https://smartbear.com/events/',
    defaultCategories: ['Developer'],
    tags: ['smartbear', 'api testing', 'qa', 'soapui'],
  },
  {
    id: 'tricentis',
    vendor: 'Tricentis',
    url: 'https://www.tricentis.com/events',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['tricentis', 'test automation', 'qa', 'continuous testing'],
  },
  {
    id: 'opentext-qm',
    vendor: 'OpenText (Micro Focus)',
    url: 'https://www.opentext.com/events',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['opentext', 'micro focus', 'quality management', 'testing'],
  },
  {
    id: 'sauce-labs',
    vendor: 'Sauce Labs',
    url: 'https://saucelabs.com/events',
    defaultCategories: ['Developer'],
    tags: ['sauce labs', 'browser testing', 'test automation'],
  },
  {
    id: 'browserstack',
    vendor: 'BrowserStack',
    url: 'https://www.browserstack.com/events',
    defaultCategories: ['Developer'],
    tags: ['browserstack', 'cross browser testing', 'test automation'],
  },
  {
    id: 'lambdatest',
    vendor: 'LambdaTest',
    url: 'https://www.lambdatest.com/events',
    defaultCategories: ['Developer'],
    tags: ['lambdatest', 'cross browser testing', 'automation'],
  },
  {
    id: 'mabl',
    vendor: 'Mabl',
    url: 'https://www.mabl.com/events',
    defaultCategories: ['Developer'],
    tags: ['mabl', 'intelligent testing', 'test automation', 'ai'],
  },

  // ── Code Quality / Static Analysis ───────────────────────────────────────
  {
    id: 'sonarsource',
    vendor: 'SonarSource (SonarQube)',
    url: 'https://www.sonarsource.com/events/',
    defaultCategories: ['Developer'],
    tags: ['sonarqube', 'code quality', 'static analysis'],
  },
  {
    id: 'synopsys-coverity',
    vendor: 'Synopsys (Coverity)',
    url: 'https://www.synopsys.com/events.html',
    defaultCategories: ['Developer', 'Cybersecurity'],
    tags: ['coverity', 'synopsys', 'static analysis', 'security'],
  },
  {
    id: 'veracode',
    vendor: 'Veracode',
    url: 'https://www.veracode.com/resources/events',
    defaultCategories: ['Developer', 'Cybersecurity'],
    tags: ['veracode', 'application security', 'sast', 'devsecops'],
  },
  {
    id: 'snyk',
    vendor: 'Snyk',
    url: 'https://snyk.io/events/',
    defaultCategories: ['Developer', 'Cybersecurity'],
    tags: ['snyk', 'devsecops', 'security', 'sast'],
  },
  {
    id: 'semgrep',
    vendor: 'Semgrep',
    url: 'https://semgrep.dev/',
    defaultCategories: ['Developer', 'Cybersecurity'],
    tags: ['semgrep', 'static analysis', 'sast', 'code security'],
  },
  {
    id: 'deepsource',
    vendor: 'DeepSource',
    url: 'https://deepsource.com/',
    defaultCategories: ['Developer'],
    tags: ['deepsource', 'code quality', 'static analysis'],
  },
  {
    id: 'codeclimate',
    vendor: 'Code Climate',
    url: 'https://codeclimate.com/',
    defaultCategories: ['Developer'],
    tags: ['code climate', 'code quality', 'technical debt'],
  },
  {
    id: 'codacy',
    vendor: 'Codacy',
    url: 'https://www.codacy.com/',
    defaultCategories: ['Developer'],
    tags: ['codacy', 'code quality', 'static analysis'],
  },
  {
    id: 'embold',
    vendor: 'Embold',
    url: 'https://embold.io/',
    defaultCategories: ['Developer'],
    tags: ['embold', 'code quality', 'software analytics'],
  },
  {
    id: 'cast-software',
    vendor: 'CAST Software',
    url: 'https://www.castsoftware.com/events',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['cast', 'software intelligence', 'code quality'],
  },

  // ── Artifact Management / Package Registries ──────────────────────────────
  {
    id: 'pulp-project',
    vendor: 'Pulp Project',
    url: 'https://pulpproject.org/',
    defaultCategories: ['Developer'],
    tags: ['pulp', 'artifact management', 'package registry'],
  },
  {
    id: 'cloudrepo',
    vendor: 'CloudRepo',
    url: 'https://www.cloudrepo.io/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['cloudrepo', 'artifact repository', 'package registry'],
  },

  // ── Infrastructure as Code ────────────────────────────────────────────────
  {
    id: 'pulumi',
    vendor: 'Pulumi',
    url: 'https://www.pulumi.com/resources/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['pulumi', 'infrastructure as code', 'iac', 'cloud'],
  },
  {
    id: 'saltstack',
    vendor: 'SaltStack (VMware)',
    url: 'https://www.vmware.com/explore.html',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['saltstack', 'configuration management', 'automation'],
  },
  {
    id: 'crossplane',
    vendor: 'Crossplane (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['crossplane', 'infrastructure as code', 'kubernetes', 'cncf'],
  },
  {
    id: 'opentofu',
    vendor: 'OpenTofu',
    url: 'https://opentofu.org/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['opentofu', 'terraform', 'infrastructure as code', 'open source'],
  },

  // ── Container & Kubernetes Tools ──────────────────────────────────────────
  {
    id: 'kubecon',
    vendor: 'KubeCon / CloudNativeCon (CNCF)',
    url: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['kubecon', 'kubernetes', 'cloud native', 'cncf'],
  },
  {
    id: 'helm',
    vendor: 'Helm (CNCF)',
    url: 'https://helm.sh/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['helm', 'kubernetes', 'package manager', 'cncf'],
  },
  {
    id: 'istio',
    vendor: 'Istio (CNCF)',
    url: 'https://events.istio.io/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['istio', 'service mesh', 'kubernetes', 'cncf'],
  },
  {
    id: 'linkerd',
    vendor: 'Linkerd (Buoyant)',
    url: 'https://buoyant.io/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['linkerd', 'service mesh', 'kubernetes'],
  },
  {
    id: 'envoy-proxy',
    vendor: 'Envoy Proxy (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['envoy', 'proxy', 'service mesh', 'cncf'],
  },
  {
    id: 'open-policy-agent',
    vendor: 'Open Policy Agent (Styra)',
    url: 'https://www.styra.com/events/',
    defaultCategories: ['Cloud', 'Developer', 'Cybersecurity'],
    tags: ['opa', 'open policy agent', 'policy as code', 'kubernetes'],
  },
  {
    id: 'kyverno',
    vendor: 'Kyverno',
    url: 'https://kyverno.io/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['kyverno', 'kubernetes', 'policy', 'security'],
  },
  {
    id: 'rancher',
    vendor: 'Rancher (SUSE)',
    url: 'https://www.suse.com/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['rancher', 'kubernetes', 'suse', 'container management'],
  },
  {
    id: 'flux-cd',
    vendor: 'Flux CD (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['flux', 'gitops', 'kubernetes', 'cncf'],
  },
  {
    id: 'knative',
    vendor: 'Knative (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['knative', 'serverless', 'kubernetes', 'cncf'],
  },
  {
    id: 'dapr',
    vendor: 'Dapr (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['dapr', 'microservices', 'kubernetes', 'cncf'],
  },

  // ── Service Mesh / API Gateway ────────────────────────────────────────────
  {
    id: 'kong',
    vendor: 'Kong',
    url: 'https://konghq.com/events',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['kong', 'api gateway', 'api management'],
  },
  {
    id: 'nginx',
    vendor: 'NGINX (F5)',
    url: 'https://www.f5.com/events',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['nginx', 'api gateway', 'load balancer', 'f5'],
  },
  {
    id: 'traefik',
    vendor: 'Traefik',
    url: 'https://traefik.io/traefik-community/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['traefik', 'reverse proxy', 'api gateway', 'kubernetes'],
  },
  {
    id: 'haproxy',
    vendor: 'HAProxy',
    url: 'https://www.haproxy.com/blog/',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['haproxy', 'load balancer', 'proxy'],
  },
  {
    id: 'mulesoft',
    vendor: 'MuleSoft (Salesforce)',
    url: 'https://www.mulesoft.com/events',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['mulesoft', 'api management', 'integration', 'salesforce'],
  },

  // ── Monitoring / APM / Observability ──────────────────────────────────────
  {
    id: 'grafana',
    vendor: 'Grafana Labs',
    url: 'https://grafana.com/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['grafana', 'observability', 'monitoring', 'dashboards'],
  },
  {
    id: 'datadog',
    vendor: 'Datadog',
    url: 'https://www.datadoghq.com/events-webinars/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['datadog', 'monitoring', 'observability', 'dashcon'],
  },
  {
    id: 'newrelic',
    vendor: 'New Relic',
    url: 'https://newrelic.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['new relic', 'observability', 'apm', 'monitoring'],
  },
  {
    id: 'dynatrace',
    vendor: 'Dynatrace',
    url: 'https://www.dynatrace.com/events/',
    defaultCategories: ['Cloud', 'Developer', 'IT / Ops'],
    tags: ['dynatrace', 'apm', 'observability', 'ai ops'],
  },
  {
    id: 'appdynamics',
    vendor: 'AppDynamics (Cisco)',
    url: 'https://www.cisco.com/c/en/us/training-events/events.html',
    defaultCategories: ['IT / Ops', 'Cloud'],
    tags: ['appdynamics', 'apm', 'cisco', 'application performance'],
  },
  {
    id: 'elastic-apm',
    vendor: 'Elastic',
    url: 'https://www.elastic.co/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['elastic', 'elasticsearch', 'apm', 'observability'],
  },
  {
    id: 'instana',
    vendor: 'Instana (IBM)',
    url: 'https://www.ibm.com/events',
    defaultCategories: ['IT / Ops', 'Cloud'],
    tags: ['instana', 'ibm', 'apm', 'observability'],
  },
  {
    id: 'honeycomb',
    vendor: 'Honeycomb',
    url: 'https://www.honeycomb.io/resources/events',
    defaultCategories: ['Developer'],
    tags: ['honeycomb', 'observability', 'distributed tracing'],
  },
  {
    id: 'jaeger',
    vendor: 'Jaeger (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['jaeger', 'distributed tracing', 'cncf', 'observability'],
  },
  {
    id: 'opentelemetry',
    vendor: 'OpenTelemetry (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['opentelemetry', 'observability', 'tracing', 'cncf'],
  },

  // ── Incident Management / On-call ─────────────────────────────────────────
  {
    id: 'opsgenie',
    vendor: 'Opsgenie (Atlassian)',
    url: 'https://www.atlassian.com/events',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['opsgenie', 'incident management', 'on-call', 'atlassian'],
  },
  {
    id: 'victorops',
    vendor: 'VictorOps (Splunk)',
    url: 'https://www.splunk.com/en_us/events.html',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['victorops', 'splunk', 'incident management', 'on-call'],
  },
  {
    id: 'firehydrant',
    vendor: 'FireHydrant',
    url: 'https://firehydrant.com/events/',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['firehydrant', 'incident management', 'sre'],
  },
  {
    id: 'blameless',
    vendor: 'Blameless',
    url: 'https://www.blameless.com/events',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['blameless', 'incident management', 'sre', 'reliability'],
  },
  {
    id: 'rootly',
    vendor: 'Rootly',
    url: 'https://rootly.com/events',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['rootly', 'incident management', 'on-call'],
  },
  {
    id: 'squadcast',
    vendor: 'Squadcast',
    url: 'https://www.squadcast.com/events',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['squadcast', 'incident management', 'on-call', 'sre'],
  },
  {
    id: 'incident-io',
    vendor: 'incident.io',
    url: 'https://incident.io/events',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['incident.io', 'incident management', 'on-call'],
  },

  // ── Feature Flags / Experimentation ──────────────────────────────────────
  {
    id: 'flagsmith',
    vendor: 'Flagsmith',
    url: 'https://flagsmith.com/',
    defaultCategories: ['Developer'],
    tags: ['flagsmith', 'feature flags', 'open source'],
  },
  {
    id: 'unleash',
    vendor: 'Unleash',
    url: 'https://www.getunleash.io/events',
    defaultCategories: ['Developer'],
    tags: ['unleash', 'feature flags', 'open source'],
  },
  {
    id: 'optimizely',
    vendor: 'Optimizely',
    url: 'https://www.optimizely.com/events/',
    defaultCategories: ['Developer'],
    tags: ['optimizely', 'experimentation', 'feature flags', 'a/b testing'],
  },
  {
    id: 'ab-tasty',
    vendor: 'AB Tasty',
    url: 'https://www.abtasty.com/events/',
    defaultCategories: ['Developer'],
    tags: ['ab tasty', 'experimentation', 'a/b testing'],
  },
  {
    id: 'vwo',
    vendor: 'VWO (Visual Website Optimizer)',
    url: 'https://vwo.com/resources/webinars/',
    defaultCategories: ['Developer'],
    tags: ['vwo', 'a/b testing', 'experimentation', 'conversion'],
  },
  {
    id: 'statsig',
    vendor: 'Statsig',
    url: 'https://www.statsig.com/events',
    defaultCategories: ['Developer'],
    tags: ['statsig', 'feature flags', 'experimentation', 'product analytics'],
  },

  // ── Developer Experience / Internal Developer Portals ─────────────────────
  {
    id: 'port',
    vendor: 'Port',
    url: 'https://www.getport.io/events',
    defaultCategories: ['Developer'],
    tags: ['port', 'developer portal', 'platform engineering'],
  },
  {
    id: 'cortex',
    vendor: 'Cortex',
    url: 'https://www.cortex.io/events',
    defaultCategories: ['Developer'],
    tags: ['cortex', 'developer portal', 'service catalog'],
  },
  {
    id: 'opslevel',
    vendor: 'OpsLevel',
    url: 'https://www.opslevel.com/resources',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['opslevel', 'developer portal', 'service maturity'],
  },
  {
    id: 'roadie',
    vendor: 'Roadie',
    url: 'https://roadie.io/events/',
    defaultCategories: ['Developer'],
    tags: ['roadie', 'backstage', 'developer portal', 'platform engineering'],
  },
  {
    id: 'gimlet',
    vendor: 'Gimlet',
    url: 'https://gimlet.io/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['gimlet', 'gitops', 'kubernetes', 'developer platform'],
  },
  {
    id: 'humanitec',
    vendor: 'Humanitec',
    url: 'https://humanitec.com/events',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['humanitec', 'platform engineering', 'idp', 'developer platform'],
  },
  {
    id: 'kratix',
    vendor: 'Kratix',
    url: 'https://kratix.io/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['kratix', 'platform engineering', 'kubernetes'],
  },
  {
    id: 'coherence',
    vendor: 'Coherence',
    url: 'https://www.withcoherence.com/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['coherence', 'developer platform', 'cloud'],
  },
  {
    id: 'qovery',
    vendor: 'Qovery',
    url: 'https://www.qovery.com/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['qovery', 'developer platform', 'kubernetes', 'cloud'],
  },

  // ── Low-code / No-code / RPA ──────────────────────────────────────────────
  {
    id: 'outsystems',
    vendor: 'OutSystems',
    url: 'https://www.outsystems.com/nextstep/',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['outsystems', 'low-code', 'nextstep', 'app development'],
  },
  {
    id: 'mendix',
    vendor: 'Mendix (Siemens)',
    url: 'https://www.mendix.com/events/',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['mendix', 'low-code', 'siemens', 'app development'],
  },
  {
    id: 'appian',
    vendor: 'Appian',
    url: 'https://appian.com/events.html',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['appian', 'low-code', 'bpm', 'rpa'],
  },
  {
    id: 'servicenow-creator',
    vendor: 'ServiceNow Creator',
    url: 'https://knowledge.servicenow.com/',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['servicenow', 'low-code', 'knowledge', 'app engine'],
  },
  {
    id: 'pega-systems',
    vendor: 'Pega Systems',
    url: 'https://www.pega.com/pega-world',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['pega', 'low-code', 'bpm', 'rpa'],
  },
  {
    id: 'nintex',
    vendor: 'Nintex',
    url: 'https://www.nintex.com/events/',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['nintex', 'workflow automation', 'rpa', 'low-code'],
  },
  {
    id: 'retool',
    vendor: 'Retool',
    url: 'https://retool.com/events',
    defaultCategories: ['Developer'],
    tags: ['retool', 'low-code', 'internal tools', 'developer'],
  },
  {
    id: 'bubble',
    vendor: 'Bubble',
    url: 'https://bubble.io/meetups',
    defaultCategories: ['Developer'],
    tags: ['bubble', 'no-code', 'app builder'],
  },

  // ── Security in DevOps (DevSecOps) ────────────────────────────────────────
  {
    id: 'gitguardian',
    vendor: 'GitGuardian',
    url: 'https://www.gitguardian.com/events',
    defaultCategories: ['Developer', 'Cybersecurity'],
    tags: ['gitguardian', 'secrets detection', 'devsecops'],
  },
  {
    id: 'aqua-security',
    vendor: 'Aqua Security',
    url: 'https://www.aquasec.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud', 'Developer'],
    tags: ['aqua security', 'container security', 'devsecops', 'cloud native'],
  },
  {
    id: 'checkov',
    vendor: 'Checkov (Bridgecrew / Palo Alto)',
    url: 'https://www.paloaltonetworks.com/events',
    defaultCategories: ['Developer', 'Cybersecurity'],
    tags: ['checkov', 'bridgecrew', 'iac security', 'devsecops'],
  },
  {
    id: 'owasp-zap',
    vendor: 'OWASP ZAP',
    url: 'https://owasp.org/events/',
    defaultCategories: ['Developer', 'Cybersecurity'],
    tags: ['owasp', 'zap', 'dast', 'application security'],
  },
  {
    id: 'prisma-cloud',
    vendor: 'Prisma Cloud (Palo Alto Networks)',
    url: 'https://www.paloaltonetworks.com/events',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['prisma cloud', 'palo alto', 'cloud security', 'devsecops'],
  },

  // ── Chaos Engineering / Reliability ──────────────────────────────────────
  {
    id: 'chaos-monkey',
    vendor: 'Chaos Monkey / Netflix OSS',
    url: 'https://netflixtechblog.com/',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['chaos monkey', 'netflix', 'chaos engineering', 'reliability'],
  },
  {
    id: 'gremlin',
    vendor: 'Gremlin',
    url: 'https://www.gremlin.com/events/',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['gremlin', 'chaos engineering', 'reliability', 'site reliability'],
  },
  {
    id: 'litmuschaos',
    vendor: 'LitmusChaos (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['litmus', 'chaos engineering', 'kubernetes', 'cncf'],
  },
  {
    id: 'chaos-mesh',
    vendor: 'Chaos Mesh (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['chaos mesh', 'chaos engineering', 'kubernetes', 'cncf'],
  },
  {
    id: 'steadybit',
    vendor: 'Steadybit',
    url: 'https://www.steadybit.com/events',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['steadybit', 'chaos engineering', 'reliability'],
  },
  {
    id: 'reliably',
    vendor: 'Reliably',
    url: 'https://reliably.com/',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['reliably', 'chaos engineering', 'slo', 'reliability'],
  },

  // ── GitOps / Progressive Delivery ────────────────────────────────────────
  {
    id: 'spinnaker',
    vendor: 'Spinnaker (Armory)',
    url: 'https://www.armory.io/events/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['spinnaker', 'armory', 'continuous delivery', 'gitops'],
  },
  {
    id: 'weaveworks',
    vendor: 'Weaveworks',
    url: 'https://www.weave.works/events/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['weaveworks', 'gitops', 'kubernetes', 'flux'],
  },
  {
    id: 'flagger',
    vendor: 'Flagger',
    url: 'https://flagger.app/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['flagger', 'progressive delivery', 'canary', 'kubernetes'],
  },

  // ── Cloud Cost / Platform Engineering ────────────────────────────────────
  {
    id: 'infracost',
    vendor: 'Infracost',
    url: 'https://www.infracost.io/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['infracost', 'cloud cost', 'terraform', 'finops'],
  },
  {
    id: 'cast-ai',
    vendor: 'CAST AI',
    url: 'https://cast.ai/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['cast ai', 'cloud cost', 'kubernetes', 'optimization'],
  },
  {
    id: 'kubecost',
    vendor: 'Kubecost',
    url: 'https://www.kubecost.com/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['kubecost', 'kubernetes cost', 'finops', 'cloud cost'],
  },
  {
    id: 'spot-netapp',
    vendor: 'Spot by NetApp',
    url: 'https://spot.io/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['spot', 'netapp', 'cloud cost', 'finops'],
  },
  {
    id: 'zesty',
    vendor: 'Zesty',
    url: 'https://zesty.io/events/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['zesty', 'cloud cost', 'optimization', 'finops'],
  },
  {
    id: 'perfectscale',
    vendor: 'PerfectScale',
    url: 'https://www.perfectscale.io/',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['perfectscale', 'kubernetes', 'cloud cost', 'optimization'],
  },

  // ── Mobile DevOps ─────────────────────────────────────────────────────────
  {
    id: 'bitrise',
    vendor: 'Bitrise',
    url: 'https://www.bitrise.io/events',
    defaultCategories: ['Developer'],
    tags: ['bitrise', 'mobile ci/cd', 'mobile devops'],
  },
  {
    id: 'fastlane',
    vendor: 'Fastlane (open source)',
    url: 'https://fastlane.tools/',
    defaultCategories: ['Developer'],
    tags: ['fastlane', 'mobile ci/cd', 'ios', 'android'],
  },
  {
    id: 'appcenter',
    vendor: 'App Center (Microsoft)',
    url: 'https://appcenter.ms/',
    defaultCategories: ['Developer'],
    tags: ['appcenter', 'mobile devops', 'microsoft', 'distribution'],
  },
  {
    id: 'firebase-distribution',
    vendor: 'Firebase App Distribution (Google)',
    url: 'https://firebase.google.com/events',
    defaultCategories: ['Developer'],
    tags: ['firebase', 'mobile', 'google', 'app distribution'],
  },
  {
    id: 'runway',
    vendor: 'Runway',
    url: 'https://www.runway.team/',
    defaultCategories: ['Developer'],
    tags: ['runway', 'mobile release', 'mobile devops'],
  },

  // ── Developer Conferences / Communities ───────────────────────────────────
  {
    id: 'oscon',
    vendor: 'OSCON (O\'Reilly)',
    url: 'https://www.oreilly.com/conferences/',
    defaultCategories: ['Developer'],
    tags: ['oscon', 'open source', 'oreilly'],
  },
  {
    id: 'open-source-summit',
    vendor: 'Open Source Summit (Linux Foundation)',
    url: 'https://events.linuxfoundation.org/open-source-summit-north-america/',
    defaultCategories: ['Developer'],
    tags: ['open source summit', 'linux foundation', 'open source'],
  },
  {
    id: 'pycon',
    vendor: 'PyCon',
    url: 'https://us.pycon.org/',
    defaultCategories: ['Developer'],
    tags: ['pycon', 'python', 'open source'],
  },
  {
    id: 'pycon-eu',
    vendor: 'PyCon Europe',
    url: 'https://europython-society.org/',
    defaultCategories: ['Developer'],
    tags: ['pycon europe', 'python', 'europython'],
  },
  {
    id: 'rustconf',
    vendor: 'RustConf',
    url: 'https://rustconf.com/',
    defaultCategories: ['Developer'],
    tags: ['rustconf', 'rust', 'systems programming'],
  },
  {
    id: 'gophercon',
    vendor: 'GopherCon',
    url: 'https://www.gophercon.com/',
    defaultCategories: ['Developer'],
    tags: ['gophercon', 'go', 'golang'],
  },
  {
    id: 'nodeconf',
    vendor: 'NodeConf',
    url: 'https://www.nodeconf.eu/',
    defaultCategories: ['Developer'],
    tags: ['nodeconf', 'nodejs', 'javascript'],
  },
  {
    id: 'jsconf',
    vendor: 'JSConf',
    url: 'https://jsconf.com/',
    defaultCategories: ['Developer'],
    tags: ['jsconf', 'javascript', 'web development'],
  },
  {
    id: 'vueconf',
    vendor: 'VueConf',
    url: 'https://vueconf.us/',
    defaultCategories: ['Developer'],
    tags: ['vueconf', 'vue', 'javascript', 'frontend'],
  },
  {
    id: 'reactconf',
    vendor: 'ReactConf',
    url: 'https://conf.react.dev/',
    defaultCategories: ['Developer'],
    tags: ['reactconf', 'react', 'javascript', 'frontend'],
  },
  {
    id: 'djangocon',
    vendor: 'DjangoCon',
    url: 'https://djangocon.us/',
    defaultCategories: ['Developer'],
    tags: ['djangocon', 'django', 'python', 'web'],
  },
  {
    id: 'platformcon',
    vendor: 'PlatformCon',
    url: 'https://platformcon.com/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['platformcon', 'platform engineering', 'developer experience'],
  },

  // ── Open Source Foundations ───────────────────────────────────────────────
  {
    id: 'linux-foundation',
    vendor: 'Linux Foundation',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['linux foundation', 'open source', 'linux'],
  },
  {
    id: 'apache-software-foundation',
    vendor: 'Apache Software Foundation',
    url: 'https://www.apache.org/events/current-events.html',
    defaultCategories: ['Developer'],
    tags: ['apache', 'open source', 'community'],
  },
  {
    id: 'cncf',
    vendor: 'CNCF (Cloud Native Computing Foundation)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['cncf', 'cloud native', 'kubernetes', 'open source'],
  },
  {
    id: 'openjs-foundation',
    vendor: 'OpenJS Foundation',
    url: 'https://openjsf.org/events/',
    defaultCategories: ['Developer'],
    tags: ['openjs', 'javascript', 'open source', 'nodejs'],
  },
  {
    id: 'eclipse-foundation',
    vendor: 'Eclipse Foundation',
    url: 'https://www.eclipse.org/events/',
    defaultCategories: ['Developer'],
    tags: ['eclipse', 'java', 'open source', 'ide'],
  },

  // ── Microsoft DevOps / Azure ──────────────────────────────────────────────
  {
    id: 'azure-devops',
    vendor: 'Azure DevOps (Microsoft)',
    url: 'https://azure.microsoft.com/en-us/products/devops/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['azure devops', 'microsoft', 'ci/cd', 'pipelines'],
  },
  {
    id: 'microsoft-build',
    vendor: 'Microsoft Build',
    url: 'https://build.microsoft.com/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['microsoft build', 'azure', 'developer conference'],
  },
  {
    id: 'microsoft-ignite',
    vendor: 'Microsoft Ignite',
    url: 'https://ignite.microsoft.com/',
    defaultCategories: ['IT / Ops', 'Cloud', 'Developer'],
    tags: ['microsoft ignite', 'azure', 'cloud'],
  },

  // ── AWS Events ────────────────────────────────────────────────────────────
  {
    id: 'aws-reinvent',
    vendor: 'AWS re:Invent',
    url: 'https://reinvent.awsevents.com/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['aws reinvent', 'amazon', 'cloud', 'devops'],
  },
  {
    id: 'aws-summit',
    vendor: 'AWS Summit',
    url: 'https://aws.amazon.com/events/summits/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['aws summit', 'amazon', 'cloud'],
  },

  // ── Google Cloud Events ───────────────────────────────────────────────────
  {
    id: 'google-cloud-next',
    vendor: 'Google Cloud Next',
    url: 'https://cloud.withgoogle.com/next/',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['google cloud', 'cloud next', 'gcp'],
  },
  {
    id: 'apigee',
    vendor: 'Apigee (Google Cloud)',
    url: 'https://cloud.withgoogle.com/next/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['apigee', 'api management', 'google cloud'],
  },

  // ── Testing / QA — Additional ─────────────────────────────────────────────
  {
    id: 'testng',
    vendor: 'TestNG',
    url: 'https://testng.org/',
    defaultCategories: ['Developer'],
    tags: ['testng', 'java testing', 'test framework'],
  },
  {
    id: 'junit',
    vendor: 'JUnit',
    url: 'https://junit.org/',
    defaultCategories: ['Developer'],
    tags: ['junit', 'java testing', 'unit testing'],
  },

  // ── Monitoring / Observability — Additional ───────────────────────────────
  {
    id: 'zipkin',
    vendor: 'Zipkin',
    url: 'https://zipkin.io/',
    defaultCategories: ['Developer'],
    tags: ['zipkin', 'distributed tracing', 'open source'],
  },
  {
    id: 'lightstep',
    vendor: 'Lightstep (ServiceNow)',
    url: 'https://lightstep.com/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['lightstep', 'observability', 'distributed tracing', 'servicenow'],
  },
  {
    id: 'prometheus',
    vendor: 'Prometheus (CNCF)',
    url: 'https://events.linuxfoundation.org/',
    defaultCategories: ['Developer', 'Cloud'],
    tags: ['prometheus', 'monitoring', 'metrics', 'cncf'],
  },

  // ── Security / DevSecOps — Additional ────────────────────────────────────
  {
    id: 'trivy',
    vendor: 'Trivy (Aqua Security)',
    url: 'https://www.aquasec.com/events/',
    defaultCategories: ['Cybersecurity', 'Developer'],
    tags: ['trivy', 'container security', 'vulnerability scanning', 'devsecops'],
  },
  {
    id: 'lacework',
    vendor: 'Lacework',
    url: 'https://www.lacework.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud'],
    tags: ['lacework', 'cloud security', 'devsecops'],
  },
  {
    id: 'sysdig',
    vendor: 'Sysdig',
    url: 'https://sysdig.com/events/',
    defaultCategories: ['Cybersecurity', 'Cloud', 'Developer'],
    tags: ['sysdig', 'container security', 'kubernetes security'],
  },

  // ── Red Hat / Ansible ─────────────────────────────────────────────────────
  {
    id: 'red-hat',
    vendor: 'Red Hat',
    url: 'https://www.redhat.com/en/events',
    defaultCategories: ['IT / Ops', 'Cloud', 'Developer'],
    tags: ['red hat', 'ansible', 'openshift', 'summit'],
  },
  {
    id: 'ansible',
    vendor: 'Ansible (Red Hat)',
    url: 'https://www.ansible.com/resources/events',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['ansible', 'configuration management', 'automation', 'red hat'],
  },

  // ── Salesforce Platform ───────────────────────────────────────────────────
  {
    id: 'salesforce-platform',
    vendor: 'Salesforce Platform',
    url: 'https://www.salesforce.com/dreamforce/',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['salesforce', 'low-code', 'dreamforce', 'platform'],
  },

  // ── ServiceNow ────────────────────────────────────────────────────────────
  {
    id: 'servicenow',
    vendor: 'ServiceNow',
    url: 'https://knowledge.servicenow.com/',
    defaultCategories: ['IT / Ops', 'Developer'],
    tags: ['servicenow', 'itsm', 'knowledge', 'it operations'],
  },

  // ── Power Platform / Microsoft ────────────────────────────────────────────
  {
    id: 'power-apps',
    vendor: 'Power Apps (Microsoft)',
    url: 'https://www.microsoft.com/en-us/power-platform/events',
    defaultCategories: ['Developer', 'IT / Ops'],
    tags: ['power apps', 'microsoft', 'low-code', 'power platform'],
  },

  // ── Data / Analytics ─────────────────────────────────────────────────────
  {
    id: 'confluent',
    vendor: 'Confluent (Kafka)',
    url: 'https://www.confluent.io/events/',
    defaultCategories: ['Developer', 'Data'],
    tags: ['confluent', 'kafka', 'streaming', 'data'],
  },
  {
    id: 'databricks',
    vendor: 'Databricks',
    url: 'https://www.databricks.com/dataaisummit/',
    defaultCategories: ['Data', 'AI', 'Developer'],
    tags: ['databricks', 'data ai summit', 'spark', 'lakehouse'],
  },

  // ── Cloud / Infrastructure — Additional ───────────────────────────────────
  {
    id: 'vmware-explore',
    vendor: 'VMware Explore',
    url: 'https://www.vmware.com/explore.html',
    defaultCategories: ['Cloud', 'IT / Ops'],
    tags: ['vmware', 'virtualization', 'explore', 'cloud'],
  },
  {
    id: 'hashidays',
    vendor: 'HashiDays',
    url: 'https://www.hashicorp.com/events',
    defaultCategories: ['Cloud', 'Developer'],
    tags: ['hashidays', 'hashicorp', 'terraform', 'vault'],
  },
  {
    id: 'devrel-conf',
    vendor: 'DevRelCon',
    url: 'https://developerrelations.com/events',
    defaultCategories: ['Developer'],
    tags: ['devrel', 'developer relations', 'community', 'advocacy'],
  },

];
